/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type {
  ChatCompletionDeleted,
  ChatCompletionList,
  ChatCompletionMessageList,
  CreateChatCompletionRequest,
  CreateChatCompletionResponse,
  CreateChatCompletionStreamResponse,
  GetChatCompletionMessagesParams,
  ListChatCompletionsParams,
  UpdateChatCompletionBody,
} from '.././schemas';

/**
 * @summary List stored Chat Completions. Only Chat Completions that have been stored
with the `store` parameter set to `true` will be returned.

 */
export type listChatCompletionsResponse200 = {
  data: ChatCompletionList;
  status: 200;
};

export type listChatCompletionsResponseComposite =
  listChatCompletionsResponse200;

export type listChatCompletionsResponse =
  listChatCompletionsResponseComposite & {
    headers: Headers;
  };

export const getListChatCompletionsUrl = (
  params?: ListChatCompletionsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/chat/completions?${stringifiedParams}`
    : `/chat/completions`;
};

export const listChatCompletions = async (
  params?: ListChatCompletionsParams,
  options?: RequestInit
): Promise<listChatCompletionsResponse> => {
  const res = await fetch(getListChatCompletionsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listChatCompletionsResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listChatCompletionsResponse;
};

/**
 * @summary **Starting a new project?** We recommend trying [Responses](/docs/api-reference/responses) 
to take advantage of the latest OpenAI platform features. Compare
[Chat Completions with Responses](/docs/guides/responses-vs-chat-completions?api-mode=responses).

---

Creates a model response for the given chat conversation. Learn more in the
[text generation](/docs/guides/text-generation), [vision](/docs/guides/vision),
and [audio](/docs/guides/audio) guides.

Parameter support can differ depending on the model used to generate the
response, particularly for newer reasoning models. Parameters that are only
supported for reasoning models are noted below. For the current state of 
unsupported parameters in reasoning models, 
[refer to the reasoning guide](/docs/guides/reasoning).

 */
export type createChatCompletionResponse200 = {
  data: CreateChatCompletionResponse;
  status: 200;
};

export type createChatCompletionResponse200 = {
  data: CreateChatCompletionStreamResponse;
  status: 200;
};

export type createChatCompletionResponseComposite =
  | createChatCompletionResponse200
  | createChatCompletionResponse200;

export type createChatCompletionResponse =
  createChatCompletionResponseComposite & {
    headers: Headers;
  };

export const getCreateChatCompletionUrl = () => {
  return `/chat/completions`;
};

export const createChatCompletion = async (
  createChatCompletionRequest: CreateChatCompletionRequest,
  options?: RequestInit
): Promise<createChatCompletionResponse> => {
  const res = await fetch(getCreateChatCompletionUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createChatCompletionRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createChatCompletionResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createChatCompletionResponse;
};

/**
 * @summary Get a stored chat completion. Only Chat Completions that have been created
with the `store` parameter set to `true` will be returned.

 */
export type getChatCompletionResponse200 = {
  data: CreateChatCompletionResponse;
  status: 200;
};

export type getChatCompletionResponseComposite = getChatCompletionResponse200;

export type getChatCompletionResponse = getChatCompletionResponseComposite & {
  headers: Headers;
};

export const getGetChatCompletionUrl = (completionId: string) => {
  return `/chat/completions/${completionId}`;
};

export const getChatCompletion = async (
  completionId: string,
  options?: RequestInit
): Promise<getChatCompletionResponse> => {
  const res = await fetch(getGetChatCompletionUrl(completionId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getChatCompletionResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChatCompletionResponse;
};

/**
 * @summary Modify a stored chat completion. Only Chat Completions that have been
created with the `store` parameter set to `true` can be modified. Currently,
the only supported modification is to update the `metadata` field.

 */
export type updateChatCompletionResponse200 = {
  data: CreateChatCompletionResponse;
  status: 200;
};

export type updateChatCompletionResponseComposite =
  updateChatCompletionResponse200;

export type updateChatCompletionResponse =
  updateChatCompletionResponseComposite & {
    headers: Headers;
  };

export const getUpdateChatCompletionUrl = (completionId: string) => {
  return `/chat/completions/${completionId}`;
};

export const updateChatCompletion = async (
  completionId: string,
  updateChatCompletionBody: UpdateChatCompletionBody,
  options?: RequestInit
): Promise<updateChatCompletionResponse> => {
  const res = await fetch(getUpdateChatCompletionUrl(completionId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateChatCompletionBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: updateChatCompletionResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateChatCompletionResponse;
};

/**
 * @summary Delete a stored chat completion. Only Chat Completions that have been
created with the `store` parameter set to `true` can be deleted.

 */
export type deleteChatCompletionResponse200 = {
  data: ChatCompletionDeleted;
  status: 200;
};

export type deleteChatCompletionResponseComposite =
  deleteChatCompletionResponse200;

export type deleteChatCompletionResponse =
  deleteChatCompletionResponseComposite & {
    headers: Headers;
  };

export const getDeleteChatCompletionUrl = (completionId: string) => {
  return `/chat/completions/${completionId}`;
};

export const deleteChatCompletion = async (
  completionId: string,
  options?: RequestInit
): Promise<deleteChatCompletionResponse> => {
  const res = await fetch(getDeleteChatCompletionUrl(completionId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteChatCompletionResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteChatCompletionResponse;
};

/**
 * @summary Get the messages in a stored chat completion. Only Chat Completions that
have been created with the `store` parameter set to `true` will be
returned.

 */
export type getChatCompletionMessagesResponse200 = {
  data: ChatCompletionMessageList;
  status: 200;
};

export type getChatCompletionMessagesResponseComposite =
  getChatCompletionMessagesResponse200;

export type getChatCompletionMessagesResponse =
  getChatCompletionMessagesResponseComposite & {
    headers: Headers;
  };

export const getGetChatCompletionMessagesUrl = (
  completionId: string,
  params?: GetChatCompletionMessagesParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/chat/completions/${completionId}/messages?${stringifiedParams}`
    : `/chat/completions/${completionId}/messages`;
};

export const getChatCompletionMessages = async (
  completionId: string,
  params?: GetChatCompletionMessagesParams,
  options?: RequestInit
): Promise<getChatCompletionMessagesResponse> => {
  const res = await fetch(
    getGetChatCompletionMessagesUrl(completionId, params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getChatCompletionMessagesResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChatCompletionMessagesResponse;
};
