/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type {
  HTTPValidationError,
  RawRequestTypedDict,
  SupportedOpenaiParamsUtilsSupportedOpenaiParamsGetParams,
  TokenCountRequest,
  TokenCountResponse,
  TransformRequestBody,
} from '.././schemas';

/**
 * @summary Token Counter
 */
export type tokenCounterUtilsTokenCounterPostResponse200 = {
  data: TokenCountResponse;
  status: 200;
};

export type tokenCounterUtilsTokenCounterPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type tokenCounterUtilsTokenCounterPostResponseComposite =
  | tokenCounterUtilsTokenCounterPostResponse200
  | tokenCounterUtilsTokenCounterPostResponse422;

export type tokenCounterUtilsTokenCounterPostResponse =
  tokenCounterUtilsTokenCounterPostResponseComposite & {
    headers: Headers;
  };

export const getTokenCounterUtilsTokenCounterPostUrl = () => {
  return `/utils/token_counter`;
};

export const tokenCounterUtilsTokenCounterPost = async (
  tokenCountRequest: TokenCountRequest,
  options?: RequestInit
): Promise<tokenCounterUtilsTokenCounterPostResponse> => {
  const res = await fetch(getTokenCounterUtilsTokenCounterPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tokenCountRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: tokenCounterUtilsTokenCounterPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as tokenCounterUtilsTokenCounterPostResponse;
};

/**
 * Returns supported openai params for a given litellm model name

e.g. `gpt-4` vs `gpt-3.5-turbo`

Example curl:
```
curl -X GET --location 'http://localhost:4000/utils/supported_openai_params?model=gpt-3.5-turbo-16k'         --header 'Authorization: Bearer sk-1234'
```
 * @summary Supported Openai Params
 */
export type supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponseComposite =

    | supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponse200
    | supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponse422;

export type supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponse =
  supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponseComposite & {
    headers: Headers;
  };

export const getSupportedOpenaiParamsUtilsSupportedOpenaiParamsGetUrl = (
  params: SupportedOpenaiParamsUtilsSupportedOpenaiParamsGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/utils/supported_openai_params?${stringifiedParams}`
    : `/utils/supported_openai_params`;
};

export const supportedOpenaiParamsUtilsSupportedOpenaiParamsGet = async (
  params: SupportedOpenaiParamsUtilsSupportedOpenaiParamsGetParams,
  options?: RequestInit
): Promise<supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponse> => {
  const res = await fetch(
    getSupportedOpenaiParamsUtilsSupportedOpenaiParamsGetUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponse['data'] =
    body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as supportedOpenaiParamsUtilsSupportedOpenaiParamsGetResponse;
};

/**
 * @summary Transform Request
 */
export type transformRequestUtilsTransformRequestPostResponse200 = {
  data: RawRequestTypedDict;
  status: 200;
};

export type transformRequestUtilsTransformRequestPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type transformRequestUtilsTransformRequestPostResponseComposite =
  | transformRequestUtilsTransformRequestPostResponse200
  | transformRequestUtilsTransformRequestPostResponse422;

export type transformRequestUtilsTransformRequestPostResponse =
  transformRequestUtilsTransformRequestPostResponseComposite & {
    headers: Headers;
  };

export const getTransformRequestUtilsTransformRequestPostUrl = () => {
  return `/utils/transform_request`;
};

export const transformRequestUtilsTransformRequestPost = async (
  transformRequestBody: TransformRequestBody,
  options?: RequestInit
): Promise<transformRequestUtilsTransformRequestPostResponse> => {
  const res = await fetch(getTransformRequestUtilsTransformRequestPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(transformRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: transformRequestUtilsTransformRequestPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as transformRequestUtilsTransformRequestPostResponse;
};
