
categories:
  - labels:
      - feature
      - enhancement
    title: 🚀 Features
  - labels:
      - bug
    title: 🐛 Bug Fixes
exclude-labels:
  - new release
name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
template: |
  ## Changes

  $CHANGES
version-resolver:
  default: patch
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
