/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { CallbacksByType } from '.././schemas';

/**
 * View List of Active Logging Callbacks
 * @summary List Callbacks
 */
export type listCallbacksCallbacksListGetResponse200 = {
  data: CallbacksByType;
  status: 200;
};

export type listCallbacksCallbacksListGetResponseComposite =
  listCallbacksCallbacksListGetResponse200;

export type listCallbacksCallbacksListGetResponse =
  listCallbacksCallbacksListGetResponseComposite & {
    headers: Headers;
  };

export const getListCallbacksCallbacksListGetUrl = () => {
  return `/callbacks/list`;
};

export const listCallbacksCallbacksListGet = async (
  options?: RequestInit
): Promise<listCallbacksCallbacksListGetResponse> => {
  const res = await fetch(getListCallbacksCallbacksListGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listCallbacksCallbacksListGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listCallbacksCallbacksListGetResponse;
};
