/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { CachePingResponse } from '.././schemas';

/**
 * Endpoint for checking if cache can be pinged
 * @summary Cache Ping
 */
export type cachePingCachePingGetResponse200 = {
  data: CachePingResponse;
  status: 200;
};

export type cachePingCachePingGetResponseComposite =
  cachePingCachePingGetResponse200;

export type cachePingCachePingGetResponse =
  cachePingCachePingGetResponseComposite & {
    headers: Headers;
  };

export const getCachePingCachePingGetUrl = () => {
  return `/cache/ping`;
};

export const cachePingCachePingGet = async (
  options?: RequestInit
): Promise<cachePingCachePingGetResponse> => {
  const res = await fetch(getCachePingCachePingGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cachePingCachePingGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cachePingCachePingGetResponse;
};

/**
 * Endpoint for deleting a key from the cache. All responses from litellm proxy have `x-litellm-cache-key` in the headers

Parameters:
- **keys**: *Optional[List[str]]* - A list of keys to delete from the cache. Example {"keys": ["key1", "key2"]}

```shell
curl -X POST "http://0.0.0.0:4000/cache/delete"     -H "Authorization: Bearer sk-1234"     -d '{"keys": ["key1", "key2"]}'
```
 * @summary Cache Delete
 */
export type cacheDeleteCacheDeletePostResponse200 = {
  data: unknown;
  status: 200;
};

export type cacheDeleteCacheDeletePostResponseComposite =
  cacheDeleteCacheDeletePostResponse200;

export type cacheDeleteCacheDeletePostResponse =
  cacheDeleteCacheDeletePostResponseComposite & {
    headers: Headers;
  };

export const getCacheDeleteCacheDeletePostUrl = () => {
  return `/cache/delete`;
};

export const cacheDeleteCacheDeletePost = async (
  options?: RequestInit
): Promise<cacheDeleteCacheDeletePostResponse> => {
  const res = await fetch(getCacheDeleteCacheDeletePostUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cacheDeleteCacheDeletePostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cacheDeleteCacheDeletePostResponse;
};

/**
 * Endpoint for getting /redis/info
 * @summary Cache Redis Info
 */
export type cacheRedisInfoCacheRedisInfoGetResponse200 = {
  data: unknown;
  status: 200;
};

export type cacheRedisInfoCacheRedisInfoGetResponseComposite =
  cacheRedisInfoCacheRedisInfoGetResponse200;

export type cacheRedisInfoCacheRedisInfoGetResponse =
  cacheRedisInfoCacheRedisInfoGetResponseComposite & {
    headers: Headers;
  };

export const getCacheRedisInfoCacheRedisInfoGetUrl = () => {
  return `/cache/redis/info`;
};

export const cacheRedisInfoCacheRedisInfoGet = async (
  options?: RequestInit
): Promise<cacheRedisInfoCacheRedisInfoGetResponse> => {
  const res = await fetch(getCacheRedisInfoCacheRedisInfoGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cacheRedisInfoCacheRedisInfoGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cacheRedisInfoCacheRedisInfoGetResponse;
};

/**
 * A function to flush all items from the cache. (All items will be deleted from the cache with this)
Raises HTTPException if the cache is not initialized or if the cache type does not support flushing.
Returns a dictionary with the status of the operation.

Usage:
```
curl -X POST http://0.0.0.0:4000/cache/flushall -H "Authorization: Bearer sk-1234"
```
 * @summary Cache Flushall
 */
export type cacheFlushallCacheFlushallPostResponse200 = {
  data: unknown;
  status: 200;
};

export type cacheFlushallCacheFlushallPostResponseComposite =
  cacheFlushallCacheFlushallPostResponse200;

export type cacheFlushallCacheFlushallPostResponse =
  cacheFlushallCacheFlushallPostResponseComposite & {
    headers: Headers;
  };

export const getCacheFlushallCacheFlushallPostUrl = () => {
  return `/cache/flushall`;
};

export const cacheFlushallCacheFlushallPost = async (
  options?: RequestInit
): Promise<cacheFlushallCacheFlushallPostResponse> => {
  const res = await fetch(getCacheFlushallCacheFlushallPostUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cacheFlushallCacheFlushallPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cacheFlushallCacheFlushallPostResponse;
};
