/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { HTTPValidationError } from '.././schemas';

/**
 * Follows the OpenAI Responses API spec: https://platform.openai.com/docs/api-reference/responses

```bash
curl -X POST http://localhost:4000/v1/responses     -H "Content-Type: application/json"     -H "Authorization: Bearer sk-1234"     -d '{
    "model": "gpt-4o",
    "input": "Tell me about AI"
}'
```
 * @summary Responses Api
 */
export type responsesApiResponsesPostResponse200 = {
  data: unknown;
  status: 200;
};

export type responsesApiResponsesPostResponseComposite =
  responsesApiResponsesPostResponse200;

export type responsesApiResponsesPostResponse =
  responsesApiResponsesPostResponseComposite & {
    headers: Headers;
  };

export const getResponsesApiResponsesPostUrl = () => {
  return `/responses`;
};

export const responsesApiResponsesPost = async (
  options?: RequestInit
): Promise<responsesApiResponsesPostResponse> => {
  const res = await fetch(getResponsesApiResponsesPostUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: responsesApiResponsesPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as responsesApiResponsesPostResponse;
};

/**
 * Follows the OpenAI Responses API spec: https://platform.openai.com/docs/api-reference/responses

```bash
curl -X POST http://localhost:4000/v1/responses     -H "Content-Type: application/json"     -H "Authorization: Bearer sk-1234"     -d '{
    "model": "gpt-4o",
    "input": "Tell me about AI"
}'
```
 * @summary Responses Api
 */
export type responsesApiV1ResponsesPostResponse200 = {
  data: unknown;
  status: 200;
};

export type responsesApiV1ResponsesPostResponseComposite =
  responsesApiV1ResponsesPostResponse200;

export type responsesApiV1ResponsesPostResponse =
  responsesApiV1ResponsesPostResponseComposite & {
    headers: Headers;
  };

export const getResponsesApiV1ResponsesPostUrl = () => {
  return `/v1/responses`;
};

export const responsesApiV1ResponsesPost = async (
  options?: RequestInit
): Promise<responsesApiV1ResponsesPostResponse> => {
  const res = await fetch(getResponsesApiV1ResponsesPostUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: responsesApiV1ResponsesPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as responsesApiV1ResponsesPostResponse;
};

/**
 * Get a response by ID.

Follows the OpenAI Responses API spec: https://platform.openai.com/docs/api-reference/responses/get

```bash
curl -X GET http://localhost:4000/v1/responses/resp_abc123     -H "Authorization: Bearer sk-1234"
```
 * @summary Get Response
 */
export type getResponseResponsesResponseIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getResponseResponsesResponseIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getResponseResponsesResponseIdGetResponseComposite =
  | getResponseResponsesResponseIdGetResponse200
  | getResponseResponsesResponseIdGetResponse422;

export type getResponseResponsesResponseIdGetResponse =
  getResponseResponsesResponseIdGetResponseComposite & {
    headers: Headers;
  };

export const getGetResponseResponsesResponseIdGetUrl = (responseId: string) => {
  return `/responses/${responseId}`;
};

export const getResponseResponsesResponseIdGet = async (
  responseId: string,
  options?: RequestInit
): Promise<getResponseResponsesResponseIdGetResponse> => {
  const res = await fetch(getGetResponseResponsesResponseIdGetUrl(responseId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getResponseResponsesResponseIdGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getResponseResponsesResponseIdGetResponse;
};

/**
 * Delete a response by ID.

Follows the OpenAI Responses API spec: https://platform.openai.com/docs/api-reference/responses/delete

```bash
curl -X DELETE http://localhost:4000/v1/responses/resp_abc123     -H "Authorization: Bearer sk-1234"
```
 * @summary Delete Response
 */
export type deleteResponseResponsesResponseIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteResponseResponsesResponseIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteResponseResponsesResponseIdDeleteResponseComposite =
  | deleteResponseResponsesResponseIdDeleteResponse200
  | deleteResponseResponsesResponseIdDeleteResponse422;

export type deleteResponseResponsesResponseIdDeleteResponse =
  deleteResponseResponsesResponseIdDeleteResponseComposite & {
    headers: Headers;
  };

export const getDeleteResponseResponsesResponseIdDeleteUrl = (
  responseId: string
) => {
  return `/responses/${responseId}`;
};

export const deleteResponseResponsesResponseIdDelete = async (
  responseId: string,
  options?: RequestInit
): Promise<deleteResponseResponsesResponseIdDeleteResponse> => {
  const res = await fetch(
    getDeleteResponseResponsesResponseIdDeleteUrl(responseId),
    {
      ...options,
      method: 'DELETE',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteResponseResponsesResponseIdDeleteResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteResponseResponsesResponseIdDeleteResponse;
};

/**
 * Get a response by ID.

Follows the OpenAI Responses API spec: https://platform.openai.com/docs/api-reference/responses/get

```bash
curl -X GET http://localhost:4000/v1/responses/resp_abc123     -H "Authorization: Bearer sk-1234"
```
 * @summary Get Response
 */
export type getResponseV1ResponsesResponseIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getResponseV1ResponsesResponseIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getResponseV1ResponsesResponseIdGetResponseComposite =
  | getResponseV1ResponsesResponseIdGetResponse200
  | getResponseV1ResponsesResponseIdGetResponse422;

export type getResponseV1ResponsesResponseIdGetResponse =
  getResponseV1ResponsesResponseIdGetResponseComposite & {
    headers: Headers;
  };

export const getGetResponseV1ResponsesResponseIdGetUrl = (
  responseId: string
) => {
  return `/v1/responses/${responseId}`;
};

export const getResponseV1ResponsesResponseIdGet = async (
  responseId: string,
  options?: RequestInit
): Promise<getResponseV1ResponsesResponseIdGetResponse> => {
  const res = await fetch(
    getGetResponseV1ResponsesResponseIdGetUrl(responseId),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getResponseV1ResponsesResponseIdGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getResponseV1ResponsesResponseIdGetResponse;
};

/**
 * Delete a response by ID.

Follows the OpenAI Responses API spec: https://platform.openai.com/docs/api-reference/responses/delete

```bash
curl -X DELETE http://localhost:4000/v1/responses/resp_abc123     -H "Authorization: Bearer sk-1234"
```
 * @summary Delete Response
 */
export type deleteResponseV1ResponsesResponseIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteResponseV1ResponsesResponseIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteResponseV1ResponsesResponseIdDeleteResponseComposite =
  | deleteResponseV1ResponsesResponseIdDeleteResponse200
  | deleteResponseV1ResponsesResponseIdDeleteResponse422;

export type deleteResponseV1ResponsesResponseIdDeleteResponse =
  deleteResponseV1ResponsesResponseIdDeleteResponseComposite & {
    headers: Headers;
  };

export const getDeleteResponseV1ResponsesResponseIdDeleteUrl = (
  responseId: string
) => {
  return `/v1/responses/${responseId}`;
};

export const deleteResponseV1ResponsesResponseIdDelete = async (
  responseId: string,
  options?: RequestInit
): Promise<deleteResponseV1ResponsesResponseIdDeleteResponse> => {
  const res = await fetch(
    getDeleteResponseV1ResponsesResponseIdDeleteUrl(responseId),
    {
      ...options,
      method: 'DELETE',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteResponseV1ResponsesResponseIdDeleteResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteResponseV1ResponsesResponseIdDeleteResponse;
};

/**
 * List input items for a response.
 * @summary Get Response Input Items
 */
export type getResponseInputItemsResponsesResponseIdInputItemsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getResponseInputItemsResponsesResponseIdInputItemsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getResponseInputItemsResponsesResponseIdInputItemsGetResponseComposite =

    | getResponseInputItemsResponsesResponseIdInputItemsGetResponse200
    | getResponseInputItemsResponsesResponseIdInputItemsGetResponse422;

export type getResponseInputItemsResponsesResponseIdInputItemsGetResponse =
  getResponseInputItemsResponsesResponseIdInputItemsGetResponseComposite & {
    headers: Headers;
  };

export const getGetResponseInputItemsResponsesResponseIdInputItemsGetUrl = (
  responseId: string
) => {
  return `/responses/${responseId}/input_items`;
};

export const getResponseInputItemsResponsesResponseIdInputItemsGet = async (
  responseId: string,
  options?: RequestInit
): Promise<getResponseInputItemsResponsesResponseIdInputItemsGetResponse> => {
  const res = await fetch(
    getGetResponseInputItemsResponsesResponseIdInputItemsGetUrl(responseId),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getResponseInputItemsResponsesResponseIdInputItemsGetResponse['data'] =
    body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getResponseInputItemsResponsesResponseIdInputItemsGetResponse;
};

/**
 * List input items for a response.
 * @summary Get Response Input Items
 */
export type getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponse200 =
  {
    data: unknown;
    status: 200;
  };

export type getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponse422 =
  {
    data: HTTPValidationError;
    status: 422;
  };

export type getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponseComposite =

    | getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponse200
    | getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponse422;

export type getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponse =
  getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponseComposite & {
    headers: Headers;
  };

export const getGetResponseInputItemsV1ResponsesResponseIdInputItemsGetUrl = (
  responseId: string
) => {
  return `/v1/responses/${responseId}/input_items`;
};

export const getResponseInputItemsV1ResponsesResponseIdInputItemsGet = async (
  responseId: string,
  options?: RequestInit
): Promise<getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponse> => {
  const res = await fetch(
    getGetResponseInputItemsV1ResponsesResponseIdInputItemsGetUrl(responseId),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponse['data'] =
    body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getResponseInputItemsV1ResponsesResponseIdInputItemsGetResponse;
};
