/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */

/**
 * The moderations endpoint is a tool you can use to check whether content complies with an LLM Providers policies.
Quick Start
```
curl --location 'http://0.0.0.0:4000/moderations'     --header 'Content-Type: application/json'     --header 'Authorization: Bearer sk-1234'     --data '{"input": "Sample text goes here", "model": "text-moderation-stable"}'
```
 * @summary Moderations
 */
export type moderationsModerationsPostResponse200 = {
  data: unknown;
  status: 200;
};

export type moderationsModerationsPostResponseComposite =
  moderationsModerationsPostResponse200;

export type moderationsModerationsPostResponse =
  moderationsModerationsPostResponseComposite & {
    headers: Headers;
  };

export const getModerationsModerationsPostUrl = () => {
  return `/moderations`;
};

export const moderationsModerationsPost = async (
  options?: RequestInit
): Promise<moderationsModerationsPostResponse> => {
  const res = await fetch(getModerationsModerationsPostUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: moderationsModerationsPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as moderationsModerationsPostResponse;
};

/**
 * The moderations endpoint is a tool you can use to check whether content complies with an LLM Providers policies.
Quick Start
```
curl --location 'http://0.0.0.0:4000/moderations'     --header 'Content-Type: application/json'     --header 'Authorization: Bearer sk-1234'     --data '{"input": "Sample text goes here", "model": "text-moderation-stable"}'
```
 * @summary Moderations
 */
export type moderationsV1ModerationsPostResponse200 = {
  data: unknown;
  status: 200;
};

export type moderationsV1ModerationsPostResponseComposite =
  moderationsV1ModerationsPostResponse200;

export type moderationsV1ModerationsPostResponse =
  moderationsV1ModerationsPostResponseComposite & {
    headers: Headers;
  };

export const getModerationsV1ModerationsPostUrl = () => {
  return `/v1/moderations`;
};

export const moderationsV1ModerationsPost = async (
  options?: RequestInit
): Promise<moderationsV1ModerationsPostResponse> => {
  const res = await fetch(getModerationsV1ModerationsPostUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: moderationsV1ModerationsPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as moderationsV1ModerationsPostResponse;
};
