/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type {
  HTTPValidationError,
  ListToolRestApiMcpRestToolsListGet200,
  ListToolRestApiMcpRestToolsListGetParams,
  LiteLLMMCPServerTable,
  NewMCPServerRequest,
  UpdateMCPServerRequest,
} from '.././models';

/**
 * Get all MCP tools available for the current key, including those from access groups
 * @summary Get Mcp Tools
 */
export type getMcpToolsV1McpToolsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getMcpToolsV1McpToolsGetResponseComposite =
  getMcpToolsV1McpToolsGetResponse200;

export type getMcpToolsV1McpToolsGetResponse =
  getMcpToolsV1McpToolsGetResponseComposite & {
    headers: Headers;
  };

export const getGetMcpToolsV1McpToolsGetUrl = () => {
  return `/v1/mcp/tools`;
};

export const getMcpToolsV1McpToolsGet = async (
  options?: RequestInit
): Promise<getMcpToolsV1McpToolsGetResponse> => {
  const res = await fetch(getGetMcpToolsV1McpToolsGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getMcpToolsV1McpToolsGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMcpToolsV1McpToolsGetResponse;
};

/**
 * Get all available MCP access groups from the database AND config
 * @summary Get Mcp Access Groups
 */
export type getMcpAccessGroupsV1McpAccessGroupsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getMcpAccessGroupsV1McpAccessGroupsGetResponseComposite =
  getMcpAccessGroupsV1McpAccessGroupsGetResponse200;

export type getMcpAccessGroupsV1McpAccessGroupsGetResponse =
  getMcpAccessGroupsV1McpAccessGroupsGetResponseComposite & {
    headers: Headers;
  };

export const getGetMcpAccessGroupsV1McpAccessGroupsGetUrl = () => {
  return `/v1/mcp/access_groups`;
};

export const getMcpAccessGroupsV1McpAccessGroupsGet = async (
  options?: RequestInit
): Promise<getMcpAccessGroupsV1McpAccessGroupsGetResponse> => {
  const res = await fetch(getGetMcpAccessGroupsV1McpAccessGroupsGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getMcpAccessGroupsV1McpAccessGroupsGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMcpAccessGroupsV1McpAccessGroupsGetResponse;
};

/**
 * Returns the mcp server list with associated teams
 * @summary Fetch All Mcp Servers
 */
export type fetchAllMcpServersV1McpServerGetResponse200 = {
  data: LiteLLMMCPServerTable[];
  status: 200;
};

export type fetchAllMcpServersV1McpServerGetResponseComposite =
  fetchAllMcpServersV1McpServerGetResponse200;

export type fetchAllMcpServersV1McpServerGetResponse =
  fetchAllMcpServersV1McpServerGetResponseComposite & {
    headers: Headers;
  };

export const getFetchAllMcpServersV1McpServerGetUrl = () => {
  return `/v1/mcp/server`;
};

export const fetchAllMcpServersV1McpServerGet = async (
  options?: RequestInit
): Promise<fetchAllMcpServersV1McpServerGetResponse> => {
  const res = await fetch(getFetchAllMcpServersV1McpServerGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: fetchAllMcpServersV1McpServerGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as fetchAllMcpServersV1McpServerGetResponse;
};

/**
 * Allows creation of mcp servers
 * @summary Add Mcp Server
 */
export type addMcpServerV1McpServerPostResponse201 = {
  data: LiteLLMMCPServerTable;
  status: 201;
};

export type addMcpServerV1McpServerPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type addMcpServerV1McpServerPostResponseComposite =
  | addMcpServerV1McpServerPostResponse201
  | addMcpServerV1McpServerPostResponse422;

export type addMcpServerV1McpServerPostResponse =
  addMcpServerV1McpServerPostResponseComposite & {
    headers: Headers;
  };

export const getAddMcpServerV1McpServerPostUrl = () => {
  return `/v1/mcp/server`;
};

export const addMcpServerV1McpServerPost = async (
  newMCPServerRequest: NewMCPServerRequest,
  options?: RequestInit
): Promise<addMcpServerV1McpServerPostResponse> => {
  const res = await fetch(getAddMcpServerV1McpServerPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(newMCPServerRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: addMcpServerV1McpServerPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as addMcpServerV1McpServerPostResponse;
};

/**
 * Allows deleting mcp serves in the db
 * @summary Edit Mcp Server
 */
export type editMcpServerV1McpServerPutResponse202 = {
  data: LiteLLMMCPServerTable;
  status: 202;
};

export type editMcpServerV1McpServerPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type editMcpServerV1McpServerPutResponseComposite =
  | editMcpServerV1McpServerPutResponse202
  | editMcpServerV1McpServerPutResponse422;

export type editMcpServerV1McpServerPutResponse =
  editMcpServerV1McpServerPutResponseComposite & {
    headers: Headers;
  };

export const getEditMcpServerV1McpServerPutUrl = () => {
  return `/v1/mcp/server`;
};

export const editMcpServerV1McpServerPut = async (
  updateMCPServerRequest: UpdateMCPServerRequest,
  options?: RequestInit
): Promise<editMcpServerV1McpServerPutResponse> => {
  const res = await fetch(getEditMcpServerV1McpServerPutUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateMCPServerRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: editMcpServerV1McpServerPutResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as editMcpServerV1McpServerPutResponse;
};

/**
 * Returns the mcp server info
 * @summary Fetch Mcp Server
 */
export type fetchMcpServerV1McpServerServerIdGetResponse200 = {
  data: LiteLLMMCPServerTable;
  status: 200;
};

export type fetchMcpServerV1McpServerServerIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type fetchMcpServerV1McpServerServerIdGetResponseComposite =
  | fetchMcpServerV1McpServerServerIdGetResponse200
  | fetchMcpServerV1McpServerServerIdGetResponse422;

export type fetchMcpServerV1McpServerServerIdGetResponse =
  fetchMcpServerV1McpServerServerIdGetResponseComposite & {
    headers: Headers;
  };

export const getFetchMcpServerV1McpServerServerIdGetUrl = (
  serverId: string
) => {
  return `/v1/mcp/server/${serverId}`;
};

export const fetchMcpServerV1McpServerServerIdGet = async (
  serverId: string,
  options?: RequestInit
): Promise<fetchMcpServerV1McpServerServerIdGetResponse> => {
  const res = await fetch(
    getFetchMcpServerV1McpServerServerIdGetUrl(serverId),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: fetchMcpServerV1McpServerServerIdGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as fetchMcpServerV1McpServerServerIdGetResponse;
};

/**
 * Allows deleting mcp serves in the db
 * @summary Remove Mcp Server
 */
export type removeMcpServerV1McpServerServerIdDeleteResponse202 = {
  data: unknown;
  status: 202;
};

export type removeMcpServerV1McpServerServerIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type removeMcpServerV1McpServerServerIdDeleteResponseComposite =
  | removeMcpServerV1McpServerServerIdDeleteResponse202
  | removeMcpServerV1McpServerServerIdDeleteResponse422;

export type removeMcpServerV1McpServerServerIdDeleteResponse =
  removeMcpServerV1McpServerServerIdDeleteResponseComposite & {
    headers: Headers;
  };

export const getRemoveMcpServerV1McpServerServerIdDeleteUrl = (
  serverId: string
) => {
  return `/v1/mcp/server/${serverId}`;
};

export const removeMcpServerV1McpServerServerIdDelete = async (
  serverId: string,
  options?: RequestInit
): Promise<removeMcpServerV1McpServerServerIdDeleteResponse> => {
  const res = await fetch(
    getRemoveMcpServerV1McpServerServerIdDeleteUrl(serverId),
    {
      ...options,
      method: 'DELETE',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: removeMcpServerV1McpServerServerIdDeleteResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as removeMcpServerV1McpServerServerIdDeleteResponse;
};

/**
 * List all available tools with information about the server they belong to.

Example response:
{
    "tools": [
        {
            "name": "create_zap",
            "description": "Create a new zap",
            "inputSchema": "tool_input_schema",
            "mcp_info": {
                "server_name": "zapier",
                "logo_url": "https://www.zapier.com/logo.png",
            }
        }
    ],
    "error": null,
    "message": "Successfully retrieved tools"
}
 * @summary List Tool Rest Api
 */
export type listToolRestApiMcpRestToolsListGetResponse200 = {
  data: ListToolRestApiMcpRestToolsListGet200;
  status: 200;
};

export type listToolRestApiMcpRestToolsListGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listToolRestApiMcpRestToolsListGetResponseComposite =
  | listToolRestApiMcpRestToolsListGetResponse200
  | listToolRestApiMcpRestToolsListGetResponse422;

export type listToolRestApiMcpRestToolsListGetResponse =
  listToolRestApiMcpRestToolsListGetResponseComposite & {
    headers: Headers;
  };

export const getListToolRestApiMcpRestToolsListGetUrl = (
  params?: ListToolRestApiMcpRestToolsListGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/mcp-rest/tools/list?${stringifiedParams}`
    : `/mcp-rest/tools/list`;
};

export const listToolRestApiMcpRestToolsListGet = async (
  params?: ListToolRestApiMcpRestToolsListGetParams,
  options?: RequestInit
): Promise<listToolRestApiMcpRestToolsListGetResponse> => {
  const res = await fetch(getListToolRestApiMcpRestToolsListGetUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listToolRestApiMcpRestToolsListGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listToolRestApiMcpRestToolsListGetResponse;
};

/**
 * REST API to call a specific MCP tool with the provided arguments
 * @summary Call Tool Rest Api
 */
export type callToolRestApiMcpRestToolsCallPostResponse200 = {
  data: unknown;
  status: 200;
};

export type callToolRestApiMcpRestToolsCallPostResponseComposite =
  callToolRestApiMcpRestToolsCallPostResponse200;

export type callToolRestApiMcpRestToolsCallPostResponse =
  callToolRestApiMcpRestToolsCallPostResponseComposite & {
    headers: Headers;
  };

export const getCallToolRestApiMcpRestToolsCallPostUrl = () => {
  return `/mcp-rest/tools/call`;
};

export const callToolRestApiMcpRestToolsCallPost = async (
  options?: RequestInit
): Promise<callToolRestApiMcpRestToolsCallPostResponse> => {
  const res = await fetch(getCallToolRestApiMcpRestToolsCallPostUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: callToolRestApiMcpRestToolsCallPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as callToolRestApiMcpRestToolsCallPostResponse;
};

/**
 * Test if we can connect to the provided MCP server before adding it
 * @summary Test Connection
 */
export type testConnectionMcpRestTestConnectionPostResponse200 = {
  data: unknown;
  status: 200;
};

export type testConnectionMcpRestTestConnectionPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type testConnectionMcpRestTestConnectionPostResponseComposite =
  | testConnectionMcpRestTestConnectionPostResponse200
  | testConnectionMcpRestTestConnectionPostResponse422;

export type testConnectionMcpRestTestConnectionPostResponse =
  testConnectionMcpRestTestConnectionPostResponseComposite & {
    headers: Headers;
  };

export const getTestConnectionMcpRestTestConnectionPostUrl = () => {
  return `/mcp-rest/test/connection`;
};

export const testConnectionMcpRestTestConnectionPost = async (
  newMCPServerRequest: NewMCPServerRequest,
  options?: RequestInit
): Promise<testConnectionMcpRestTestConnectionPostResponse> => {
  const res = await fetch(getTestConnectionMcpRestTestConnectionPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(newMCPServerRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: testConnectionMcpRestTestConnectionPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as testConnectionMcpRestTestConnectionPostResponse;
};

/**
 * Preview tools available from MCP server before adding it
 * @summary Test Tools List
 */
export type testToolsListMcpRestTestToolsListPostResponse200 = {
  data: unknown;
  status: 200;
};

export type testToolsListMcpRestTestToolsListPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type testToolsListMcpRestTestToolsListPostResponseComposite =
  | testToolsListMcpRestTestToolsListPostResponse200
  | testToolsListMcpRestTestToolsListPostResponse422;

export type testToolsListMcpRestTestToolsListPostResponse =
  testToolsListMcpRestTestToolsListPostResponseComposite & {
    headers: Headers;
  };

export const getTestToolsListMcpRestTestToolsListPostUrl = () => {
  return `/mcp-rest/test/tools/list`;
};

export const testToolsListMcpRestTestToolsListPost = async (
  newMCPServerRequest: NewMCPServerRequest,
  options?: RequestInit
): Promise<testToolsListMcpRestTestToolsListPostResponse> => {
  const res = await fetch(getTestToolsListMcpRestTestToolsListPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(newMCPServerRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: testToolsListMcpRestTestToolsListPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as testToolsListMcpRestTestToolsListPostResponse;
};
