/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type {
  CreateFineTuningCheckpointPermissionRequest,
  CreateFineTuningJobRequest,
  DeleteFineTuningCheckpointPermissionResponse,
  FineTuningJob,
  ListFineTuningCheckpointPermissionResponse,
  ListFineTuningCheckpointPermissionsParams,
  ListFineTuningEventsParams,
  ListFineTuningJobCheckpointsParams,
  ListFineTuningJobCheckpointsResponse,
  ListFineTuningJobEventsResponse,
  ListPaginatedFineTuningJobsParams,
  ListPaginatedFineTuningJobsResponse,
  RunGraderRequest,
  RunGraderResponse,
  ValidateGraderRequest,
  ValidateGraderResponse,
} from '.././schemas';

/**
 * @summary Run a grader.

 */
export type runGraderResponse200 = {
  data: RunGraderResponse;
  status: 200;
};

export type runGraderResponseComposite = runGraderResponse200;

export type runGraderResponse = runGraderResponseComposite & {
  headers: Headers;
};

export const getRunGraderUrl = () => {
  return `/fine_tuning/alpha/graders/run`;
};

export const runGrader = async (
  runGraderRequest: RunGraderRequest,
  options?: RequestInit
): Promise<runGraderResponse> => {
  const res = await fetch(getRunGraderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(runGraderRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: runGraderResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as runGraderResponse;
};

/**
 * @summary Validate a grader.

 */
export type validateGraderResponse200 = {
  data: ValidateGraderResponse;
  status: 200;
};

export type validateGraderResponseComposite = validateGraderResponse200;

export type validateGraderResponse = validateGraderResponseComposite & {
  headers: Headers;
};

export const getValidateGraderUrl = () => {
  return `/fine_tuning/alpha/graders/validate`;
};

export const validateGrader = async (
  validateGraderRequest: ValidateGraderRequest,
  options?: RequestInit
): Promise<validateGraderResponse> => {
  const res = await fetch(getValidateGraderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(validateGraderRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: validateGraderResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as validateGraderResponse;
};

/**
 * @summary **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).

Organization owners can use this endpoint to view all permissions for a fine-tuned model checkpoint.

 */
export type listFineTuningCheckpointPermissionsResponse200 = {
  data: ListFineTuningCheckpointPermissionResponse;
  status: 200;
};

export type listFineTuningCheckpointPermissionsResponseComposite =
  listFineTuningCheckpointPermissionsResponse200;

export type listFineTuningCheckpointPermissionsResponse =
  listFineTuningCheckpointPermissionsResponseComposite & {
    headers: Headers;
  };

export const getListFineTuningCheckpointPermissionsUrl = (
  fineTunedModelCheckpoint: string,
  params?: ListFineTuningCheckpointPermissionsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/fine_tuning/checkpoints/${fineTunedModelCheckpoint}/permissions?${stringifiedParams}`
    : `/fine_tuning/checkpoints/${fineTunedModelCheckpoint}/permissions`;
};

export const listFineTuningCheckpointPermissions = async (
  fineTunedModelCheckpoint: string,
  params?: ListFineTuningCheckpointPermissionsParams,
  options?: RequestInit
): Promise<listFineTuningCheckpointPermissionsResponse> => {
  const res = await fetch(
    getListFineTuningCheckpointPermissionsUrl(fineTunedModelCheckpoint, params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listFineTuningCheckpointPermissionsResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listFineTuningCheckpointPermissionsResponse;
};

/**
 * @summary **NOTE:** Calling this endpoint requires an [admin API key](../admin-api-keys).

This enables organization owners to share fine-tuned models with other projects in their organization.

 */
export type createFineTuningCheckpointPermissionResponse200 = {
  data: ListFineTuningCheckpointPermissionResponse;
  status: 200;
};

export type createFineTuningCheckpointPermissionResponseComposite =
  createFineTuningCheckpointPermissionResponse200;

export type createFineTuningCheckpointPermissionResponse =
  createFineTuningCheckpointPermissionResponseComposite & {
    headers: Headers;
  };

export const getCreateFineTuningCheckpointPermissionUrl = (
  fineTunedModelCheckpoint: string
) => {
  return `/fine_tuning/checkpoints/${fineTunedModelCheckpoint}/permissions`;
};

export const createFineTuningCheckpointPermission = async (
  fineTunedModelCheckpoint: string,
  createFineTuningCheckpointPermissionRequest: CreateFineTuningCheckpointPermissionRequest,
  options?: RequestInit
): Promise<createFineTuningCheckpointPermissionResponse> => {
  const res = await fetch(
    getCreateFineTuningCheckpointPermissionUrl(fineTunedModelCheckpoint),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createFineTuningCheckpointPermissionRequest),
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createFineTuningCheckpointPermissionResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createFineTuningCheckpointPermissionResponse;
};

/**
 * @summary **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).

Organization owners can use this endpoint to delete a permission for a fine-tuned model checkpoint.

 */
export type deleteFineTuningCheckpointPermissionResponse200 = {
  data: DeleteFineTuningCheckpointPermissionResponse;
  status: 200;
};

export type deleteFineTuningCheckpointPermissionResponseComposite =
  deleteFineTuningCheckpointPermissionResponse200;

export type deleteFineTuningCheckpointPermissionResponse =
  deleteFineTuningCheckpointPermissionResponseComposite & {
    headers: Headers;
  };

export const getDeleteFineTuningCheckpointPermissionUrl = (
  fineTunedModelCheckpoint: string,
  permissionId: string
) => {
  return `/fine_tuning/checkpoints/${fineTunedModelCheckpoint}/permissions/${permissionId}`;
};

export const deleteFineTuningCheckpointPermission = async (
  fineTunedModelCheckpoint: string,
  permissionId: string,
  options?: RequestInit
): Promise<deleteFineTuningCheckpointPermissionResponse> => {
  const res = await fetch(
    getDeleteFineTuningCheckpointPermissionUrl(
      fineTunedModelCheckpoint,
      permissionId
    ),
    {
      ...options,
      method: 'DELETE',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteFineTuningCheckpointPermissionResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteFineTuningCheckpointPermissionResponse;
};

/**
 * @summary Creates a fine-tuning job which begins the process of creating a new model from a given dataset.

Response includes details of the enqueued job including job status and the name of the fine-tuned models once complete.

[Learn more about fine-tuning](/docs/guides/model-optimization)

 */
export type createFineTuningJobResponse200 = {
  data: FineTuningJob;
  status: 200;
};

export type createFineTuningJobResponseComposite =
  createFineTuningJobResponse200;

export type createFineTuningJobResponse =
  createFineTuningJobResponseComposite & {
    headers: Headers;
  };

export const getCreateFineTuningJobUrl = () => {
  return `/fine_tuning/jobs`;
};

export const createFineTuningJob = async (
  createFineTuningJobRequest: CreateFineTuningJobRequest,
  options?: RequestInit
): Promise<createFineTuningJobResponse> => {
  const res = await fetch(getCreateFineTuningJobUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFineTuningJobRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createFineTuningJobResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createFineTuningJobResponse;
};

/**
 * @summary List your organization's fine-tuning jobs

 */
export type listPaginatedFineTuningJobsResponse200 = {
  data: ListPaginatedFineTuningJobsResponse;
  status: 200;
};

export type listPaginatedFineTuningJobsResponseComposite =
  listPaginatedFineTuningJobsResponse200;

export type listPaginatedFineTuningJobsResponse =
  listPaginatedFineTuningJobsResponseComposite & {
    headers: Headers;
  };

export const getListPaginatedFineTuningJobsUrl = (
  params?: ListPaginatedFineTuningJobsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ['metadata'];

    if (value instanceof Array && explodeParameters.includes(key)) {
      value.forEach((v) =>
        normalizedParams.append(key, v === null ? 'null' : v.toString())
      );
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/fine_tuning/jobs?${stringifiedParams}`
    : `/fine_tuning/jobs`;
};

export const listPaginatedFineTuningJobs = async (
  params?: ListPaginatedFineTuningJobsParams,
  options?: RequestInit
): Promise<listPaginatedFineTuningJobsResponse> => {
  const res = await fetch(getListPaginatedFineTuningJobsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listPaginatedFineTuningJobsResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listPaginatedFineTuningJobsResponse;
};

/**
 * @summary Get info about a fine-tuning job.

[Learn more about fine-tuning](/docs/guides/model-optimization)

 */
export type retrieveFineTuningJobResponse200 = {
  data: FineTuningJob;
  status: 200;
};

export type retrieveFineTuningJobResponseComposite =
  retrieveFineTuningJobResponse200;

export type retrieveFineTuningJobResponse =
  retrieveFineTuningJobResponseComposite & {
    headers: Headers;
  };

export const getRetrieveFineTuningJobUrl = (fineTuningJobId: string) => {
  return `/fine_tuning/jobs/${fineTuningJobId}`;
};

export const retrieveFineTuningJob = async (
  fineTuningJobId: string,
  options?: RequestInit
): Promise<retrieveFineTuningJobResponse> => {
  const res = await fetch(getRetrieveFineTuningJobUrl(fineTuningJobId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveFineTuningJobResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveFineTuningJobResponse;
};

/**
 * @summary Immediately cancel a fine-tune job.

 */
export type cancelFineTuningJobResponse200 = {
  data: FineTuningJob;
  status: 200;
};

export type cancelFineTuningJobResponseComposite =
  cancelFineTuningJobResponse200;

export type cancelFineTuningJobResponse =
  cancelFineTuningJobResponseComposite & {
    headers: Headers;
  };

export const getCancelFineTuningJobUrl = (fineTuningJobId: string) => {
  return `/fine_tuning/jobs/${fineTuningJobId}/cancel`;
};

export const cancelFineTuningJob = async (
  fineTuningJobId: string,
  options?: RequestInit
): Promise<cancelFineTuningJobResponse> => {
  const res = await fetch(getCancelFineTuningJobUrl(fineTuningJobId), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cancelFineTuningJobResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cancelFineTuningJobResponse;
};

/**
 * @summary List checkpoints for a fine-tuning job.

 */
export type listFineTuningJobCheckpointsResponse200 = {
  data: ListFineTuningJobCheckpointsResponse;
  status: 200;
};

export type listFineTuningJobCheckpointsResponseComposite =
  listFineTuningJobCheckpointsResponse200;

export type listFineTuningJobCheckpointsResponse =
  listFineTuningJobCheckpointsResponseComposite & {
    headers: Headers;
  };

export const getListFineTuningJobCheckpointsUrl = (
  fineTuningJobId: string,
  params?: ListFineTuningJobCheckpointsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/fine_tuning/jobs/${fineTuningJobId}/checkpoints?${stringifiedParams}`
    : `/fine_tuning/jobs/${fineTuningJobId}/checkpoints`;
};

export const listFineTuningJobCheckpoints = async (
  fineTuningJobId: string,
  params?: ListFineTuningJobCheckpointsParams,
  options?: RequestInit
): Promise<listFineTuningJobCheckpointsResponse> => {
  const res = await fetch(
    getListFineTuningJobCheckpointsUrl(fineTuningJobId, params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listFineTuningJobCheckpointsResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listFineTuningJobCheckpointsResponse;
};

/**
 * @summary Get status updates for a fine-tuning job.

 */
export type listFineTuningEventsResponse200 = {
  data: ListFineTuningJobEventsResponse;
  status: 200;
};

export type listFineTuningEventsResponseComposite =
  listFineTuningEventsResponse200;

export type listFineTuningEventsResponse =
  listFineTuningEventsResponseComposite & {
    headers: Headers;
  };

export const getListFineTuningEventsUrl = (
  fineTuningJobId: string,
  params?: ListFineTuningEventsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/fine_tuning/jobs/${fineTuningJobId}/events?${stringifiedParams}`
    : `/fine_tuning/jobs/${fineTuningJobId}/events`;
};

export const listFineTuningEvents = async (
  fineTuningJobId: string,
  params?: ListFineTuningEventsParams,
  options?: RequestInit
): Promise<listFineTuningEventsResponse> => {
  const res = await fetch(getListFineTuningEventsUrl(fineTuningJobId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listFineTuningEventsResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listFineTuningEventsResponse;
};

/**
 * @summary Pause a fine-tune job.

 */
export type pauseFineTuningJobResponse200 = {
  data: FineTuningJob;
  status: 200;
};

export type pauseFineTuningJobResponseComposite = pauseFineTuningJobResponse200;

export type pauseFineTuningJobResponse = pauseFineTuningJobResponseComposite & {
  headers: Headers;
};

export const getPauseFineTuningJobUrl = (fineTuningJobId: string) => {
  return `/fine_tuning/jobs/${fineTuningJobId}/pause`;
};

export const pauseFineTuningJob = async (
  fineTuningJobId: string,
  options?: RequestInit
): Promise<pauseFineTuningJobResponse> => {
  const res = await fetch(getPauseFineTuningJobUrl(fineTuningJobId), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: pauseFineTuningJobResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as pauseFineTuningJobResponse;
};

/**
 * @summary Resume a fine-tune job.

 */
export type resumeFineTuningJobResponse200 = {
  data: FineTuningJob;
  status: 200;
};

export type resumeFineTuningJobResponseComposite =
  resumeFineTuningJobResponse200;

export type resumeFineTuningJobResponse =
  resumeFineTuningJobResponseComposite & {
    headers: Headers;
  };

export const getResumeFineTuningJobUrl = (fineTuningJobId: string) => {
  return `/fine_tuning/jobs/${fineTuningJobId}/resume`;
};

export const resumeFineTuningJob = async (
  fineTuningJobId: string,
  options?: RequestInit
): Promise<resumeFineTuningJobResponse> => {
  const res = await fetch(getResumeFineTuningJobUrl(fineTuningJobId), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: resumeFineTuningJobResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as resumeFineTuningJobResponse;
};
