/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { FileSearchRankingOptions } from './fileSearchRankingOptions';

/**
 * Overrides for the file search tool.
 */
export type AssistantToolsFileSearchFileSearch = {
  /**
   * The maximum number of results the file search tool should output. The default is 20 for `gpt-4*` models and 5 for `gpt-3.5-turbo`. This number should be between 1 and 50 inclusive.

Note that the file search tool may output fewer than `max_num_results` results. See the [file search tool documentation](/docs/assistants/tools/file-search#customizing-file-search-settings) for more information.

   * @minimum 1
   * @maximum 50
   */
  max_num_results?: number;
  ranking_options?: FileSearchRankingOptions;
};
