/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`. For `gpt-4o-transcribe` and `gpt-4o-mini-transcribe`, the only supported format is `json`.

 */
export type AudioResponseFormat =
  (typeof AudioResponseFormat)[keyof typeof AudioResponseFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AudioResponseFormat = {
  json: 'json',
  text: 'text',
  srt: 'srt',
  verbose_json: 'verbose_json',
  vtt: 'vtt',
} as const;
