/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of API key. Can be either `user` or `service_account`.
 */
export type AuditLogActorApiKeyType =
  (typeof AuditLogActorApiKeyType)[keyof typeof AuditLogActorApiKeyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditLogActorApiKeyType = {
  user: 'user',
  service_account: 'service_account',
} as const;
