/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ChatCompletionMessageToolCall } from './chatCompletionMessageToolCall';

/**
 * The tool calls generated by the model, such as function calls.
 */
export type ChatCompletionMessageToolCalls = ChatCompletionMessageToolCall[];
