/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * If the audio output modality is requested, this object contains data
about the audio response from the model. [Learn more](/docs/guides/audio).

 * @nullable
 */
export type ChatCompletionResponseMessageAudio = {
  /** Unique identifier for this audio response. */
  id: string;
  /** The Unix timestamp (in seconds) for when this audio response will
no longer be accessible on the server for use in multi-turn
conversations.
 */
  expires_at: number;
  /** Base64 encoded audio bytes generated by the model, in the format
specified in the request.
 */
  data: string;
  /** Transcript of the audio generated by the model. */
  transcript: string;
} | null;
