/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Data about a previous audio response from the model. 
[Learn more](/docs/guides/audio).

 * @nullable
 */
export type ChatCompletionRequestAssistantMessageAudio = {
  /** Unique identifier for a previous audio response from the model.
   */
  id: string;
} | null;
