/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The role of the messages author, in this case `assistant`.
 */
export type ChatCompletionRequestAssistantMessageRole =
  (typeof ChatCompletionRequestAssistantMessageRole)[keyof typeof ChatCompletionRequestAssistantMessageRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatCompletionRequestAssistantMessageRole = {
  assistant: 'assistant',
} as const;
