/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the tool. Currently, only `function` is supported.
 */
export type ChatCompletionNamedToolChoiceType =
  (typeof ChatCompletionNamedToolChoiceType)[keyof typeof ChatCompletionNamedToolChoiceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatCompletionNamedToolChoiceType = {
  function: 'function',
} as const;
