/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the content part.
 */
export type ChatCompletionRequestMessageContentPartTextType =
  (typeof ChatCompletionRequestMessageContentPartTextType)[keyof typeof ChatCompletionRequestMessageContentPartTextType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatCompletionRequestMessageContentPartTextType = {
  text: 'text',
} as const;
