/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Indicates which mouse button was pressed during the click. One of `left`, `right`, `wheel`, `back`, or `forward`.

 */
export type ClickButton = (typeof ClickButton)[keyof typeof ClickButton];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClickButton = {
  left: 'left',
  right: 'right',
  wheel: 'wheel',
  back: 'back',
  forward: 'forward',
} as const;
