/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type CodeInterpreterFileOutputFilesItem = {
  /** The MIME type of the file.
   */
  mime_type: string;
  /** The ID of the file.
   */
  file_id: string;
};
