/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The status of the code interpreter tool call. Valid values are `in_progress`, `completed`, `incomplete`, `interpreting`, and `failed`.

 */
export type CodeInterpreterToolCallStatus =
  (typeof CodeInterpreterToolCallStatus)[keyof typeof CodeInterpreterToolCallStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CodeInterpreterToolCallStatus = {
  in_progress: 'in_progress',
  completed: 'completed',
  incomplete: 'incomplete',
  interpreting: 'interpreting',
  failed: 'failed',
} as const;
