/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the computer tool call output. Always `computer_call_output`.

 */
export type ComputerToolCallOutputType =
  (typeof ComputerToolCallOutputType)[keyof typeof ComputerToolCallOutputType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComputerToolCallOutputType = {
  computer_call_output: 'computer_call_output',
} as const;
