/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { CreateEvalCustomDataSourceConfig } from './createEvalCustomDataSourceConfig';
import type { CreateEvalLogsDataSourceConfig } from './createEvalLogsDataSourceConfig';
import type { CreateEvalStoredCompletionsDataSourceConfig } from './createEvalStoredCompletionsDataSourceConfig';

/**
 * The configuration for the data source used for the evaluation runs. Dictates the schema of the data used in the evaluation.
 */
export type CreateEvalRequestDataSourceConfig =
  | CreateEvalCustomDataSourceConfig
  | CreateEvalLogsDataSourceConfig
  | CreateEvalStoredCompletionsDataSourceConfig;
