/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceItem =
  (typeof CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceItem)[keyof typeof CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateModerationResponseResultsItemCategoryAppliedInputTypesViolenceItem =
  {
    text: 'text',
    image: 'image',
  } as const;
