/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`,
`opus`, or `pcm16`.

 */
export type CreateChatCompletionRequestAllOfAudioFormat =
  (typeof CreateChatCompletionRequestAllOfAudioFormat)[keyof typeof CreateChatCompletionRequestAllOfAudioFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateChatCompletionRequestAllOfAudioFormat = {
  wav: 'wav',
  aac: 'aac',
  mp3: 'mp3',
  flac: 'flac',
  opus: 'opus',
  pcm16: 'pcm16',
} as const;
