/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { CreateEvalCustomDataSourceConfigType } from './createEvalCustomDataSourceConfigType';
import type { CreateEvalCustomDataSourceConfigItemSchema } from './createEvalCustomDataSourceConfigItemSchema';

/**
 * A CustomDataSourceConfig object that defines the schema for the data source used for the evaluation runs.
This schema is used to define the shape of the data that will be:
- Used to define your testing criteria and
- What data is required when creating a run

 */
export interface CreateEvalCustomDataSourceConfig {
  /** The type of data source. Always `custom`. */
  type: CreateEvalCustomDataSourceConfigType;
  /** The json schema for each row in the data source. */
  item_schema: CreateEvalCustomDataSourceConfigItemSchema;
  /** Whether the eval should expect you to populate the sample namespace (ie, by generating responses off of your data source) */
  include_sample_schema?: boolean;
}
