/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { CreateEvalCompletionsRunDataSourceInputMessagesOneOf } from './createEvalCompletionsRunDataSourceInputMessagesOneOf';
import type { CreateEvalCompletionsRunDataSourceInputMessagesOneOfFour } from './createEvalCompletionsRunDataSourceInputMessagesOneOfFour';

/**
 * Used when sampling from a model. Dictates the structure of the messages passed into the model. Can either be a reference to a prebuilt trajectory (ie, `item.input_trajectory`), or a template with variable references to the `item` namespace.
 */
export type CreateEvalCompletionsRunDataSourceInputMessages =
  | CreateEvalCompletionsRunDataSourceInputMessagesOneOf
  | CreateEvalCompletionsRunDataSourceInputMessagesOneOfFour;
