/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { CreateUploadRequestPurpose } from './createUploadRequestPurpose';

export interface CreateUploadRequest {
  /** The name of the file to upload.
   */
  filename: string;
  /** The intended purpose of the uploaded file.

See the [documentation on File purposes](/docs/api-reference/files/create#files-create-purpose).
 */
  purpose: CreateUploadRequestPurpose;
  /** The number of bytes in the file you are uploading.
   */
  bytes: number;
  /** The MIME type of the file.

This must fall within the supported MIME types for your file purpose. See the supported MIME types for assistants and vision.
 */
  mime_type: string;
}
