/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type CreateRunIncludeItem =
  (typeof CreateRunIncludeItem)[keyof typeof CreateRunIncludeItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRunIncludeItem = {
  'step_detailstool_calls[*]file_searchresults[*]content':
    'step_details.tool_calls[*].file_search.results[*].content',
} as const;
