/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { VoiceIdsShared } from './voiceIdsShared';
import type { CreateChatCompletionRequestAllOfAudioFormat } from './createChatCompletionRequestAllOfAudioFormat';

/**
 * Parameters for audio output. Required when audio output is requested with
`modalities: ["audio"]`. [Learn more](/docs/guides/audio).

 * @nullable
 */
export type CreateChatCompletionRequestAllOfAudio = {
  /** The voice the model uses to respond. Supported voices are 
`alloy`, `ash`, `ballad`, `coral`, `echo`, `fable`, `nova`, `onyx`, `sage`, and `shimmer`.
 */
  voice: VoiceIdsShared;
  /** Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`,
`opus`, or `pcm16`.
 */
  format: CreateChatCompletionRequestAllOfAudioFormat;
} | null;
