/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ChatCompletionStreamResponseDelta } from './chatCompletionStreamResponseDelta';
import type { CreateChatCompletionStreamResponseChoicesItemLogprobs } from './createChatCompletionStreamResponseChoicesItemLogprobs';
import type { CreateChatCompletionStreamResponseChoicesItemFinishReason } from './createChatCompletionStreamResponseChoicesItemFinishReason';

export type CreateChatCompletionStreamResponseChoicesItem = {
  delta: ChatCompletionStreamResponseDelta;
  /**
   * Log probability information for the choice.
   * @nullable
   */
  logprobs?: CreateChatCompletionStreamResponseChoicesItemLogprobs;
  /**
   * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
`length` if the maximum number of tokens specified in the request was reached,
`content_filter` if content was omitted due to a flag from our content filters,
`tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.

   * @nullable
   */
  finish_reason: CreateChatCompletionStreamResponseChoicesItemFinishReason;
  /** The index of the choice in the list of choices. */
  index: number;
};
