/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { CreateThreadRequestToolResourcesFileSearchVectorStoresItemChunkingStrategyOneOf } from './createThreadRequestToolResourcesFileSearchVectorStoresItemChunkingStrategyOneOf';
import type { CreateThreadRequestToolResourcesFileSearchVectorStoresItemChunkingStrategyOneOfThree } from './createThreadRequestToolResourcesFileSearchVectorStoresItemChunkingStrategyOneOfThree';

/**
 * The chunking strategy used to chunk the file(s). If not set, will use the `auto` strategy.
 */
export type CreateThreadRequestToolResourcesFileSearchVectorStoresItemChunkingStrategy =

    | CreateThreadRequestToolResourcesFileSearchVectorStoresItemChunkingStrategyOneOf
    | CreateThreadRequestToolResourcesFileSearchVectorStoresItemChunkingStrategyOneOfThree;
