/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The format in which the generated images are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter is only supported for `dall-e-2`, as `gpt-image-1` will always return base64-encoded images.
 * @nullable
 */
export type CreateImageEditRequestResponseFormat =
  | (typeof CreateImageEditRequestResponseFormat)[keyof typeof CreateImageEditRequestResponseFormat]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateImageEditRequestResponseFormat = {
  url: 'url',
  b64_json: 'b64_json',
} as const;
