/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The time frame within which the batch should be processed. Currently only `24h` is supported.
 */
export type CreateBatchBodyCompletionWindow =
  (typeof CreateBatchBodyCompletionWindow)[keyof typeof CreateBatchBodyCompletionWindow];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBatchBodyCompletionWindow = {
  '24h': '24h',
} as const;
