/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { CreateModerationRequestInputOneOfItemOneOf } from './createModerationRequestInputOneOfItemOneOf';
import type { CreateModerationRequestInputOneOfItemOneOfFour } from './createModerationRequestInputOneOfItemOneOfFour';

export type CreateModerationRequestInputOneOfItem =
  | CreateModerationRequestInputOneOfItemOneOf
  | CreateModerationRequestInputOneOfItemOneOfFour;
