/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The format to stream the audio in. Supported formats are `sse` and `audio`. `sse` is not supported for `tts-1` or `tts-1-hd`.
 */
export type CreateSpeechRequestStreamFormat =
  (typeof CreateSpeechRequestStreamFormat)[keyof typeof CreateSpeechRequestStreamFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSpeechRequestStreamFormat = {
  sse: 'sse',
  audio: 'audio',
} as const;
