/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Specifies the event type. For a double click action, this property is 
always set to `double_click`.

 */
export type DoubleClickType =
  (typeof DoubleClickType)[keyof typeof DoubleClickType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DoubleClickType = {
  double_click: 'double_click',
} as const;
