/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the message input. Always `message`.

 */
export type EvalItemType = (typeof EvalItemType)[keyof typeof EvalItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvalItemType = {
  message: 'message',
} as const;
