/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the object. Always "eval.run".
 */
export type EvalRunObject = (typeof EvalRunObject)[keyof typeof EvalRunObject];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvalRunObject = {
  evalrun: 'eval.run',
} as const;
