/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { EvalResponsesSourceType } from './evalResponsesSourceType';
import type { EvalResponsesSourceMetadata } from './evalResponsesSourceMetadata';
import type { ReasoningEffort } from './reasoningEffort';

/**
 * A EvalResponsesSource object describing a run data source configuration.

 */
export interface EvalResponsesSource {
  /** The type of run data source. Always `responses`. */
  type: EvalResponsesSourceType;
  /**
   * Metadata filter for the responses. This is a query parameter used to select responses.
   * @nullable
   */
  metadata?: EvalResponsesSourceMetadata;
  /**
   * The name of the model to find responses for. This is a query parameter used to select responses.
   * @nullable
   */
  model?: string | null;
  /**
   * Optional string to search the 'instructions' field. This is a query parameter used to select responses.
   * @nullable
   */
  instructions_search?: string | null;
  /**
   * Only include items created after this timestamp (inclusive). This is a query parameter used to select responses.
   * @minimum 0
   * @nullable
   */
  created_after?: number | null;
  /**
   * Only include items created before this timestamp (inclusive). This is a query parameter used to select responses.
   * @minimum 0
   * @nullable
   */
  created_before?: number | null;
  /**
   * Optional reasoning effort parameter. This is a query parameter used to select responses.
   * @nullable
   */
  reasoning_effort?: ReasoningEffort;
  /**
   * Sampling temperature. This is a query parameter used to select responses.
   * @nullable
   */
  temperature?: number | null;
  /**
   * Nucleus sampling parameter. This is a query parameter used to select responses.
   * @nullable
   */
  top_p?: number | null;
  /**
   * List of user identifiers. This is a query parameter used to select responses.
   * @nullable
   */
  users?: string[] | null;
  /**
   * List of tool names. This is a query parameter used to select responses.
   * @nullable
   */
  tools?: string[] | null;
}
