/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { EvalStoredCompletionsSourceType } from './evalStoredCompletionsSourceType';
import type { Metadata } from './metadata';

/**
 * A StoredCompletionsRunDataSource configuration describing a set of filters

 */
export interface EvalStoredCompletionsSource {
  /** The type of source. Always `stored_completions`. */
  type: EvalStoredCompletionsSourceType;
  metadata?: Metadata;
  /**
   * An optional model to filter by (e.g., 'gpt-4o').
   * @nullable
   */
  model?: string | null;
  /**
   * An optional Unix timestamp to filter items created after this time.
   * @nullable
   */
  created_after?: number | null;
  /**
   * An optional Unix timestamp to filter items created before this time.
   * @nullable
   */
  created_before?: number | null;
  /**
   * An optional maximum number of items to return.
   * @nullable
   */
  limit?: number | null;
}
