/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { FileSearchToolCallType } from './fileSearchToolCallType';
import type { FileSearchToolCallStatus } from './fileSearchToolCallStatus';
import type { FileSearchToolCallResultsItem } from './fileSearchToolCallResultsItem';

/**
 * The results of a file search tool call. See the 
[file search guide](/docs/guides/tools-file-search) for more information.

 */
export interface FileSearchToolCall {
  /** The unique ID of the file search tool call.
   */
  id: string;
  /** The type of the file search tool call. Always `file_search_call`.
   */
  type: FileSearchToolCallType;
  /** The status of the file search tool call. One of `in_progress`, 
`searching`, `incomplete` or `failed`,
 */
  status: FileSearchToolCallStatus;
  /** The queries used to search for files.
   */
  queries: string[];
  /**
   * The results of the file search tool call.

   * @nullable
   */
  results?: FileSearchToolCallResultsItem[] | null;
}
