/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the file citation. Always `file_citation`.
 */
export type FileCitationBodyType =
  (typeof FileCitationBodyType)[keyof typeof FileCitationBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileCitationBodyType = {
  file_citation: 'file_citation',
} as const;
