/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { VectorStoreFileAttributes } from './vectorStoreFileAttributes';

export type FileSearchToolCallResultsItem = {
  /** The unique ID of the file.
   */
  file_id?: string;
  /** The text that was retrieved from the file.
   */
  text?: string;
  /** The name of the file.
   */
  filename?: string;
  attributes?: VectorStoreFileAttributes;
  /** The relevance score of the file - a value between 0 and 1.
   */
  score?: number;
};
