/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The status of the file search tool call. One of `in_progress`, 
`searching`, `incomplete` or `failed`,

 */
export type FileSearchToolCallStatus =
  (typeof FileSearchToolCallStatus)[keyof typeof FileSearchToolCallStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileSearchToolCallStatus = {
  in_progress: 'in_progress',
  searching: 'searching',
  completed: 'completed',
  incomplete: 'incomplete',
  failed: 'failed',
} as const;
