/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { FineTuneReinforcementHyperparametersBatchSize } from './fineTuneReinforcementHyperparametersBatchSize';
import type { FineTuneReinforcementHyperparametersLearningRateMultiplier } from './fineTuneReinforcementHyperparametersLearningRateMultiplier';
import type { FineTuneReinforcementHyperparametersNEpochs } from './fineTuneReinforcementHyperparametersNEpochs';
import type { FineTuneReinforcementHyperparametersReasoningEffort } from './fineTuneReinforcementHyperparametersReasoningEffort';
import type { FineTuneReinforcementHyperparametersComputeMultiplier } from './fineTuneReinforcementHyperparametersComputeMultiplier';
import type { FineTuneReinforcementHyperparametersEvalInterval } from './fineTuneReinforcementHyperparametersEvalInterval';
import type { FineTuneReinforcementHyperparametersEvalSamples } from './fineTuneReinforcementHyperparametersEvalSamples';

/**
 * The hyperparameters used for the reinforcement fine-tuning job.
 */
export interface FineTuneReinforcementHyperparameters {
  /** Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance.
   */
  batch_size?: FineTuneReinforcementHyperparametersBatchSize;
  /** Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting.
   */
  learning_rate_multiplier?: FineTuneReinforcementHyperparametersLearningRateMultiplier;
  /** The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset.
   */
  n_epochs?: FineTuneReinforcementHyperparametersNEpochs;
  /** Level of reasoning effort.
   */
  reasoning_effort?: FineTuneReinforcementHyperparametersReasoningEffort;
  /** Multiplier on amount of compute used for exploring search space during training.
   */
  compute_multiplier?: FineTuneReinforcementHyperparametersComputeMultiplier;
  /** The number of training steps between evaluation runs.
   */
  eval_interval?: FineTuneReinforcementHyperparametersEvalInterval;
  /** Number of evaluation samples to generate per training step.
   */
  eval_samples?: FineTuneReinforcementHyperparametersEvalSamples;
}
