/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The object type, which is always "fine_tuning.job".
 */
export type FineTuningJobObject =
  (typeof FineTuningJobObject)[keyof typeof FineTuningJobObject];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FineTuningJobObject = {
  fine_tuningjob: 'fine_tuning.job',
} as const;
