/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ChatCompletionRequestDeveloperMessage } from './chatCompletionRequestDeveloperMessage';
import type { ChatCompletionRequestUserMessage } from './chatCompletionRequestUserMessage';
import type { FineTuneChatCompletionRequestAssistantMessage } from './fineTuneChatCompletionRequestAssistantMessage';
import type { ChatCompletionRequestToolMessage } from './chatCompletionRequestToolMessage';

export type FineTuneReinforcementRequestInputMessagesItem =
  | ChatCompletionRequestDeveloperMessage
  | ChatCompletionRequestUserMessage
  | FineTuneChatCompletionRequestAssistantMessage
  | ChatCompletionRequestToolMessage;
