/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Number of examples in each batch. A larger batch size means that model parameters
are updated less frequently, but with lower variance.

 * @nullable
 */
export type FineTuningJobHyperparametersBatchSize = 'auto' | number | null;
