/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { FineTuningJobHyperparametersBatchSize } from './fineTuningJobHyperparametersBatchSize';
import type { FineTuningJobHyperparametersLearningRateMultiplier } from './fineTuningJobHyperparametersLearningRateMultiplier';
import type { FineTuningJobHyperparametersNEpochs } from './fineTuningJobHyperparametersNEpochs';

/**
 * The hyperparameters used for the fine-tuning job. This value will only be returned when running `supervised` jobs.
 */
export type FineTuningJobHyperparameters = {
  /**
   * Number of examples in each batch. A larger batch size means that model parameters
are updated less frequently, but with lower variance.

   * @nullable
   */
  batch_size?: FineTuningJobHyperparametersBatchSize;
  /** Scaling factor for the learning rate. A smaller learning rate may be useful to avoid
overfitting.
 */
  learning_rate_multiplier?: FineTuningJobHyperparametersLearningRateMultiplier;
  /** The number of epochs to train the model for. An epoch refers to one full cycle
through the training dataset.
 */
  n_epochs?: FineTuningJobHyperparametersNEpochs;
};
