/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { FunctionCallOutputItemParamId } from './functionCallOutputItemParamId';
import type { FunctionCallOutputItemParamType } from './functionCallOutputItemParamType';
import type { FunctionCallOutputItemParamStatus } from './functionCallOutputItemParamStatus';

/**
 * The output of a function tool call.
 */
export interface FunctionCallOutputItemParam {
  id?: FunctionCallOutputItemParamId;
  /**
   * The unique ID of the function tool call generated by the model.
   * @minLength 1
   * @maxLength 64
   */
  call_id: string;
  /** The type of the function tool call output. Always `function_call_output`. */
  type: FunctionCallOutputItemParamType;
  /**
   * A JSON string of the output of the function tool call.
   * @maxLength 10485760
   */
  output: string;
  status?: FunctionCallOutputItemParamStatus;
}
