/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { GenerateKeyResponseKeyAlias } from './generateKeyResponseKeyAlias';
import type { GenerateKeyResponseDuration } from './generateKeyResponseDuration';
import type { GenerateKeyResponseModels } from './generateKeyResponseModels';
import type { GenerateKeyResponseSpend } from './generateKeyResponseSpend';
import type { GenerateKeyResponseMaxBudget } from './generateKeyResponseMaxBudget';
import type { GenerateKeyResponseUserId } from './generateKeyResponseUserId';
import type { GenerateKeyResponseTeamId } from './generateKeyResponseTeamId';
import type { GenerateKeyResponseMaxParallelRequests } from './generateKeyResponseMaxParallelRequests';
import type { GenerateKeyResponseMetadata } from './generateKeyResponseMetadata';
import type { GenerateKeyResponseTpmLimit } from './generateKeyResponseTpmLimit';
import type { GenerateKeyResponseRpmLimit } from './generateKeyResponseRpmLimit';
import type { GenerateKeyResponseBudgetDuration } from './generateKeyResponseBudgetDuration';
import type { GenerateKeyResponseAllowedCacheControls } from './generateKeyResponseAllowedCacheControls';
import type { GenerateKeyResponseConfig } from './generateKeyResponseConfig';
import type { GenerateKeyResponsePermissions } from './generateKeyResponsePermissions';
import type { GenerateKeyResponseModelMaxBudget } from './generateKeyResponseModelMaxBudget';
import type { GenerateKeyResponseModelRpmLimit } from './generateKeyResponseModelRpmLimit';
import type { GenerateKeyResponseModelTpmLimit } from './generateKeyResponseModelTpmLimit';
import type { GenerateKeyResponseGuardrails } from './generateKeyResponseGuardrails';
import type { GenerateKeyResponseBlocked } from './generateKeyResponseBlocked';
import type { GenerateKeyResponseAliases } from './generateKeyResponseAliases';
import type { GenerateKeyResponseObjectPermission } from './generateKeyResponseObjectPermission';
import type { GenerateKeyResponseBudgetId } from './generateKeyResponseBudgetId';
import type { GenerateKeyResponseTags } from './generateKeyResponseTags';
import type { GenerateKeyResponseEnforcedParams } from './generateKeyResponseEnforcedParams';
import type { GenerateKeyResponseAllowedRoutes } from './generateKeyResponseAllowedRoutes';
import type { GenerateKeyResponseKeyName } from './generateKeyResponseKeyName';
import type { GenerateKeyResponseExpires } from './generateKeyResponseExpires';
import type { GenerateKeyResponseTokenId } from './generateKeyResponseTokenId';
import type { GenerateKeyResponseLitellmBudgetTable } from './generateKeyResponseLitellmBudgetTable';
import type { GenerateKeyResponseToken } from './generateKeyResponseToken';
import type { GenerateKeyResponseCreatedBy } from './generateKeyResponseCreatedBy';
import type { GenerateKeyResponseUpdatedBy } from './generateKeyResponseUpdatedBy';
import type { GenerateKeyResponseCreatedAt } from './generateKeyResponseCreatedAt';
import type { GenerateKeyResponseUpdatedAt } from './generateKeyResponseUpdatedAt';

export interface GenerateKeyResponse {
  key_alias?: GenerateKeyResponseKeyAlias;
  duration?: GenerateKeyResponseDuration;
  models?: GenerateKeyResponseModels;
  spend?: GenerateKeyResponseSpend;
  max_budget?: GenerateKeyResponseMaxBudget;
  user_id?: GenerateKeyResponseUserId;
  team_id?: GenerateKeyResponseTeamId;
  max_parallel_requests?: GenerateKeyResponseMaxParallelRequests;
  metadata?: GenerateKeyResponseMetadata;
  tpm_limit?: GenerateKeyResponseTpmLimit;
  rpm_limit?: GenerateKeyResponseRpmLimit;
  budget_duration?: GenerateKeyResponseBudgetDuration;
  allowed_cache_controls?: GenerateKeyResponseAllowedCacheControls;
  config?: GenerateKeyResponseConfig;
  permissions?: GenerateKeyResponsePermissions;
  model_max_budget?: GenerateKeyResponseModelMaxBudget;
  model_rpm_limit?: GenerateKeyResponseModelRpmLimit;
  model_tpm_limit?: GenerateKeyResponseModelTpmLimit;
  guardrails?: GenerateKeyResponseGuardrails;
  blocked?: GenerateKeyResponseBlocked;
  aliases?: GenerateKeyResponseAliases;
  object_permission?: GenerateKeyResponseObjectPermission;
  key: string;
  budget_id?: GenerateKeyResponseBudgetId;
  tags?: GenerateKeyResponseTags;
  enforced_params?: GenerateKeyResponseEnforcedParams;
  allowed_routes?: GenerateKeyResponseAllowedRoutes;
  key_name?: GenerateKeyResponseKeyName;
  expires?: GenerateKeyResponseExpires;
  token_id?: GenerateKeyResponseTokenId;
  litellm_budget_table?: GenerateKeyResponseLitellmBudgetTable;
  token?: GenerateKeyResponseToken;
  created_by?: GenerateKeyResponseCreatedBy;
  updated_by?: GenerateKeyResponseUpdatedBy;
  created_at?: GenerateKeyResponseCreatedAt;
  updated_at?: GenerateKeyResponseUpdatedAt;
}
