/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { GraderPythonType } from './graderPythonType';

/**
 * A PythonGrader object that runs a python script on the input.

 */
export interface GraderPython {
  /** The object type, which is always `python`. */
  type: GraderPythonType;
  /** The name of the grader. */
  name: string;
  /** The source code of the python script. */
  source: string;
  /** The image tag to use for the python script. */
  image_tag?: string;
}
