/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The evaluation metric to use. One of `fuzzy_match`, `bleu`, `gleu`, `meteor`, `rouge_1`, `rouge_2`, `rouge_3`, `rouge_4`, `rouge_5`, or `rouge_l`.
 */
export type GraderTextSimilarityEvaluationMetric =
  (typeof GraderTextSimilarityEvaluationMetric)[keyof typeof GraderTextSimilarityEvaluationMetric];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GraderTextSimilarityEvaluationMetric = {
  fuzzy_match: 'fuzzy_match',
  bleu: 'bleu',
  gleu: 'gleu',
  meteor: 'meteor',
  rouge_1: 'rouge_1',
  rouge_2: 'rouge_2',
  rouge_3: 'rouge_3',
  rouge_4: 'rouge_4',
  rouge_5: 'rouge_5',
  rouge_l: 'rouge_l',
} as const;
