/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { GraderStringCheckType } from './graderStringCheckType';
import type { GraderStringCheckOperation } from './graderStringCheckOperation';

/**
 * A StringCheckGrader object that performs a string comparison between input and reference using a specified operation.

 */
export interface GraderStringCheck {
  /** The object type, which is always `string_check`. */
  type: GraderStringCheckType;
  /** The name of the grader. */
  name: string;
  /** The input text. This may include template strings. */
  input: string;
  /** The reference text. This may include template strings. */
  reference: string;
  /** The string check operation to perform. One of `eq`, `ne`, `like`, or `ilike`. */
  operation: GraderStringCheckOperation;
}
