/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { GraderLabelModelType } from './graderLabelModelType';
import type { EvalItem } from './evalItem';

/**
 * A LabelModelGrader object which uses a model to assign labels to each item
in the evaluation.

 */
export interface GraderLabelModel {
  /** The object type, which is always `label_model`. */
  type: GraderLabelModelType;
  /** The name of the grader. */
  name: string;
  /** The model to use for the evaluation. Must support structured outputs. */
  model: string;
  input: EvalItem[];
  /** The labels to assign to each item in the evaluation. */
  labels: string[];
  /** The labels that indicate a passing result. Must be a subset of labels. */
  passing_labels: string[];
}
