/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { GraderTextSimilarityType } from './graderTextSimilarityType';
import type { GraderTextSimilarityEvaluationMetric } from './graderTextSimilarityEvaluationMetric';

/**
 * A TextSimilarityGrader object which grades text based on similarity metrics.

 */
export interface GraderTextSimilarity {
  /** The type of grader. */
  type: GraderTextSimilarityType;
  /** The name of the grader. */
  name: string;
  /** The text being graded. */
  input: string;
  /** The text being graded against. */
  reference: string;
  /** The evaluation metric to use. One of `fuzzy_match`, `bleu`, `gleu`, `meteor`, `rouge_1`, `rouge_2`, `rouge_3`, `rouge_4`, `rouge_5`, or `rouge_l`. */
  evaluation_metric: GraderTextSimilarityEvaluationMetric;
}
