/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The background setting for the requested edited image.

 */
export type ImageEditPartialImageEventBackground =
  (typeof ImageEditPartialImageEventBackground)[keyof typeof ImageEditPartialImageEventBackground];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageEditPartialImageEventBackground = {
  transparent: 'transparent',
  opaque: 'opaque',
  auto: 'auto',
} as const;
