/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The background parameter used for the image generation. Either `transparent` or `opaque`.
 */
export type ImagesResponseBackground =
  (typeof ImagesResponseBackground)[keyof typeof ImagesResponseBackground];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImagesResponseBackground = {
  transparent: 'transparent',
  opaque: 'opaque',
} as const;
