/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The size of the generated image. One of `1024x1024`, `1024x1536`, 
`1536x1024`, or `auto`. Default: `auto`.

 */
export type ImageGenToolSize =
  (typeof ImageGenToolSize)[keyof typeof ImageGenToolSize];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageGenToolSize = {
  '1024x1024': '1024x1024',
  '1024x1536': '1024x1536',
  '1536x1024': '1536x1024',
  auto: 'auto',
} as const;
