/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Specify additional output data to include in the model response. Currently
supported values are:
- `code_interpreter_call.outputs`: Includes the outputs of python code execution
  in code interpreter tool call items.
- `computer_call_output.output.image_url`: Include image urls from the computer call output.
- `file_search_call.results`: Include the search results of
  the file search tool call.
- `message.input_image.image_url`: Include image urls from the input message.
- `message.output_text.logprobs`: Include logprobs with assistant messages.
- `reasoning.encrypted_content`: Includes an encrypted version of reasoning
  tokens in reasoning item outputs. This enables reasoning items to be used in
  multi-turn conversations when using the Responses API statelessly (like
  when the `store` parameter is set to `false`, or when an organization is
  enrolled in the zero data retention program).

 */
export type Includable = (typeof Includable)[keyof typeof Includable];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Includable = {
  code_interpreter_calloutputs: 'code_interpreter_call.outputs',
  computer_call_outputoutputimage_url: 'computer_call_output.output.image_url',
  file_search_callresults: 'file_search_call.results',
  messageinput_imageimage_url: 'message.input_image.image_url',
  messageoutput_textlogprobs: 'message.output_text.logprobs',
  reasoningencrypted_content: 'reasoning.encrypted_content',
} as const;
