/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { InviteRequestRole } from './inviteRequestRole';
import type { InviteRequestProjectsItem } from './inviteRequestProjectsItem';

export interface InviteRequest {
  /** Send an email to this address */
  email: string;
  /** `owner` or `reader` */
  role: InviteRequestRole;
  /** An array of projects to which membership is granted at the same time the org invite is accepted. If omitted, the user will be invited to the default project for compatibility with legacy behavior. */
  projects?: InviteRequestProjectsItem[];
}
