/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ItemReferenceParamType } from './itemReferenceParamType';

/**
 * An internal identifier for an item to reference.
 */
export interface ItemReferenceParam {
  type?: ItemReferenceParamType;
  /** The ID of the item to reference. */
  id: string;
}
