/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Specifies the event type. For a keypress action, this property is 
always set to `keypress`.

 */
export type KeyPressType = (typeof KeyPressType)[keyof typeof KeyPressType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KeyPressType = {
  keypress: 'keypress',
} as const;
