/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ListEvalsOrder } from './listEvalsOrder';
import type { ListEvalsOrderBy } from './listEvalsOrderBy';

export type ListEvalsParams = {
  /**
   * Identifier for the last eval from the previous pagination request.
   */
  after?: string;
  /**
   * Number of evals to retrieve.
   */
  limit?: number;
  /**
   * Sort order for evals by timestamp. Use `asc` for ascending order or `desc` for descending order.
   */
  order?: ListEvalsOrder;
  /**
 * Evals can be ordered by creation time or last updated time. Use
`created_at` for creation time or `updated_at` for last updated time.

 */
  order_by?: ListEvalsOrderBy;
};
