/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */

export type ListFineTuningJobsV1FineTuningJobsGetParams = {
  custom_llm_provider?: 'openai' | 'azure' | null;
  /**
   * Comma separated list of model names to filter by. Example: 'gpt-4o,gpt-4o-mini'
   */
  target_model_names?: string | null;
  after?: string | null;
  limit?: number | null;
};
