/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type ListEvalsOrder =
  (typeof ListEvalsOrder)[keyof typeof ListEvalsOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListEvalsOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
