/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type ListCertificatesResponseObject =
  (typeof ListCertificatesResponseObject)[keyof typeof ListCertificatesResponseObject];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListCertificatesResponseObject = {
  list: 'list',
} as const;
