/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { LitellmParamsApiKey } from './litellmParamsApiKey';
import type { LitellmParamsApiBase } from './litellmParamsApiBase';
import type { LitellmParamsCategoryThresholds } from './litellmParamsCategoryThresholds';
import type { LitellmParamsDetectSecretsConfig } from './litellmParamsDetectSecretsConfig';
import type { LitellmParamsGuardName } from './litellmParamsGuardName';
import type { LitellmParamsDefaultOn } from './litellmParamsDefaultOn';
import type { LitellmParamsMaskRequestContent } from './litellmParamsMaskRequestContent';
import type { LitellmParamsMaskResponseContent } from './litellmParamsMaskResponseContent';
import type { LitellmParamsPangeaInputRecipe } from './litellmParamsPangeaInputRecipe';
import type { LitellmParamsPangeaOutputRecipe } from './litellmParamsPangeaOutputRecipe';
import type { LitellmParamsModel } from './litellmParamsModel';
import type { LitellmParamsTemplateId } from './litellmParamsTemplateId';
import type { LitellmParamsLocation } from './litellmParamsLocation';
import type { LitellmParamsCredentials } from './litellmParamsCredentials';
import type { LitellmParamsApiEndpoint } from './litellmParamsApiEndpoint';
import type { LitellmParamsFailOnError } from './litellmParamsFailOnError';
import type { LitellmParamsOnFlaggedAction } from './litellmParamsOnFlaggedAction';
import type { LitellmParamsLassoUserId } from './litellmParamsLassoUserId';
import type { LitellmParamsLassoConversationId } from './litellmParamsLassoConversationId';
import type { LitellmParamsProjectId } from './litellmParamsProjectId';
import type { LitellmParamsPayload } from './litellmParamsPayload';
import type { LitellmParamsBreakdown } from './litellmParamsBreakdown';
import type { LitellmParamsMetadata } from './litellmParamsMetadata';
import type { LitellmParamsDevInfo } from './litellmParamsDevInfo';
import type { LitellmParamsGuardrailIdentifier } from './litellmParamsGuardrailIdentifier';
import type { LitellmParamsGuardrailVersion } from './litellmParamsGuardrailVersion';
import type { LitellmParamsDisableExceptionOnBlock } from './litellmParamsDisableExceptionOnBlock';
import type { LitellmParamsAwsRegionName } from './litellmParamsAwsRegionName';
import type { LitellmParamsAwsAccessKeyId } from './litellmParamsAwsAccessKeyId';
import type { LitellmParamsAwsSecretAccessKey } from './litellmParamsAwsSecretAccessKey';
import type { LitellmParamsAwsSessionToken } from './litellmParamsAwsSessionToken';
import type { LitellmParamsAwsSessionName } from './litellmParamsAwsSessionName';
import type { LitellmParamsAwsProfileName } from './litellmParamsAwsProfileName';
import type { LitellmParamsAwsRoleName } from './litellmParamsAwsRoleName';
import type { LitellmParamsAwsWebIdentityToken } from './litellmParamsAwsWebIdentityToken';
import type { LitellmParamsAwsStsEndpoint } from './litellmParamsAwsStsEndpoint';
import type { LitellmParamsAwsBedrockRuntimeEndpoint } from './litellmParamsAwsBedrockRuntimeEndpoint';
import type { LitellmParamsPresidioAnalyzerApiBase } from './litellmParamsPresidioAnalyzerApiBase';
import type { LitellmParamsPresidioAnonymizerApiBase } from './litellmParamsPresidioAnonymizerApiBase';
import type { LitellmParamsOutputParsePii } from './litellmParamsOutputParsePii';
import type { LitellmParamsPresidioLanguage } from './litellmParamsPresidioLanguage';
import type { LitellmParamsPiiEntitiesConfig } from './litellmParamsPiiEntitiesConfig';
import type { LitellmParamsPresidioAdHocRecognizers } from './litellmParamsPresidioAdHocRecognizers';
import type { LitellmParamsMockRedactedText } from './litellmParamsMockRedactedText';
import type { LitellmParamsMode } from './litellmParamsMode';

export interface LitellmParams {
  /** API key for the Lakera AI service */
  api_key?: LitellmParamsApiKey;
  /** Base URL for the Lakera AI API */
  api_base?: LitellmParamsApiBase;
  /** Threshold configuration for Lakera guardrail categories */
  category_thresholds?: LitellmParamsCategoryThresholds;
  /** Configuration for detect-secrets guardrail */
  detect_secrets_config?: LitellmParamsDetectSecretsConfig;
  /** Name of the guardrail in guardrails.ai */
  guard_name?: LitellmParamsGuardName;
  /** Whether the guardrail is enabled by default */
  default_on?: LitellmParamsDefaultOn;
  /** Will mask request content if guardrail makes any changes */
  mask_request_content?: LitellmParamsMaskRequestContent;
  /** Will mask response content if guardrail makes any changes */
  mask_response_content?: LitellmParamsMaskResponseContent;
  /** Recipe for input (LLM request) */
  pangea_input_recipe?: LitellmParamsPangeaInputRecipe;
  /** Recipe for output (LLM response) */
  pangea_output_recipe?: LitellmParamsPangeaOutputRecipe;
  /** Optional field if guardrail requires a 'model' parameter */
  model?: LitellmParamsModel;
  /** The ID of your Model Armor template */
  template_id?: LitellmParamsTemplateId;
  /** Google Cloud location/region (e.g., us-central1) */
  location?: LitellmParamsLocation;
  /** Path to Google Cloud credentials JSON file or JSON string */
  credentials?: LitellmParamsCredentials;
  /** Optional custom API endpoint for Model Armor */
  api_endpoint?: LitellmParamsApiEndpoint;
  /** Whether to fail the request if Model Armor encounters an error */
  fail_on_error?: LitellmParamsFailOnError;
  /** Action to take when content is flagged: 'block' (raise exception) or 'monitor' (log only) */
  on_flagged_action?: LitellmParamsOnFlaggedAction;
  /** User ID for the Lasso guardrail */
  lasso_user_id?: LitellmParamsLassoUserId;
  /** Conversation ID for the Lasso guardrail */
  lasso_conversation_id?: LitellmParamsLassoConversationId;
  /** Project ID for the Lakera AI project */
  project_id?: LitellmParamsProjectId;
  /** Whether to include payload in the response */
  payload?: LitellmParamsPayload;
  /** Whether to include breakdown in the response */
  breakdown?: LitellmParamsBreakdown;
  /** Additional metadata to include in the request */
  metadata?: LitellmParamsMetadata;
  /** Whether to include developer information in the response */
  dev_info?: LitellmParamsDevInfo;
  /** The ID of your guardrail on Bedrock */
  guardrailIdentifier?: LitellmParamsGuardrailIdentifier;
  /** The version of your Bedrock guardrail (e.g., DRAFT or version number) */
  guardrailVersion?: LitellmParamsGuardrailVersion;
  /** If True, will not raise an exception when the guardrail is blocked. Useful for OpenWebUI where exceptions can end the chat flow. */
  disable_exception_on_block?: LitellmParamsDisableExceptionOnBlock;
  /** AWS region where your guardrail is deployed */
  aws_region_name?: LitellmParamsAwsRegionName;
  /** AWS access key ID for authentication */
  aws_access_key_id?: LitellmParamsAwsAccessKeyId;
  /** AWS secret access key for authentication */
  aws_secret_access_key?: LitellmParamsAwsSecretAccessKey;
  /** AWS session token for temporary credentials */
  aws_session_token?: LitellmParamsAwsSessionToken;
  /** Name of the AWS session */
  aws_session_name?: LitellmParamsAwsSessionName;
  /** AWS profile name for credential retrieval */
  aws_profile_name?: LitellmParamsAwsProfileName;
  /** AWS role name for assuming roles */
  aws_role_name?: LitellmParamsAwsRoleName;
  /** Web identity token for AWS role assumption */
  aws_web_identity_token?: LitellmParamsAwsWebIdentityToken;
  /** AWS STS endpoint URL */
  aws_sts_endpoint?: LitellmParamsAwsStsEndpoint;
  /** AWS Bedrock runtime endpoint URL */
  aws_bedrock_runtime_endpoint?: LitellmParamsAwsBedrockRuntimeEndpoint;
  /** Base URL for the Presidio analyzer API */
  presidio_analyzer_api_base?: LitellmParamsPresidioAnalyzerApiBase;
  /** Base URL for the Presidio anonymizer API */
  presidio_anonymizer_api_base?: LitellmParamsPresidioAnonymizerApiBase;
  /** When True, LiteLLM will replace the masked text with the original text in the response */
  output_parse_pii?: LitellmParamsOutputParsePii;
  /** Language code for Presidio PII analysis (e.g., 'en', 'de', 'es', 'fr') */
  presidio_language?: LitellmParamsPresidioLanguage;
  /** Configuration for PII entity types and actions */
  pii_entities_config?: LitellmParamsPiiEntitiesConfig;
  /** Path to a JSON file containing ad-hoc recognizers for Presidio */
  presidio_ad_hoc_recognizers?: LitellmParamsPresidioAdHocRecognizers;
  /** Mock redacted text for testing */
  mock_redacted_text?: LitellmParamsMockRedactedText;
  /** The type of guardrail integration to use */
  guardrail: string;
  /** When to apply the guardrail (pre_call, post_call, during_call, logging_only) */
  mode: LitellmParamsMode;
  [key: string]: unknown;
}
