/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the item. Always `mcp_approval_request`.

 */
export type MCPApprovalRequestType =
  (typeof MCPApprovalRequestType)[keyof typeof MCPApprovalRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MCPApprovalRequestType = {
  mcp_approval_request: 'mcp_approval_request',
} as const;
