/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Optional HTTP headers to send to the MCP server. Use for authentication
or other purposes.

 * @nullable
 */
export type MCPToolHeaders = { [key: string]: string } | null;
