/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { MessageDeltaContentImageFileObject } from './messageDeltaContentImageFileObject';
import type { MessageDeltaContentTextObject } from './messageDeltaContentTextObject';
import type { MessageDeltaContentRefusalObject } from './messageDeltaContentRefusalObject';
import type { MessageDeltaContentImageUrlObject } from './messageDeltaContentImageUrlObject';

export type MessageDeltaObjectDeltaContentItem =
  | MessageDeltaContentImageFileObject
  | MessageDeltaContentTextObject
  | MessageDeltaContentRefusalObject
  | MessageDeltaContentImageUrlObject;
