/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { MessageStreamEventOneOfFiveEvent } from './messageStreamEventOneOfFiveEvent';
import type { MessageDeltaObject } from './messageDeltaObject';

/**
 * Occurs when parts of a [Message](/docs/api-reference/messages/object) are being streamed.
 */
export type MessageStreamEventOneOfFive = {
  event: MessageStreamEventOneOfFiveEvent;
  data: MessageDeltaObject;
};
