/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { MessageContentImageFileObject } from './messageContentImageFileObject';
import type { MessageContentImageUrlObject } from './messageContentImageUrlObject';
import type { MessageContentTextObject } from './messageContentTextObject';
import type { MessageContentRefusalObject } from './messageContentRefusalObject';

export type MessageObjectContentItem =
  | MessageContentImageFileObject
  | MessageContentImageUrlObject
  | MessageContentTextObject
  | MessageContentRefusalObject;
