/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Specifies the detail level of the image. `low` uses fewer tokens, you can opt in to high resolution using `high`.
 */
export type MessageDeltaContentImageUrlObjectImageUrlDetail =
  (typeof MessageDeltaContentImageUrlObjectImageUrlDetail)[keyof typeof MessageDeltaContentImageUrlObjectImageUrlDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageDeltaContentImageUrlObjectImageUrlDetail = {
  auto: 'auto',
  low: 'low',
  high: 'high',
} as const;
