/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The entity that produced the message. One of `user` or `assistant`.
 */
export type MessageObjectRole =
  (typeof MessageObjectRole)[keyof typeof MessageObjectRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageObjectRole = {
  user: 'user',
  assistant: 'assistant',
} as const;
