/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { MessageStreamEventOneOf } from './messageStreamEventOneOf';
import type { MessageStreamEventOneOfThree } from './messageStreamEventOneOfThree';
import type { MessageStreamEventOneOfFive } from './messageStreamEventOneOfFive';
import type { MessageStreamEventOneOfSeven } from './messageStreamEventOneOfSeven';
import type { MessageStreamEventOneOfNine } from './messageStreamEventOneOfNine';

export type MessageStreamEvent =
  | MessageStreamEventOneOf
  | MessageStreamEventOneOfThree
  | MessageStreamEventOneOfFive
  | MessageStreamEventOneOfSeven
  | MessageStreamEventOneOfNine;
