/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { MessageStreamEventOneOfSevenEvent } from './messageStreamEventOneOfSevenEvent';
import type { MessageObject } from './messageObject';

/**
 * Occurs when a [message](/docs/api-reference/messages/object) is completed.
 */
export type MessageStreamEventOneOfSeven = {
  event: MessageStreamEventOneOfSevenEvent;
  data: MessageObject;
};
