/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { NewOrganizationRequestBudgetId } from './newOrganizationRequestBudgetId';
import type { NewOrganizationRequestSoftBudget } from './newOrganizationRequestSoftBudget';
import type { NewOrganizationRequestMaxBudget } from './newOrganizationRequestMaxBudget';
import type { NewOrganizationRequestMaxParallelRequests } from './newOrganizationRequestMaxParallelRequests';
import type { NewOrganizationRequestTpmLimit } from './newOrganizationRequestTpmLimit';
import type { NewOrganizationRequestRpmLimit } from './newOrganizationRequestRpmLimit';
import type { NewOrganizationRequestModelMaxBudget } from './newOrganizationRequestModelMaxBudget';
import type { NewOrganizationRequestBudgetDuration } from './newOrganizationRequestBudgetDuration';
import type { NewOrganizationRequestOrganizationId } from './newOrganizationRequestOrganizationId';
import type { NewOrganizationRequestMetadata } from './newOrganizationRequestMetadata';
import type { NewOrganizationRequestObjectPermission } from './newOrganizationRequestObjectPermission';

export interface NewOrganizationRequest {
  budget_id?: NewOrganizationRequestBudgetId;
  soft_budget?: NewOrganizationRequestSoftBudget;
  max_budget?: NewOrganizationRequestMaxBudget;
  max_parallel_requests?: NewOrganizationRequestMaxParallelRequests;
  tpm_limit?: NewOrganizationRequestTpmLimit;
  rpm_limit?: NewOrganizationRequestRpmLimit;
  model_max_budget?: NewOrganizationRequestModelMaxBudget;
  budget_duration?: NewOrganizationRequestBudgetDuration;
  organization_id?: NewOrganizationRequestOrganizationId;
  organization_alias: string;
  models?: unknown[];
  metadata?: NewOrganizationRequestMetadata;
  object_permission?: NewOrganizationRequestObjectPermission;
}
