/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The role of the output message. Always `assistant`.

 */
export type OutputMessageRole =
  (typeof OutputMessageRole)[keyof typeof OutputMessageRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OutputMessageRole = {
  assistant: 'assistant',
} as const;
