/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * `owner` or `member`
 */
export type ProjectUserCreateRequestRole =
  (typeof ProjectUserCreateRequestRole)[keyof typeof ProjectUserCreateRequestRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectUserCreateRequestRole = {
  owner: 'owner',
  member: 'member',
} as const;
