/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * `user` or `service_account`
 */
export type ProjectApiKeyOwnerType =
  (typeof ProjectApiKeyOwnerType)[keyof typeof ProjectApiKeyOwnerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectApiKeyOwnerType = {
  user: 'user',
  service_account: 'service_account',
} as const;
