/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The ranker to use for the file search.
 */
export type RankingOptionsRanker =
  (typeof RankingOptionsRanker)[keyof typeof RankingOptionsRanker];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RankingOptionsRanker = {
  auto: 'auto',
  'default-2024-11-15': 'default-2024-11-15',
} as const;
