/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `input_audio_buffer.cleared`.
 */
export type RealtimeServerEventInputAudioBufferClearedType =
  (typeof RealtimeServerEventInputAudioBufferClearedType)[keyof typeof RealtimeServerEventInputAudioBufferClearedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventInputAudioBufferClearedType = {
  input_audio_buffercleared: 'input_audio_buffer.cleared',
} as const;
