/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `response.content_part.added`.
 */
export type RealtimeServerEventResponseContentPartAddedType =
  (typeof RealtimeServerEventResponseContentPartAddedType)[keyof typeof RealtimeServerEventResponseContentPartAddedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventResponseContentPartAddedType = {
  responsecontent_partadded: 'response.content_part.added',
} as const;
