/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RealtimeTranscriptionSessionCreateRequestClientSecretExpiresAtAnchor } from './realtimeTranscriptionSessionCreateRequestClientSecretExpiresAtAnchor';

/**
 * Configuration for the ephemeral token expiration.

 */
export type RealtimeTranscriptionSessionCreateRequestClientSecretExpiresAt = {
  /** The anchor point for the ephemeral token expiration. Only `created_at` is currently supported.
   */
  anchor?: RealtimeTranscriptionSessionCreateRequestClientSecretExpiresAtAnchor;
  /** The number of seconds from the anchor point to the expiration. Select a value between `10` and `7200`.
   */
  seconds?: number;
};
