/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `response.function_call_arguments.done`.

 */
export type RealtimeServerEventResponseFunctionCallArgumentsDoneType =
  (typeof RealtimeServerEventResponseFunctionCallArgumentsDoneType)[keyof typeof RealtimeServerEventResponseFunctionCallArgumentsDoneType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventResponseFunctionCallArgumentsDoneType = {
  responsefunction_call_argumentsdone: 'response.function_call_arguments.done',
} as const;
