/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RealtimeServerEventConversationCreatedType } from './realtimeServerEventConversationCreatedType';
import type { RealtimeServerEventConversationCreatedConversation } from './realtimeServerEventConversationCreatedConversation';

/**
 * Returned when a conversation is created. Emitted right after session creation.

 */
export interface RealtimeServerEventConversationCreated {
  /** The unique ID of the server event. */
  event_id: string;
  /** The event type, must be `conversation.created`. */
  type: RealtimeServerEventConversationCreatedType;
  /** The conversation resource. */
  conversation: RealtimeServerEventConversationCreatedConversation;
}
