/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `conversation.item.deleted`.
 */
export type RealtimeServerEventConversationItemDeletedType =
  (typeof RealtimeServerEventConversationItemDeletedType)[keyof typeof RealtimeServerEventConversationItemDeletedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventConversationItemDeletedType = {
  conversationitemdeleted: 'conversation.item.deleted',
} as const;
