/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The anchor point for the ephemeral token expiration. Only `created_at` is currently supported.

 */
export type RealtimeSessionCreateRequestClientSecretExpiresAfterAnchor =
  (typeof RealtimeSessionCreateRequestClientSecretExpiresAfterAnchor)[keyof typeof RealtimeSessionCreateRequestClientSecretExpiresAfterAnchor];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeSessionCreateRequestClientSecretExpiresAfterAnchor = {
  created_at: 'created_at',
} as const;
