/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RealtimeServerEventResponseContentPartAddedPartType } from './realtimeServerEventResponseContentPartAddedPartType';

/**
 * The content part that was added.
 */
export type RealtimeServerEventResponseContentPartAddedPart = {
  /** The content type ("text", "audio"). */
  type?: RealtimeServerEventResponseContentPartAddedPartType;
  /** The text content (if type is "text"). */
  text?: string;
  /** Base64-encoded audio data (if type is "audio"). */
  audio?: string;
  /** The transcript of the audio (if type is "audio"). */
  transcript?: string;
};
