/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The Realtime model used for this session.

 */
export type RealtimeSessionModel =
  (typeof RealtimeSessionModel)[keyof typeof RealtimeSessionModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeSessionModel = {
  'gpt-4o-realtime-preview': 'gpt-4o-realtime-preview',
  'gpt-4o-realtime-preview-2024-10-01': 'gpt-4o-realtime-preview-2024-10-01',
  'gpt-4o-realtime-preview-2024-12-17': 'gpt-4o-realtime-preview-2024-12-17',
  'gpt-4o-realtime-preview-2025-06-03': 'gpt-4o-realtime-preview-2025-06-03',
  'gpt-4o-mini-realtime-preview': 'gpt-4o-mini-realtime-preview',
  'gpt-4o-mini-realtime-preview-2024-12-17':
    'gpt-4o-mini-realtime-preview-2024-12-17',
} as const;
