/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `input_audio_buffer.commit`.
 */
export type RealtimeClientEventInputAudioBufferCommitType =
  (typeof RealtimeClientEventInputAudioBufferCommitType)[keyof typeof RealtimeClientEventInputAudioBufferCommitType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeClientEventInputAudioBufferCommitType = {
  input_audio_buffercommit: 'input_audio_buffer.commit',
} as const;
