/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `response.audio.done`.
 */
export type RealtimeServerEventResponseAudioDoneType =
  (typeof RealtimeServerEventResponseAudioDoneType)[keyof typeof RealtimeServerEventResponseAudioDoneType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventResponseAudioDoneType = {
  responseaudiodone: 'response.audio.done',
} as const;
