/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RealtimeServerEventResponseOutputItemDoneType } from './realtimeServerEventResponseOutputItemDoneType';
import type { RealtimeConversationItem } from './realtimeConversationItem';

/**
 * Returned when an Item is done streaming. Also emitted when a Response is 
interrupted, incomplete, or cancelled.

 */
export interface RealtimeServerEventResponseOutputItemDone {
  /** The unique ID of the server event. */
  event_id: string;
  /** The event type, must be `response.output_item.done`. */
  type: RealtimeServerEventResponseOutputItemDoneType;
  /** The ID of the Response to which the item belongs. */
  response_id: string;
  /** The index of the output item in the Response. */
  output_index: number;
  item: RealtimeConversationItem;
}
