/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `rate_limits.updated`.
 */
export type RealtimeServerEventRateLimitsUpdatedType =
  (typeof RealtimeServerEventRateLimitsUpdatedType)[keyof typeof RealtimeServerEventRateLimitsUpdatedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventRateLimitsUpdatedType = {
  rate_limitsupdated: 'rate_limits.updated',
} as const;
