/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `conversation.created`.
 */
export type RealtimeServerEventConversationCreatedType =
  (typeof RealtimeServerEventConversationCreatedType)[keyof typeof RealtimeServerEventConversationCreatedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventConversationCreatedType = {
  conversationcreated: 'conversation.created',
} as const;
