/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RealtimeConversationItemWithReferenceContentItemType } from './realtimeConversationItemWithReferenceContentItemType';

export type RealtimeConversationItemWithReferenceContentItem = {
  /** The content type (`input_text`, `input_audio`, `item_reference`, `text`).
   */
  type?: RealtimeConversationItemWithReferenceContentItemType;
  /** The text content, used for `input_text` and `text` content types.
   */
  text?: string;
  /** ID of a previous conversation item to reference (for `item_reference`
content types in `response.create` events). These can reference both
client and server created items.
 */
  id?: string;
  /** Base64-encoded audio bytes, used for `input_audio` content type.
   */
  audio?: string;
  /** The transcript of the audio, used for `input_audio` content type.
   */
  transcript?: string;
};
