/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `input_audio_buffer.committed`.
 */
export type RealtimeServerEventInputAudioBufferCommittedType =
  (typeof RealtimeServerEventInputAudioBufferCommittedType)[keyof typeof RealtimeServerEventInputAudioBufferCommittedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventInputAudioBufferCommittedType = {
  input_audio_buffercommitted: 'input_audio_buffer.committed',
} as const;
