/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `input_audio_buffer.clear`.
 */
export type RealtimeClientEventInputAudioBufferClearType =
  (typeof RealtimeClientEventInputAudioBufferClearType)[keyof typeof RealtimeClientEventInputAudioBufferClearType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeClientEventInputAudioBufferClearType = {
  input_audio_bufferclear: 'input_audio_buffer.clear',
} as const;
