/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { TranscriptTextUsageTokens } from './transcriptTextUsageTokens';
import type { TranscriptTextUsageDuration } from './transcriptTextUsageDuration';

/**
 * Usage statistics for the transcription.
 */
export type RealtimeServerEventConversationItemInputAudioTranscriptionCompletedUsage =
  TranscriptTextUsageTokens | TranscriptTextUsageDuration;
