/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Type of turn detection.

 */
export type RealtimeTranscriptionSessionCreateRequestTurnDetectionType =
  (typeof RealtimeTranscriptionSessionCreateRequestTurnDetectionType)[keyof typeof RealtimeTranscriptionSessionCreateRequestTurnDetectionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeTranscriptionSessionCreateRequestTurnDetectionType = {
  server_vad: 'server_vad',
  semantic_vad: 'semantic_vad',
} as const;
