/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Type of noise reduction. `near_field` is for close-talking microphones such as headphones, `far_field` is for far-field microphones such as laptop or conference room microphones.

 */
export type RealtimeSessionCreateRequestInputAudioNoiseReductionType =
  (typeof RealtimeSessionCreateRequestInputAudioNoiseReductionType)[keyof typeof RealtimeSessionCreateRequestInputAudioNoiseReductionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeSessionCreateRequestInputAudioNoiseReductionType = {
  near_field: 'near_field',
  far_field: 'far_field',
} as const;
