/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RealtimeServerEventErrorType } from './realtimeServerEventErrorType';
import type { RealtimeServerEventErrorError } from './realtimeServerEventErrorError';

/**
 * Returned when an error occurs, which could be a client problem or a server 
problem. Most errors are recoverable and the session will stay open, we 
recommend to implementors to monitor and log error messages by default.

 */
export interface RealtimeServerEventError {
  /** The unique ID of the server event. */
  event_id: string;
  /** The event type, must be `error`. */
  type: RealtimeServerEventErrorType;
  /** Details of the error. */
  error: RealtimeServerEventErrorError;
}
