/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `response.output_item.added`.
 */
export type RealtimeServerEventResponseOutputItemAddedType =
  (typeof RealtimeServerEventResponseOutputItemAddedType)[keyof typeof RealtimeServerEventResponseOutputItemAddedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventResponseOutputItemAddedType = {
  responseoutput_itemadded: 'response.output_item.added',
} as const;
