/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Details of the transcription error.
 */
export type RealtimeServerEventConversationItemInputAudioTranscriptionFailedError =
  {
    /** The type of error. */
    type?: string;
    /** Error code, if any. */
    code?: string;
    /** A human-readable error message. */
    message?: string;
    /** Parameter related to the error, if any. */
    param?: string;
  };
