/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The name of the rate limit (`requests`, `tokens`).

 */
export type RealtimeServerEventRateLimitsUpdatedRateLimitsItemName =
  (typeof RealtimeServerEventRateLimitsUpdatedRateLimitsItemName)[keyof typeof RealtimeServerEventRateLimitsUpdatedRateLimitsItemName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventRateLimitsUpdatedRateLimitsItemName = {
  requests: 'requests',
  tokens: 'tokens',
} as const;
