/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RealtimeResponseStatusDetailsType } from './realtimeResponseStatusDetailsType';
import type { RealtimeResponseStatusDetailsReason } from './realtimeResponseStatusDetailsReason';
import type { RealtimeResponseStatusDetailsError } from './realtimeResponseStatusDetailsError';

/**
 * Additional details about the status.
 */
export type RealtimeResponseStatusDetails = {
  /** The type of error that caused the response to fail, corresponding 
with the `status` field (`completed`, `cancelled`, `incomplete`, 
`failed`).
 */
  type?: RealtimeResponseStatusDetailsType;
  /** The reason the Response did not complete. For a `cancelled` Response, 
one of `turn_detected` (the server VAD detected a new start of speech) 
or `client_cancelled` (the client sent a cancel event). For an 
`incomplete` Response, one of `max_output_tokens` or `content_filter` 
(the server-side safety filter activated and cut off the response).
 */
  reason?: RealtimeResponseStatusDetailsReason;
  /** A description of the error that caused the response to fail, 
populated when the `status` is `failed`.
 */
  error?: RealtimeResponseStatusDetailsError;
};
