/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `error`.
 */
export type RealtimeServerEventErrorType =
  (typeof RealtimeServerEventErrorType)[keyof typeof RealtimeServerEventErrorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventErrorType = {
  error: 'error',
} as const;
