/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Maximum number of output tokens for a single assistant response,
inclusive of tool calls, that was used in this response.

 */
export type RealtimeResponseMaxOutputTokens = number | 'inf';
