/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `transcription_session.update`.
 */
export type RealtimeClientEventTranscriptionSessionUpdateType =
  (typeof RealtimeClientEventTranscriptionSessionUpdateType)[keyof typeof RealtimeClientEventTranscriptionSessionUpdateType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeClientEventTranscriptionSessionUpdateType = {
  transcription_sessionupdate: 'transcription_session.update',
} as const;
