/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The event type, must be `output_audio_buffer.cleared`.
 */
export type RealtimeServerEventOutputAudioBufferClearedType =
  (typeof RealtimeServerEventOutputAudioBufferClearedType)[keyof typeof RealtimeServerEventOutputAudioBufferClearedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealtimeServerEventOutputAudioBufferClearedType = {
  output_audio_buffercleared: 'output_audio_buffer.cleared',
} as const;
