/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ReasoningItemType } from './reasoningItemType';
import type { ReasoningItemSummaryItem } from './reasoningItemSummaryItem';
import type { ReasoningItemStatus } from './reasoningItemStatus';

/**
 * A description of the chain of thought used by a reasoning model while generating
a response. Be sure to include these items in your `input` to the Responses API
for subsequent turns of a conversation if you are manually 
[managing context](/docs/guides/conversation-state).

 */
export interface ReasoningItem {
  /** The type of the object. Always `reasoning`.
   */
  type: ReasoningItemType;
  /** The unique identifier of the reasoning content.
   */
  id: string;
  /**
   * The encrypted content of the reasoning item - populated when a response is
generated with `reasoning.encrypted_content` in the `include` parameter.

   * @nullable
   */
  encrypted_content?: string | null;
  /** Reasoning text contents.
   */
  summary: ReasoningItemSummaryItem[];
  /** The status of the item. One of `in_progress`, `completed`, or
`incomplete`. Populated when items are returned via API.
 */
  status?: ReasoningItemStatus;
}
