/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * A summary of the reasoning performed by the model. This can be
useful for debugging and understanding the model's reasoning process.
One of `auto`, `concise`, or `detailed`.

 * @nullable
 */
export type ReasoningSummary =
  | (typeof ReasoningSummary)[keyof typeof ReasoningSummary]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReasoningSummary = {
  auto: 'auto',
  concise: 'concise',
  detailed: 'detailed',
} as const;
