/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of response format being defined. Always `json_schema`.
 */
export type ResponseFormatJsonSchemaType =
  (typeof ResponseFormatJsonSchemaType)[keyof typeof ResponseFormatJsonSchemaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseFormatJsonSchemaType = {
  json_schema: 'json_schema',
} as const;
