/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * A detailed breakdown of the input tokens.
 */
export type ResponseUsageInputTokensDetails = {
  /** The number of tokens that were retrieved from the cache. 
[More on prompt caching](/docs/guides/prompt-caching).
 */
  cached_tokens: number;
};
