/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the event. Always `response.output_text.delta`.

 */
export type ResponseTextDeltaEventType =
  (typeof ResponseTextDeltaEventType)[keyof typeof ResponseTextDeltaEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseTextDeltaEventType = {
  responseoutput_textdelta: 'response.output_text.delta',
} as const;
