/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ResponseFailedEventType } from './responseFailedEventType';
import type { Response } from './response';

/**
 * An event that is emitted when a response fails.

 */
export interface ResponseFailedEvent {
  /** The type of the event. Always `response.failed`.
   */
  type: ResponseFailedEventType;
  /** The sequence number of this event. */
  sequence_number: number;
  /** The response that failed.
   */
  response: Response;
}
