/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ResponseLogProbTopLogprobsItem } from './responseLogProbTopLogprobsItem';

/**
 * A logprob is the logarithmic probability that the model assigns to producing 
a particular token at a given position in the sequence. Less-negative (higher) 
logprob values indicate greater model confidence in that token choice.

 */
export interface ResponseLogProb {
  /** A possible text token. */
  token: string;
  /** The log probability of this token.
   */
  logprob: number;
  /** The log probability of the top 20 most likely tokens.
   */
  top_logprobs?: ResponseLogProbTopLogprobsItem[];
}
