/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ResponseIncompleteEventType } from './responseIncompleteEventType';
import type { Response } from './response';

/**
 * An event that is emitted when a response finishes as incomplete.

 */
export interface ResponseIncompleteEvent {
  /** The type of the event. Always `response.incomplete`.
   */
  type: ResponseIncompleteEventType;
  /** The response that was incomplete.
   */
  response: Response;
  /** The sequence number of this event. */
  sequence_number: number;
}
