/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the event. Always `response.refusal.delta`.

 */
export type ResponseRefusalDeltaEventType =
  (typeof ResponseRefusalDeltaEventType)[keyof typeof ResponseRefusalDeltaEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseRefusalDeltaEventType = {
  responserefusaldelta: 'response.refusal.delta',
} as const;
