/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the event. Always `response.reasoning_summary_text.delta`.

 */
export type ResponseReasoningSummaryTextDeltaEventType =
  (typeof ResponseReasoningSummaryTextDeltaEventType)[keyof typeof ResponseReasoningSummaryTextDeltaEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseReasoningSummaryTextDeltaEventType = {
  responsereasoning_summary_textdelta: 'response.reasoning_summary_text.delta',
} as const;
