/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ResponseMCPCallFailedEventType } from './responseMCPCallFailedEventType';

/**
 * Emitted when an MCP  tool call has failed.

 */
export interface ResponseMCPCallFailedEvent {
  /** The type of the event. Always 'response.mcp_call.failed'. */
  type: ResponseMCPCallFailedEventType;
  /** The ID of the MCP tool call item that failed. */
  item_id: string;
  /** The index of the output item that failed. */
  output_index: number;
  /** The sequence number of this event. */
  sequence_number: number;
}
