/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ResponseOutputItemDoneEventType } from './responseOutputItemDoneEventType';
import type { OutputItem } from './outputItem';

/**
 * Emitted when an output item is marked done.
 */
export interface ResponseOutputItemDoneEvent {
  /** The type of the event. Always `response.output_item.done`.
   */
  type: ResponseOutputItemDoneEventType;
  /** The index of the output item that was marked done.
   */
  output_index: number;
  /** The sequence number of this event.
   */
  sequence_number: number;
  /** The output item that was marked done.
   */
  item: OutputItem;
}
