/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * For now, this is always `submit_tool_outputs`.
 */
export type RunObjectRequiredActionType =
  (typeof RunObjectRequiredActionType)[keyof typeof RunObjectRequiredActionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunObjectRequiredActionType = {
  submit_tool_outputs: 'submit_tool_outputs',
} as const;
