/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * One of `server_error`, `rate_limit_exceeded`, or `invalid_prompt`.
 */
export type RunObjectLastErrorCode =
  (typeof RunObjectLastErrorCode)[keyof typeof RunObjectLastErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunObjectLastErrorCode = {
  server_error: 'server_error',
  rate_limit_exceeded: 'rate_limit_exceeded',
  invalid_prompt: 'invalid_prompt',
} as const;
