/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RunStepDeltaStepDetailsToolCallsFunctionObjectType } from './runStepDeltaStepDetailsToolCallsFunctionObjectType';
import type { RunStepDeltaStepDetailsToolCallsFunctionObjectFunction } from './runStepDeltaStepDetailsToolCallsFunctionObjectFunction';

export interface RunStepDeltaStepDetailsToolCallsFunctionObject {
  /** The index of the tool call in the tool calls array. */
  index: number;
  /** The ID of the tool call object. */
  id?: string;
  /** The type of tool call. This is always going to be `function` for this type of tool call. */
  type: RunStepDeltaStepDetailsToolCallsFunctionObjectType;
  /** The definition of the function that was called. */
  function?: RunStepDeltaStepDetailsToolCallsFunctionObjectFunction;
}
