/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type RunStepStreamEventOneOfOneoneEvent =
  (typeof RunStepStreamEventOneOfOneoneEvent)[keyof typeof RunStepStreamEventOneOfOneoneEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunStepStreamEventOneOfOneoneEvent = {
  threadrunstepcancelled: 'thread.run.step.cancelled',
} as const;
