/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type RunStreamEventOneOfThreeEvent =
  (typeof RunStreamEventOneOfThreeEvent)[keyof typeof RunStreamEventOneOfThreeEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunStreamEventOneOfThreeEvent = {
  threadrunqueued: 'thread.run.queued',
} as const;
