/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RunStreamEventOneOfOnenineEvent } from './runStreamEventOneOfOnenineEvent';
import type { RunObject } from './runObject';

/**
 * Occurs when a [run](/docs/api-reference/runs/object) expires.
 */
export type RunStreamEventOneOfOnenine = {
  event: RunStreamEventOneOfOnenineEvent;
  data: RunObject;
};
