/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type ThreadStreamEventOneOfEvent =
  (typeof ThreadStreamEventOneOfEvent)[keyof typeof ThreadStreamEventOneOfEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThreadStreamEventOneOfEvent = {
  threadcreated: 'thread.created',
} as const;
