/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ToolChoiceFunctionType } from './toolChoiceFunctionType';

/**
 * Use this option to force the model to call a specific function.

 */
export interface ToolChoiceFunction {
  /** For function calling, the type is always `function`. */
  type: ToolChoiceFunctionType;
  /** The name of the function to call. */
  name: string;
}
