/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { ToolChoiceTypesType } from './toolChoiceTypesType';

/**
 * Indicates that the model should use a built-in tool to generate a response.
[Learn more about built-in tools](/docs/guides/tools).

 */
export interface ToolChoiceTypes {
  /** The type of hosted tool the model should to use. Learn more about
[built-in tools](/docs/guides/tools).

Allowed values are:
- `file_search`
- `web_search_preview`
- `computer_use_preview`
- `code_interpreter`
- `image_generation`
 */
  type: ToolChoiceTypesType;
}
