/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export interface TranscriptionWord {
  /** The text content of the word. */
  word: string;
  /** Start time of the word in seconds. */
  start: number;
  /** End time of the word in seconds. */
  end: number;
}
