/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The object type, which is always `upload.part`.
 */
export type UploadPartObject =
  (typeof UploadPartObject)[keyof typeof UploadPartObject];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadPartObject = {
  uploadpart: 'upload.part',
} as const;
