/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type UsageVectorStoresBucketWidth =
  (typeof UsageVectorStoresBucketWidth)[keyof typeof UsageVectorStoresBucketWidth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsageVectorStoresBucketWidth = {
  '1m': '1m',
  '1h': '1h',
  '1d': '1d',
} as const;
