/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type UsageCompletionsGroupByItem =
  (typeof UsageCompletionsGroupByItem)[keyof typeof UsageCompletionsGroupByItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsageCompletionsGroupByItem = {
  project_id: 'project_id',
  user_id: 'user_id',
  api_key_id: 'api_key_id',
  model: 'model',
  batch: 'batch',
} as const;
