/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type UsageCompletionsBucketWidth =
  (typeof UsageCompletionsBucketWidth)[keyof typeof UsageCompletionsBucketWidth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsageCompletionsBucketWidth = {
  '1m': '1m',
  '1h': '1h',
  '1d': '1d',
} as const;
