/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { UsageCostsBucketWidth } from './usageCostsBucketWidth';
import type { UsageCostsGroupByItem } from './usageCostsGroupByItem';

export type UsageCostsParams = {
  /**
   * Start time (Unix seconds) of the query time range, inclusive.
   */
  start_time: number;
  /**
   * End time (Unix seconds) of the query time range, exclusive.
   */
  end_time?: number;
  /**
   * Width of each time bucket in response. Currently only `1d` is supported, default to `1d`.
   */
  bucket_width?: UsageCostsBucketWidth;
  /**
   * Return only costs for these projects.
   */
  project_ids?: string[];
  /**
   * Group the costs by the specified fields. Support fields include `project_id`, `line_item` and any combination of them.
   */
  group_by?: UsageCostsGroupByItem[];
  /**
 * A limit on the number of buckets to be returned. Limit can range between 1 and 180, and the default is 7.

 */
  limit?: number;
  /**
   * A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.
   */
  page?: string;
};
