/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The object type, which is always `vector_store.search_results.page`
 */
export type VectorStoreSearchResultsPageObject =
  (typeof VectorStoreSearchResultsPageObject)[keyof typeof VectorStoreSearchResultsPageObject];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VectorStoreSearchResultsPageObject = {
  vector_storesearch_resultspage: 'vector_store.search_results.page',
} as const;
