/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The object type, which is always `vector_store.file_content.page`
 */
export type VectorStoreFileContentResponseObject =
  (typeof VectorStoreFileContentResponseObject)[keyof typeof VectorStoreFileContentResponseObject];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VectorStoreFileContentResponseObject = {
  vector_storefile_contentpage: 'vector_store.file_content.page',
} as const;
