/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { WaitType } from './waitType';

/**
 * A wait action.

 */
export interface Wait {
  /** Specifies the event type. For a wait action, this property is 
always set to `wait`.
 */
  type: WaitType;
}
