/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * Specifies the event type. For a wait action, this property is 
always set to `wait`.

 */
export type WaitType = (typeof WaitType)[keyof typeof WaitType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WaitType = {
  wait: 'wait',
} as const;
