/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the event. Always `batch.cancelled`.

 */
export type WebhookBatchCancelledType =
  (typeof WebhookBatchCancelledType)[keyof typeof WebhookBatchCancelledType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WebhookBatchCancelledType = {
  batchcancelled: 'batch.cancelled',
} as const;
