/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { WebhookBatchCancelledData } from './webhookBatchCancelledData';
import type { WebhookBatchCancelledObject } from './webhookBatchCancelledObject';
import type { WebhookBatchCancelledType } from './webhookBatchCancelledType';

/**
 * Sent when a batch API request has been cancelled.

 */
export interface WebhookBatchCancelled {
  /** The Unix timestamp (in seconds) of when the batch API request was cancelled.
   */
  created_at: number;
  /** The unique ID of the event.
   */
  id: string;
  /** Event data payload.
   */
  data: WebhookBatchCancelledData;
  /** The object of the event. Always `event`.
   */
  object?: WebhookBatchCancelledObject;
  /** The type of the event. Always `batch.cancelled`.
   */
  type: WebhookBatchCancelledType;
}
