/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { WebSearchActionOpenPageType } from './webSearchActionOpenPageType';

/**
 * Action type "open_page" - Opens a specific URL from search results.

 */
export interface WebSearchActionOpenPage {
  /** The action type.
   */
  type: WebSearchActionOpenPageType;
  /** The URL opened by the model.
   */
  url: string;
}
