/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The type of the web search tool. One of `web_search_preview` or `web_search_preview_2025_03_11`.
 */
export type WebSearchPreviewToolType =
  (typeof WebSearchPreviewToolType)[keyof typeof WebSearchPreviewToolType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WebSearchPreviewToolType = {
  web_search_preview: 'web_search_preview',
  web_search_preview_2025_03_11: 'web_search_preview_2025_03_11',
} as const;
