/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { WebSearchActionFindType } from './webSearchActionFindType';

/**
 * Action type "find": Searches for a pattern within a loaded page.

 */
export interface WebSearchActionFind {
  /** The action type.
   */
  type: WebSearchActionFindType;
  /** The URL of the page searched for the pattern.
   */
  url: string;
  /** The pattern or text to search for within the page.
   */
  pattern: string;
}
