/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type {
  ErrorResponse,
  ListProjectApiKeysParams,
  ListProjectRateLimitsParams,
  ListProjectServiceAccountsParams,
  ListProjectUsersParams,
  ListProjectsParams,
  Project,
  ProjectApiKey,
  ProjectApiKeyDeleteResponse,
  ProjectApiKeyListResponse,
  ProjectCreateRequest,
  ProjectListResponse,
  ProjectRateLimit,
  ProjectRateLimitListResponse,
  ProjectRateLimitUpdateRequest,
  ProjectServiceAccount,
  ProjectServiceAccountCreateRequest,
  ProjectServiceAccountCreateResponse,
  ProjectServiceAccountDeleteResponse,
  ProjectServiceAccountListResponse,
  ProjectUpdateRequest,
  ProjectUser,
  ProjectUserCreateRequest,
  ProjectUserDeleteResponse,
  ProjectUserListResponse,
  ProjectUserUpdateRequest,
} from '.././schemas';

/**
 * @summary Returns a list of projects.
 */
export type listProjectsResponse200 = {
  data: ProjectListResponse;
  status: 200;
};

export type listProjectsResponseComposite = listProjectsResponse200;

export type listProjectsResponse = listProjectsResponseComposite & {
  headers: Headers;
};

export const getListProjectsUrl = (params?: ListProjectsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/organization/projects?${stringifiedParams}`
    : `/organization/projects`;
};

export const listProjects = async (
  params?: ListProjectsParams,
  options?: RequestInit
): Promise<listProjectsResponse> => {
  const res = await fetch(getListProjectsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listProjectsResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listProjectsResponse;
};

/**
 * @summary Create a new project in the organization. Projects can be created and archived, but cannot be deleted.
 */
export type createProjectResponse200 = {
  data: Project;
  status: 200;
};

export type createProjectResponseComposite = createProjectResponse200;

export type createProjectResponse = createProjectResponseComposite & {
  headers: Headers;
};

export const getCreateProjectUrl = () => {
  return `/organization/projects`;
};

export const createProject = async (
  projectCreateRequest: ProjectCreateRequest,
  options?: RequestInit
): Promise<createProjectResponse> => {
  const res = await fetch(getCreateProjectUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectCreateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createProjectResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createProjectResponse;
};

/**
 * @summary Retrieves a project.
 */
export type retrieveProjectResponse200 = {
  data: Project;
  status: 200;
};

export type retrieveProjectResponseComposite = retrieveProjectResponse200;

export type retrieveProjectResponse = retrieveProjectResponseComposite & {
  headers: Headers;
};

export const getRetrieveProjectUrl = (projectId: string) => {
  return `/organization/projects/${projectId}`;
};

export const retrieveProject = async (
  projectId: string,
  options?: RequestInit
): Promise<retrieveProjectResponse> => {
  const res = await fetch(getRetrieveProjectUrl(projectId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveProjectResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveProjectResponse;
};

/**
 * @summary Modifies a project in the organization.
 */
export type modifyProjectResponse200 = {
  data: Project;
  status: 200;
};

export type modifyProjectResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type modifyProjectResponseComposite =
  | modifyProjectResponse200
  | modifyProjectResponse400;

export type modifyProjectResponse = modifyProjectResponseComposite & {
  headers: Headers;
};

export const getModifyProjectUrl = (projectId: string) => {
  return `/organization/projects/${projectId}`;
};

export const modifyProject = async (
  projectId: string,
  projectUpdateRequest: ProjectUpdateRequest,
  options?: RequestInit
): Promise<modifyProjectResponse> => {
  const res = await fetch(getModifyProjectUrl(projectId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: modifyProjectResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as modifyProjectResponse;
};

/**
 * @summary Returns a list of API keys in the project.
 */
export type listProjectApiKeysResponse200 = {
  data: ProjectApiKeyListResponse;
  status: 200;
};

export type listProjectApiKeysResponseComposite = listProjectApiKeysResponse200;

export type listProjectApiKeysResponse = listProjectApiKeysResponseComposite & {
  headers: Headers;
};

export const getListProjectApiKeysUrl = (
  projectId: string,
  params?: ListProjectApiKeysParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/organization/projects/${projectId}/api_keys?${stringifiedParams}`
    : `/organization/projects/${projectId}/api_keys`;
};

export const listProjectApiKeys = async (
  projectId: string,
  params?: ListProjectApiKeysParams,
  options?: RequestInit
): Promise<listProjectApiKeysResponse> => {
  const res = await fetch(getListProjectApiKeysUrl(projectId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listProjectApiKeysResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listProjectApiKeysResponse;
};

/**
 * @summary Retrieves an API key in the project.
 */
export type retrieveProjectApiKeyResponse200 = {
  data: ProjectApiKey;
  status: 200;
};

export type retrieveProjectApiKeyResponseComposite =
  retrieveProjectApiKeyResponse200;

export type retrieveProjectApiKeyResponse =
  retrieveProjectApiKeyResponseComposite & {
    headers: Headers;
  };

export const getRetrieveProjectApiKeyUrl = (
  projectId: string,
  keyId: string
) => {
  return `/organization/projects/${projectId}/api_keys/${keyId}`;
};

export const retrieveProjectApiKey = async (
  projectId: string,
  keyId: string,
  options?: RequestInit
): Promise<retrieveProjectApiKeyResponse> => {
  const res = await fetch(getRetrieveProjectApiKeyUrl(projectId, keyId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveProjectApiKeyResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveProjectApiKeyResponse;
};

/**
 * @summary Deletes an API key from the project.
 */
export type deleteProjectApiKeyResponse200 = {
  data: ProjectApiKeyDeleteResponse;
  status: 200;
};

export type deleteProjectApiKeyResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type deleteProjectApiKeyResponseComposite =
  | deleteProjectApiKeyResponse200
  | deleteProjectApiKeyResponse400;

export type deleteProjectApiKeyResponse =
  deleteProjectApiKeyResponseComposite & {
    headers: Headers;
  };

export const getDeleteProjectApiKeyUrl = (projectId: string, keyId: string) => {
  return `/organization/projects/${projectId}/api_keys/${keyId}`;
};

export const deleteProjectApiKey = async (
  projectId: string,
  keyId: string,
  options?: RequestInit
): Promise<deleteProjectApiKeyResponse> => {
  const res = await fetch(getDeleteProjectApiKeyUrl(projectId, keyId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteProjectApiKeyResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteProjectApiKeyResponse;
};

/**
 * @summary Archives a project in the organization. Archived projects cannot be used or updated.
 */
export type archiveProjectResponse200 = {
  data: Project;
  status: 200;
};

export type archiveProjectResponseComposite = archiveProjectResponse200;

export type archiveProjectResponse = archiveProjectResponseComposite & {
  headers: Headers;
};

export const getArchiveProjectUrl = (projectId: string) => {
  return `/organization/projects/${projectId}/archive`;
};

export const archiveProject = async (
  projectId: string,
  options?: RequestInit
): Promise<archiveProjectResponse> => {
  const res = await fetch(getArchiveProjectUrl(projectId), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: archiveProjectResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as archiveProjectResponse;
};

/**
 * @summary Returns the rate limits per model for a project.
 */
export type listProjectRateLimitsResponse200 = {
  data: ProjectRateLimitListResponse;
  status: 200;
};

export type listProjectRateLimitsResponseComposite =
  listProjectRateLimitsResponse200;

export type listProjectRateLimitsResponse =
  listProjectRateLimitsResponseComposite & {
    headers: Headers;
  };

export const getListProjectRateLimitsUrl = (
  projectId: string,
  params?: ListProjectRateLimitsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/organization/projects/${projectId}/rate_limits?${stringifiedParams}`
    : `/organization/projects/${projectId}/rate_limits`;
};

export const listProjectRateLimits = async (
  projectId: string,
  params?: ListProjectRateLimitsParams,
  options?: RequestInit
): Promise<listProjectRateLimitsResponse> => {
  const res = await fetch(getListProjectRateLimitsUrl(projectId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listProjectRateLimitsResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listProjectRateLimitsResponse;
};

/**
 * @summary Updates a project rate limit.
 */
export type updateProjectRateLimitsResponse200 = {
  data: ProjectRateLimit;
  status: 200;
};

export type updateProjectRateLimitsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type updateProjectRateLimitsResponseComposite =
  | updateProjectRateLimitsResponse200
  | updateProjectRateLimitsResponse400;

export type updateProjectRateLimitsResponse =
  updateProjectRateLimitsResponseComposite & {
    headers: Headers;
  };

export const getUpdateProjectRateLimitsUrl = (
  projectId: string,
  rateLimitId: string
) => {
  return `/organization/projects/${projectId}/rate_limits/${rateLimitId}`;
};

export const updateProjectRateLimits = async (
  projectId: string,
  rateLimitId: string,
  projectRateLimitUpdateRequest: ProjectRateLimitUpdateRequest,
  options?: RequestInit
): Promise<updateProjectRateLimitsResponse> => {
  const res = await fetch(
    getUpdateProjectRateLimitsUrl(projectId, rateLimitId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(projectRateLimitUpdateRequest),
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: updateProjectRateLimitsResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateProjectRateLimitsResponse;
};

/**
 * @summary Returns a list of service accounts in the project.
 */
export type listProjectServiceAccountsResponse200 = {
  data: ProjectServiceAccountListResponse;
  status: 200;
};

export type listProjectServiceAccountsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type listProjectServiceAccountsResponseComposite =
  | listProjectServiceAccountsResponse200
  | listProjectServiceAccountsResponse400;

export type listProjectServiceAccountsResponse =
  listProjectServiceAccountsResponseComposite & {
    headers: Headers;
  };

export const getListProjectServiceAccountsUrl = (
  projectId: string,
  params?: ListProjectServiceAccountsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/organization/projects/${projectId}/service_accounts?${stringifiedParams}`
    : `/organization/projects/${projectId}/service_accounts`;
};

export const listProjectServiceAccounts = async (
  projectId: string,
  params?: ListProjectServiceAccountsParams,
  options?: RequestInit
): Promise<listProjectServiceAccountsResponse> => {
  const res = await fetch(getListProjectServiceAccountsUrl(projectId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listProjectServiceAccountsResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listProjectServiceAccountsResponse;
};

/**
 * @summary Creates a new service account in the project. This also returns an unredacted API key for the service account.
 */
export type createProjectServiceAccountResponse200 = {
  data: ProjectServiceAccountCreateResponse;
  status: 200;
};

export type createProjectServiceAccountResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type createProjectServiceAccountResponseComposite =
  | createProjectServiceAccountResponse200
  | createProjectServiceAccountResponse400;

export type createProjectServiceAccountResponse =
  createProjectServiceAccountResponseComposite & {
    headers: Headers;
  };

export const getCreateProjectServiceAccountUrl = (projectId: string) => {
  return `/organization/projects/${projectId}/service_accounts`;
};

export const createProjectServiceAccount = async (
  projectId: string,
  projectServiceAccountCreateRequest: ProjectServiceAccountCreateRequest,
  options?: RequestInit
): Promise<createProjectServiceAccountResponse> => {
  const res = await fetch(getCreateProjectServiceAccountUrl(projectId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectServiceAccountCreateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createProjectServiceAccountResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createProjectServiceAccountResponse;
};

/**
 * @summary Retrieves a service account in the project.
 */
export type retrieveProjectServiceAccountResponse200 = {
  data: ProjectServiceAccount;
  status: 200;
};

export type retrieveProjectServiceAccountResponseComposite =
  retrieveProjectServiceAccountResponse200;

export type retrieveProjectServiceAccountResponse =
  retrieveProjectServiceAccountResponseComposite & {
    headers: Headers;
  };

export const getRetrieveProjectServiceAccountUrl = (
  projectId: string,
  serviceAccountId: string
) => {
  return `/organization/projects/${projectId}/service_accounts/${serviceAccountId}`;
};

export const retrieveProjectServiceAccount = async (
  projectId: string,
  serviceAccountId: string,
  options?: RequestInit
): Promise<retrieveProjectServiceAccountResponse> => {
  const res = await fetch(
    getRetrieveProjectServiceAccountUrl(projectId, serviceAccountId),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveProjectServiceAccountResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveProjectServiceAccountResponse;
};

/**
 * @summary Deletes a service account from the project.
 */
export type deleteProjectServiceAccountResponse200 = {
  data: ProjectServiceAccountDeleteResponse;
  status: 200;
};

export type deleteProjectServiceAccountResponseComposite =
  deleteProjectServiceAccountResponse200;

export type deleteProjectServiceAccountResponse =
  deleteProjectServiceAccountResponseComposite & {
    headers: Headers;
  };

export const getDeleteProjectServiceAccountUrl = (
  projectId: string,
  serviceAccountId: string
) => {
  return `/organization/projects/${projectId}/service_accounts/${serviceAccountId}`;
};

export const deleteProjectServiceAccount = async (
  projectId: string,
  serviceAccountId: string,
  options?: RequestInit
): Promise<deleteProjectServiceAccountResponse> => {
  const res = await fetch(
    getDeleteProjectServiceAccountUrl(projectId, serviceAccountId),
    {
      ...options,
      method: 'DELETE',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteProjectServiceAccountResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteProjectServiceAccountResponse;
};

/**
 * @summary Returns a list of users in the project.
 */
export type listProjectUsersResponse200 = {
  data: ProjectUserListResponse;
  status: 200;
};

export type listProjectUsersResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type listProjectUsersResponseComposite =
  | listProjectUsersResponse200
  | listProjectUsersResponse400;

export type listProjectUsersResponse = listProjectUsersResponseComposite & {
  headers: Headers;
};

export const getListProjectUsersUrl = (
  projectId: string,
  params?: ListProjectUsersParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/organization/projects/${projectId}/users?${stringifiedParams}`
    : `/organization/projects/${projectId}/users`;
};

export const listProjectUsers = async (
  projectId: string,
  params?: ListProjectUsersParams,
  options?: RequestInit
): Promise<listProjectUsersResponse> => {
  const res = await fetch(getListProjectUsersUrl(projectId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listProjectUsersResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listProjectUsersResponse;
};

/**
 * @summary Adds a user to the project. Users must already be members of the organization to be added to a project.
 */
export type createProjectUserResponse200 = {
  data: ProjectUser;
  status: 200;
};

export type createProjectUserResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type createProjectUserResponseComposite =
  | createProjectUserResponse200
  | createProjectUserResponse400;

export type createProjectUserResponse = createProjectUserResponseComposite & {
  headers: Headers;
};

export const getCreateProjectUserUrl = (projectId: string) => {
  return `/organization/projects/${projectId}/users`;
};

export const createProjectUser = async (
  projectId: string,
  projectUserCreateRequest: ProjectUserCreateRequest,
  options?: RequestInit
): Promise<createProjectUserResponse> => {
  const res = await fetch(getCreateProjectUserUrl(projectId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectUserCreateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createProjectUserResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createProjectUserResponse;
};

/**
 * @summary Retrieves a user in the project.
 */
export type retrieveProjectUserResponse200 = {
  data: ProjectUser;
  status: 200;
};

export type retrieveProjectUserResponseComposite =
  retrieveProjectUserResponse200;

export type retrieveProjectUserResponse =
  retrieveProjectUserResponseComposite & {
    headers: Headers;
  };

export const getRetrieveProjectUserUrl = (
  projectId: string,
  userId: string
) => {
  return `/organization/projects/${projectId}/users/${userId}`;
};

export const retrieveProjectUser = async (
  projectId: string,
  userId: string,
  options?: RequestInit
): Promise<retrieveProjectUserResponse> => {
  const res = await fetch(getRetrieveProjectUserUrl(projectId, userId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveProjectUserResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveProjectUserResponse;
};

/**
 * @summary Modifies a user's role in the project.
 */
export type modifyProjectUserResponse200 = {
  data: ProjectUser;
  status: 200;
};

export type modifyProjectUserResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type modifyProjectUserResponseComposite =
  | modifyProjectUserResponse200
  | modifyProjectUserResponse400;

export type modifyProjectUserResponse = modifyProjectUserResponseComposite & {
  headers: Headers;
};

export const getModifyProjectUserUrl = (projectId: string, userId: string) => {
  return `/organization/projects/${projectId}/users/${userId}`;
};

export const modifyProjectUser = async (
  projectId: string,
  userId: string,
  projectUserUpdateRequest: ProjectUserUpdateRequest,
  options?: RequestInit
): Promise<modifyProjectUserResponse> => {
  const res = await fetch(getModifyProjectUserUrl(projectId, userId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectUserUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: modifyProjectUserResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as modifyProjectUserResponse;
};

/**
 * @summary Deletes a user from the project.
 */
export type deleteProjectUserResponse200 = {
  data: ProjectUserDeleteResponse;
  status: 200;
};

export type deleteProjectUserResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type deleteProjectUserResponseComposite =
  | deleteProjectUserResponse200
  | deleteProjectUserResponse400;

export type deleteProjectUserResponse = deleteProjectUserResponseComposite & {
  headers: Headers;
};

export const getDeleteProjectUserUrl = (projectId: string, userId: string) => {
  return `/organization/projects/${projectId}/users/${userId}`;
};

export const deleteProjectUser = async (
  projectId: string,
  userId: string,
  options?: RequestInit
): Promise<deleteProjectUserResponse> => {
  const res = await fetch(getDeleteProjectUserUrl(projectId, userId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteProjectUserResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteProjectUserResponse;
};
