/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type {
  BlockUsers,
  DeleteCustomerRequest,
  EndUserInfoCustomerInfoGetParams,
  HTTPValidationError,
  LiteLLMEndUserTable,
  NewCustomerRequest,
  UpdateCustomerRequest,
} from '.././models';

/**
 * [BETA] Reject calls with this end-user id

Parameters:
- user_ids (List[str], required): The unique `user_id`s for the users to block

    (any /chat/completion call with this user={end-user-id} param, will be rejected.)

    ```
    curl -X POST "http://0.0.0.0:8000/user/block"
    -H "Authorization: Bearer sk-1234"
    -d '{
    "user_ids": [<user_id>, ...]
    }'
    ```
 * @summary Block User
 */
export type blockUserCustomerBlockPostResponse200 = {
  data: unknown;
  status: 200;
};

export type blockUserCustomerBlockPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type blockUserCustomerBlockPostResponseComposite =
  | blockUserCustomerBlockPostResponse200
  | blockUserCustomerBlockPostResponse422;

export type blockUserCustomerBlockPostResponse =
  blockUserCustomerBlockPostResponseComposite & {
    headers: Headers;
  };

export const getBlockUserCustomerBlockPostUrl = () => {
  return `/customer/block`;
};

export const blockUserCustomerBlockPost = async (
  blockUsers: BlockUsers,
  options?: RequestInit
): Promise<blockUserCustomerBlockPostResponse> => {
  const res = await fetch(getBlockUserCustomerBlockPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(blockUsers),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: blockUserCustomerBlockPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as blockUserCustomerBlockPostResponse;
};

/**
 * [BETA] Unblock calls with this user id

Example
```
curl -X POST "http://0.0.0.0:8000/user/unblock"
-H "Authorization: Bearer sk-1234"
-d '{
"user_ids": [<user_id>, ...]
}'
```
 * @summary Unblock User
 */
export type unblockUserCustomerUnblockPostResponse200 = {
  data: unknown;
  status: 200;
};

export type unblockUserCustomerUnblockPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type unblockUserCustomerUnblockPostResponseComposite =
  | unblockUserCustomerUnblockPostResponse200
  | unblockUserCustomerUnblockPostResponse422;

export type unblockUserCustomerUnblockPostResponse =
  unblockUserCustomerUnblockPostResponseComposite & {
    headers: Headers;
  };

export const getUnblockUserCustomerUnblockPostUrl = () => {
  return `/customer/unblock`;
};

export const unblockUserCustomerUnblockPost = async (
  blockUsers: BlockUsers,
  options?: RequestInit
): Promise<unblockUserCustomerUnblockPostResponse> => {
  const res = await fetch(getUnblockUserCustomerUnblockPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(blockUsers),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: unblockUserCustomerUnblockPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as unblockUserCustomerUnblockPostResponse;
};

/**
 * Allow creating a new Customer 


Parameters:
- user_id: str - The unique identifier for the user.
- alias: Optional[str] - A human-friendly alias for the user.
- blocked: bool - Flag to allow or disallow requests for this end-user. Default is False.
- max_budget: Optional[float] - The maximum budget allocated to the user. Either 'max_budget' or 'budget_id' should be provided, not both.
- budget_id: Optional[str] - The identifier for an existing budget allocated to the user. Either 'max_budget' or 'budget_id' should be provided, not both.
- allowed_model_region: Optional[Union[Literal["eu"], Literal["us"]]] - Require all user requests to use models in this specific region.
- default_model: Optional[str] - If no equivalent model in the allowed region, default all requests to this model.
- metadata: Optional[dict] = Metadata for customer, store information for customer. Example metadata = {"data_training_opt_out": True}
- budget_duration: Optional[str] - Budget is reset at the end of specified duration. If not set, budget is never reset. You can set duration as seconds ("30s"), minutes ("30m"), hours ("30h"), days ("30d").
- tpm_limit: Optional[int] - [Not Implemented Yet] Specify tpm limit for a given customer (Tokens per minute)
- rpm_limit: Optional[int] - [Not Implemented Yet] Specify rpm limit for a given customer (Requests per minute)
- model_max_budget: Optional[dict] - [Not Implemented Yet] Specify max budget for a given model. Example: {"openai/gpt-4o-mini": {"max_budget": 100.0, "budget_duration": "1d"}}
- max_parallel_requests: Optional[int] - [Not Implemented Yet] Specify max parallel requests for a given customer.
- soft_budget: Optional[float] - [Not Implemented Yet] Get alerts when customer crosses given budget, doesn't block requests.
- spend: Optional[float] - Specify initial spend for a given customer.
- budget_reset_at: Optional[str] - Specify the date and time when the budget should be reset.


- Allow specifying allowed regions 
- Allow specifying default model

Example curl:
```
curl --location 'http://0.0.0.0:4000/customer/new'         --header 'Authorization: Bearer sk-1234'         --header 'Content-Type: application/json'         --data '{
        "user_id" : "ishaan-jaff-3",
        "allowed_region": "eu",
        "budget_id": "free_tier",
        "default_model": "azure/gpt-3.5-turbo-eu" <- all calls from this user, use this model? 
    }'

    # return end-user object
```

NOTE: This used to be called `/end_user/new`, we will still be maintaining compatibility for /end_user/XXX for these endpoints
 * @summary New End User
 */
export type newEndUserCustomerNewPostResponse200 = {
  data: unknown;
  status: 200;
};

export type newEndUserCustomerNewPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type newEndUserCustomerNewPostResponseComposite =
  | newEndUserCustomerNewPostResponse200
  | newEndUserCustomerNewPostResponse422;

export type newEndUserCustomerNewPostResponse =
  newEndUserCustomerNewPostResponseComposite & {
    headers: Headers;
  };

export const getNewEndUserCustomerNewPostUrl = () => {
  return `/customer/new`;
};

export const newEndUserCustomerNewPost = async (
  newCustomerRequest: NewCustomerRequest,
  options?: RequestInit
): Promise<newEndUserCustomerNewPostResponse> => {
  const res = await fetch(getNewEndUserCustomerNewPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(newCustomerRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: newEndUserCustomerNewPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as newEndUserCustomerNewPostResponse;
};

/**
 * Get information about an end-user. An `end_user` is a customer (external user) of the proxy.

Parameters:
- end_user_id (str, required): The unique identifier for the end-user

Example curl:
```
curl -X GET 'http://localhost:4000/customer/info?end_user_id=test-litellm-user-4'         -H 'Authorization: Bearer sk-1234'
```
 * @summary End User Info
 */
export type endUserInfoCustomerInfoGetResponse200 = {
  data: LiteLLMEndUserTable;
  status: 200;
};

export type endUserInfoCustomerInfoGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type endUserInfoCustomerInfoGetResponseComposite =
  | endUserInfoCustomerInfoGetResponse200
  | endUserInfoCustomerInfoGetResponse422;

export type endUserInfoCustomerInfoGetResponse =
  endUserInfoCustomerInfoGetResponseComposite & {
    headers: Headers;
  };

export const getEndUserInfoCustomerInfoGetUrl = (
  params: EndUserInfoCustomerInfoGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/customer/info?${stringifiedParams}`
    : `/customer/info`;
};

export const endUserInfoCustomerInfoGet = async (
  params: EndUserInfoCustomerInfoGetParams,
  options?: RequestInit
): Promise<endUserInfoCustomerInfoGetResponse> => {
  const res = await fetch(getEndUserInfoCustomerInfoGetUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: endUserInfoCustomerInfoGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as endUserInfoCustomerInfoGetResponse;
};

/**
 * Example curl 

Parameters:
- user_id: str
- alias: Optional[str] = None  # human-friendly alias
- blocked: bool = False  # allow/disallow requests for this end-user
- max_budget: Optional[float] = None
- budget_id: Optional[str] = None  # give either a budget_id or max_budget
- allowed_model_region: Optional[AllowedModelRegion] = (
    None  # require all user requests to use models in this specific region
)
- default_model: Optional[str] = (
    None  # if no equivalent model in allowed region - default all requests to this model
)

Example curl:
```
curl --location 'http://0.0.0.0:4000/customer/update'     --header 'Authorization: Bearer sk-1234'     --header 'Content-Type: application/json'     --data '{
    "user_id": "test-litellm-user-4",
    "budget_id": "paid_tier"
}'

See below for all params 
```
 * @summary Update End User
 */
export type updateEndUserCustomerUpdatePostResponse200 = {
  data: unknown;
  status: 200;
};

export type updateEndUserCustomerUpdatePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateEndUserCustomerUpdatePostResponseComposite =
  | updateEndUserCustomerUpdatePostResponse200
  | updateEndUserCustomerUpdatePostResponse422;

export type updateEndUserCustomerUpdatePostResponse =
  updateEndUserCustomerUpdatePostResponseComposite & {
    headers: Headers;
  };

export const getUpdateEndUserCustomerUpdatePostUrl = () => {
  return `/customer/update`;
};

export const updateEndUserCustomerUpdatePost = async (
  updateCustomerRequest: UpdateCustomerRequest,
  options?: RequestInit
): Promise<updateEndUserCustomerUpdatePostResponse> => {
  const res = await fetch(getUpdateEndUserCustomerUpdatePostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCustomerRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: updateEndUserCustomerUpdatePostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateEndUserCustomerUpdatePostResponse;
};

/**
 * Delete multiple end-users.

Parameters:
- user_ids (List[str], required): The unique `user_id`s for the users to delete

Example curl:
```
curl --location 'http://0.0.0.0:4000/customer/delete'         --header 'Authorization: Bearer sk-1234'         --header 'Content-Type: application/json'         --data '{
        "user_ids" :["ishaan-jaff-5"]
}'

See below for all params 
```
 * @summary Delete End User
 */
export type deleteEndUserCustomerDeletePostResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteEndUserCustomerDeletePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteEndUserCustomerDeletePostResponseComposite =
  | deleteEndUserCustomerDeletePostResponse200
  | deleteEndUserCustomerDeletePostResponse422;

export type deleteEndUserCustomerDeletePostResponse =
  deleteEndUserCustomerDeletePostResponseComposite & {
    headers: Headers;
  };

export const getDeleteEndUserCustomerDeletePostUrl = () => {
  return `/customer/delete`;
};

export const deleteEndUserCustomerDeletePost = async (
  deleteCustomerRequest: DeleteCustomerRequest,
  options?: RequestInit
): Promise<deleteEndUserCustomerDeletePostResponse> => {
  const res = await fetch(getDeleteEndUserCustomerDeletePostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteCustomerRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteEndUserCustomerDeletePostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteEndUserCustomerDeletePostResponse;
};

/**
 * [Admin-only] List all available customers

Example curl:
```
curl --location --request GET 'http://0.0.0.0:4000/customer/list'         --header 'Authorization: Bearer sk-1234'
```
 * @summary List End User
 */
export type listEndUserCustomerListGetResponse200 = {
  data: LiteLLMEndUserTable[];
  status: 200;
};

export type listEndUserCustomerListGetResponseComposite =
  listEndUserCustomerListGetResponse200;

export type listEndUserCustomerListGetResponse =
  listEndUserCustomerListGetResponseComposite & {
    headers: Headers;
  };

export const getListEndUserCustomerListGetUrl = () => {
  return `/customer/list`;
};

export const listEndUserCustomerListGet = async (
  options?: RequestInit
): Promise<listEndUserCustomerListGetResponse> => {
  const res = await fetch(getListEndUserCustomerListGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listEndUserCustomerListGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listEndUserCustomerListGetResponse;
};
