/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type {
  CancelBatchBatchesBatchIdCancelPostParams,
  CancelBatchV1BatchesBatchIdCancelPostParams,
  CreateBatchBatchesPostParams,
  CreateBatchV1BatchesPostParams,
  HTTPValidationError,
  ListBatchesBatchesGetParams,
  ListBatchesProviderV1BatchesGetParams,
  ListBatchesV1BatchesGetParams,
  RetrieveBatchBatchesBatchIdGetParams,
  RetrieveBatchV1BatchesBatchIdGetParams,
} from '.././schemas';

/**
 * Create large batches of API requests for asynchronous processing.
This is the equivalent of POST https://api.openai.com/v1/batch
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch

Example Curl
```
curl http://localhost:4000/v1/batches         -H "Authorization: Bearer sk-1234"         -H "Content-Type: application/json"         -d '{
        "input_file_id": "file-abc123",
        "endpoint": "/v1/chat/completions",
        "completion_window": "24h"
}'
```
 * @summary Create Batch
 */
export type createBatchBatchesPostResponse200 = {
  data: unknown;
  status: 200;
};

export type createBatchBatchesPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createBatchBatchesPostResponseComposite =
  | createBatchBatchesPostResponse200
  | createBatchBatchesPostResponse422;

export type createBatchBatchesPostResponse =
  createBatchBatchesPostResponseComposite & {
    headers: Headers;
  };

export const getCreateBatchBatchesPostUrl = (
  params?: CreateBatchBatchesPostParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/batches?${stringifiedParams}`
    : `/batches`;
};

export const createBatchBatchesPost = async (
  params?: CreateBatchBatchesPostParams,
  options?: RequestInit
): Promise<createBatchBatchesPostResponse> => {
  const res = await fetch(getCreateBatchBatchesPostUrl(params), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createBatchBatchesPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createBatchBatchesPostResponse;
};

/**
 * Lists 
This is the equivalent of GET https://api.openai.com/v1/batches/
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/list

Example Curl
```
curl http://localhost:4000/v1/batches?limit=2     -H "Authorization: Bearer sk-1234"     -H "Content-Type: application/json" 
```
 * @summary List Batches
 */
export type listBatchesBatchesGetResponse200 = {
  data: unknown;
  status: 200;
};

export type listBatchesBatchesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listBatchesBatchesGetResponseComposite =
  | listBatchesBatchesGetResponse200
  | listBatchesBatchesGetResponse422;

export type listBatchesBatchesGetResponse =
  listBatchesBatchesGetResponseComposite & {
    headers: Headers;
  };

export const getListBatchesBatchesGetUrl = (
  params?: ListBatchesBatchesGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/batches?${stringifiedParams}`
    : `/batches`;
};

export const listBatchesBatchesGet = async (
  params?: ListBatchesBatchesGetParams,
  options?: RequestInit
): Promise<listBatchesBatchesGetResponse> => {
  const res = await fetch(getListBatchesBatchesGetUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listBatchesBatchesGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listBatchesBatchesGetResponse;
};

/**
 * Create large batches of API requests for asynchronous processing.
This is the equivalent of POST https://api.openai.com/v1/batch
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch

Example Curl
```
curl http://localhost:4000/v1/batches         -H "Authorization: Bearer sk-1234"         -H "Content-Type: application/json"         -d '{
        "input_file_id": "file-abc123",
        "endpoint": "/v1/chat/completions",
        "completion_window": "24h"
}'
```
 * @summary Create Batch
 */
export type createBatchV1BatchesPostResponse200 = {
  data: unknown;
  status: 200;
};

export type createBatchV1BatchesPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createBatchV1BatchesPostResponseComposite =
  | createBatchV1BatchesPostResponse200
  | createBatchV1BatchesPostResponse422;

export type createBatchV1BatchesPostResponse =
  createBatchV1BatchesPostResponseComposite & {
    headers: Headers;
  };

export const getCreateBatchV1BatchesPostUrl = (
  params?: CreateBatchV1BatchesPostParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/batches?${stringifiedParams}`
    : `/v1/batches`;
};

export const createBatchV1BatchesPost = async (
  params?: CreateBatchV1BatchesPostParams,
  options?: RequestInit
): Promise<createBatchV1BatchesPostResponse> => {
  const res = await fetch(getCreateBatchV1BatchesPostUrl(params), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createBatchV1BatchesPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createBatchV1BatchesPostResponse;
};

/**
 * Lists 
This is the equivalent of GET https://api.openai.com/v1/batches/
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/list

Example Curl
```
curl http://localhost:4000/v1/batches?limit=2     -H "Authorization: Bearer sk-1234"     -H "Content-Type: application/json" 
```
 * @summary List Batches
 */
export type listBatchesV1BatchesGetResponse200 = {
  data: unknown;
  status: 200;
};

export type listBatchesV1BatchesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listBatchesV1BatchesGetResponseComposite =
  | listBatchesV1BatchesGetResponse200
  | listBatchesV1BatchesGetResponse422;

export type listBatchesV1BatchesGetResponse =
  listBatchesV1BatchesGetResponseComposite & {
    headers: Headers;
  };

export const getListBatchesV1BatchesGetUrl = (
  params?: ListBatchesV1BatchesGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/batches?${stringifiedParams}`
    : `/v1/batches`;
};

export const listBatchesV1BatchesGet = async (
  params?: ListBatchesV1BatchesGetParams,
  options?: RequestInit
): Promise<listBatchesV1BatchesGetResponse> => {
  const res = await fetch(getListBatchesV1BatchesGetUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listBatchesV1BatchesGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listBatchesV1BatchesGetResponse;
};

/**
 * Create large batches of API requests for asynchronous processing.
This is the equivalent of POST https://api.openai.com/v1/batch
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch

Example Curl
```
curl http://localhost:4000/v1/batches         -H "Authorization: Bearer sk-1234"         -H "Content-Type: application/json"         -d '{
        "input_file_id": "file-abc123",
        "endpoint": "/v1/chat/completions",
        "completion_window": "24h"
}'
```
 * @summary Create Batch
 */
export type createBatchProviderV1BatchesPostResponse200 = {
  data: unknown;
  status: 200;
};

export type createBatchProviderV1BatchesPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createBatchProviderV1BatchesPostResponseComposite =
  | createBatchProviderV1BatchesPostResponse200
  | createBatchProviderV1BatchesPostResponse422;

export type createBatchProviderV1BatchesPostResponse =
  createBatchProviderV1BatchesPostResponseComposite & {
    headers: Headers;
  };

export const getCreateBatchProviderV1BatchesPostUrl = (
  provider: string | null
) => {
  return `/${provider}/v1/batches`;
};

export const createBatchProviderV1BatchesPost = async (
  provider: string | null,
  options?: RequestInit
): Promise<createBatchProviderV1BatchesPostResponse> => {
  const res = await fetch(getCreateBatchProviderV1BatchesPostUrl(provider), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createBatchProviderV1BatchesPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createBatchProviderV1BatchesPostResponse;
};

/**
 * Lists 
This is the equivalent of GET https://api.openai.com/v1/batches/
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/list

Example Curl
```
curl http://localhost:4000/v1/batches?limit=2     -H "Authorization: Bearer sk-1234"     -H "Content-Type: application/json" 
```
 * @summary List Batches
 */
export type listBatchesProviderV1BatchesGetResponse200 = {
  data: unknown;
  status: 200;
};

export type listBatchesProviderV1BatchesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listBatchesProviderV1BatchesGetResponseComposite =
  | listBatchesProviderV1BatchesGetResponse200
  | listBatchesProviderV1BatchesGetResponse422;

export type listBatchesProviderV1BatchesGetResponse =
  listBatchesProviderV1BatchesGetResponseComposite & {
    headers: Headers;
  };

export const getListBatchesProviderV1BatchesGetUrl = (
  provider: string | null,
  params?: ListBatchesProviderV1BatchesGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/${provider}/v1/batches?${stringifiedParams}`
    : `/${provider}/v1/batches`;
};

export const listBatchesProviderV1BatchesGet = async (
  provider: string | null,
  params?: ListBatchesProviderV1BatchesGetParams,
  options?: RequestInit
): Promise<listBatchesProviderV1BatchesGetResponse> => {
  const res = await fetch(
    getListBatchesProviderV1BatchesGetUrl(provider, params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listBatchesProviderV1BatchesGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listBatchesProviderV1BatchesGetResponse;
};

/**
 * Retrieves a batch.
This is the equivalent of GET https://api.openai.com/v1/batches/{batch_id}
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/retrieve

Example Curl
```
curl http://localhost:4000/v1/batches/batch_abc123     -H "Authorization: Bearer sk-1234"     -H "Content-Type: application/json" 
```
 * @summary Retrieve Batch
 */
export type retrieveBatchBatchesBatchIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type retrieveBatchBatchesBatchIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type retrieveBatchBatchesBatchIdGetResponseComposite =
  | retrieveBatchBatchesBatchIdGetResponse200
  | retrieveBatchBatchesBatchIdGetResponse422;

export type retrieveBatchBatchesBatchIdGetResponse =
  retrieveBatchBatchesBatchIdGetResponseComposite & {
    headers: Headers;
  };

export const getRetrieveBatchBatchesBatchIdGetUrl = (
  batchId: string,
  params?: RetrieveBatchBatchesBatchIdGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/batches/${batchId}?${stringifiedParams}`
    : `/batches/${batchId}`;
};

export const retrieveBatchBatchesBatchIdGet = async (
  batchId: string,
  params?: RetrieveBatchBatchesBatchIdGetParams,
  options?: RequestInit
): Promise<retrieveBatchBatchesBatchIdGetResponse> => {
  const res = await fetch(
    getRetrieveBatchBatchesBatchIdGetUrl(batchId, params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveBatchBatchesBatchIdGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveBatchBatchesBatchIdGetResponse;
};

/**
 * Retrieves a batch.
This is the equivalent of GET https://api.openai.com/v1/batches/{batch_id}
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/retrieve

Example Curl
```
curl http://localhost:4000/v1/batches/batch_abc123     -H "Authorization: Bearer sk-1234"     -H "Content-Type: application/json" 
```
 * @summary Retrieve Batch
 */
export type retrieveBatchV1BatchesBatchIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type retrieveBatchV1BatchesBatchIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type retrieveBatchV1BatchesBatchIdGetResponseComposite =
  | retrieveBatchV1BatchesBatchIdGetResponse200
  | retrieveBatchV1BatchesBatchIdGetResponse422;

export type retrieveBatchV1BatchesBatchIdGetResponse =
  retrieveBatchV1BatchesBatchIdGetResponseComposite & {
    headers: Headers;
  };

export const getRetrieveBatchV1BatchesBatchIdGetUrl = (
  batchId: string,
  params?: RetrieveBatchV1BatchesBatchIdGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/batches/${batchId}?${stringifiedParams}`
    : `/v1/batches/${batchId}`;
};

export const retrieveBatchV1BatchesBatchIdGet = async (
  batchId: string,
  params?: RetrieveBatchV1BatchesBatchIdGetParams,
  options?: RequestInit
): Promise<retrieveBatchV1BatchesBatchIdGetResponse> => {
  const res = await fetch(
    getRetrieveBatchV1BatchesBatchIdGetUrl(batchId, params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveBatchV1BatchesBatchIdGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveBatchV1BatchesBatchIdGetResponse;
};

/**
 * Retrieves a batch.
This is the equivalent of GET https://api.openai.com/v1/batches/{batch_id}
Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/retrieve

Example Curl
```
curl http://localhost:4000/v1/batches/batch_abc123     -H "Authorization: Bearer sk-1234"     -H "Content-Type: application/json" 
```
 * @summary Retrieve Batch
 */
export type retrieveBatchProviderV1BatchesBatchIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type retrieveBatchProviderV1BatchesBatchIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type retrieveBatchProviderV1BatchesBatchIdGetResponseComposite =
  | retrieveBatchProviderV1BatchesBatchIdGetResponse200
  | retrieveBatchProviderV1BatchesBatchIdGetResponse422;

export type retrieveBatchProviderV1BatchesBatchIdGetResponse =
  retrieveBatchProviderV1BatchesBatchIdGetResponseComposite & {
    headers: Headers;
  };

export const getRetrieveBatchProviderV1BatchesBatchIdGetUrl = (
  provider: string | null,
  batchId: string
) => {
  return `/${provider}/v1/batches/${batchId}`;
};

export const retrieveBatchProviderV1BatchesBatchIdGet = async (
  provider: string | null,
  batchId: string,
  options?: RequestInit
): Promise<retrieveBatchProviderV1BatchesBatchIdGetResponse> => {
  const res = await fetch(
    getRetrieveBatchProviderV1BatchesBatchIdGetUrl(provider, batchId),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveBatchProviderV1BatchesBatchIdGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveBatchProviderV1BatchesBatchIdGetResponse;
};

/**
 * Cancel a batch.
This is the equivalent of POST https://api.openai.com/v1/batches/{batch_id}/cancel

Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/cancel

Example Curl
```
curl http://localhost:4000/v1/batches/batch_abc123/cancel         -H "Authorization: Bearer sk-1234"         -H "Content-Type: application/json"         -X POST

```
 * @summary Cancel Batch
 */
export type cancelBatchBatchesBatchIdCancelPostResponse200 = {
  data: unknown;
  status: 200;
};

export type cancelBatchBatchesBatchIdCancelPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type cancelBatchBatchesBatchIdCancelPostResponseComposite =
  | cancelBatchBatchesBatchIdCancelPostResponse200
  | cancelBatchBatchesBatchIdCancelPostResponse422;

export type cancelBatchBatchesBatchIdCancelPostResponse =
  cancelBatchBatchesBatchIdCancelPostResponseComposite & {
    headers: Headers;
  };

export const getCancelBatchBatchesBatchIdCancelPostUrl = (
  batchId: string,
  params?: CancelBatchBatchesBatchIdCancelPostParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/batches/${batchId}/cancel?${stringifiedParams}`
    : `/batches/${batchId}/cancel`;
};

export const cancelBatchBatchesBatchIdCancelPost = async (
  batchId: string,
  params?: CancelBatchBatchesBatchIdCancelPostParams,
  options?: RequestInit
): Promise<cancelBatchBatchesBatchIdCancelPostResponse> => {
  const res = await fetch(
    getCancelBatchBatchesBatchIdCancelPostUrl(batchId, params),
    {
      ...options,
      method: 'POST',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cancelBatchBatchesBatchIdCancelPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cancelBatchBatchesBatchIdCancelPostResponse;
};

/**
 * Cancel a batch.
This is the equivalent of POST https://api.openai.com/v1/batches/{batch_id}/cancel

Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/cancel

Example Curl
```
curl http://localhost:4000/v1/batches/batch_abc123/cancel         -H "Authorization: Bearer sk-1234"         -H "Content-Type: application/json"         -X POST

```
 * @summary Cancel Batch
 */
export type cancelBatchV1BatchesBatchIdCancelPostResponse200 = {
  data: unknown;
  status: 200;
};

export type cancelBatchV1BatchesBatchIdCancelPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type cancelBatchV1BatchesBatchIdCancelPostResponseComposite =
  | cancelBatchV1BatchesBatchIdCancelPostResponse200
  | cancelBatchV1BatchesBatchIdCancelPostResponse422;

export type cancelBatchV1BatchesBatchIdCancelPostResponse =
  cancelBatchV1BatchesBatchIdCancelPostResponseComposite & {
    headers: Headers;
  };

export const getCancelBatchV1BatchesBatchIdCancelPostUrl = (
  batchId: string,
  params?: CancelBatchV1BatchesBatchIdCancelPostParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/batches/${batchId}/cancel?${stringifiedParams}`
    : `/v1/batches/${batchId}/cancel`;
};

export const cancelBatchV1BatchesBatchIdCancelPost = async (
  batchId: string,
  params?: CancelBatchV1BatchesBatchIdCancelPostParams,
  options?: RequestInit
): Promise<cancelBatchV1BatchesBatchIdCancelPostResponse> => {
  const res = await fetch(
    getCancelBatchV1BatchesBatchIdCancelPostUrl(batchId, params),
    {
      ...options,
      method: 'POST',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cancelBatchV1BatchesBatchIdCancelPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cancelBatchV1BatchesBatchIdCancelPostResponse;
};

/**
 * Cancel a batch.
This is the equivalent of POST https://api.openai.com/v1/batches/{batch_id}/cancel

Supports Identical Params as: https://platform.openai.com/docs/api-reference/batch/cancel

Example Curl
```
curl http://localhost:4000/v1/batches/batch_abc123/cancel         -H "Authorization: Bearer sk-1234"         -H "Content-Type: application/json"         -X POST

```
 * @summary Cancel Batch
 */
export type cancelBatchProviderV1BatchesBatchIdCancelPostResponse200 = {
  data: unknown;
  status: 200;
};

export type cancelBatchProviderV1BatchesBatchIdCancelPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type cancelBatchProviderV1BatchesBatchIdCancelPostResponseComposite =
  | cancelBatchProviderV1BatchesBatchIdCancelPostResponse200
  | cancelBatchProviderV1BatchesBatchIdCancelPostResponse422;

export type cancelBatchProviderV1BatchesBatchIdCancelPostResponse =
  cancelBatchProviderV1BatchesBatchIdCancelPostResponseComposite & {
    headers: Headers;
  };

export const getCancelBatchProviderV1BatchesBatchIdCancelPostUrl = (
  provider: string | null,
  batchId: string
) => {
  return `/${provider}/v1/batches/${batchId}/cancel`;
};

export const cancelBatchProviderV1BatchesBatchIdCancelPost = async (
  provider: string | null,
  batchId: string,
  options?: RequestInit
): Promise<cancelBatchProviderV1BatchesBatchIdCancelPostResponse> => {
  const res = await fetch(
    getCancelBatchProviderV1BatchesBatchIdCancelPostUrl(provider, batchId),
    {
      ...options,
      method: 'POST',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cancelBatchProviderV1BatchesBatchIdCancelPostResponse['data'] =
    body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cancelBatchProviderV1BatchesBatchIdCancelPostResponse;
};
