/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { HTTPValidationError } from '.././models';

/**
 * [Docs](https://docs.litellm.ai/docs/anthropic_completion)
 * @summary Anthropic Proxy Route
 */
export type anthropicProxyRouteAnthropicEndpointGetResponse200 = {
  data: unknown;
  status: 200;
};

export type anthropicProxyRouteAnthropicEndpointGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type anthropicProxyRouteAnthropicEndpointGetResponseComposite =
  | anthropicProxyRouteAnthropicEndpointGetResponse200
  | anthropicProxyRouteAnthropicEndpointGetResponse422;

export type anthropicProxyRouteAnthropicEndpointGetResponse =
  anthropicProxyRouteAnthropicEndpointGetResponseComposite & {
    headers: Headers;
  };

export const getAnthropicProxyRouteAnthropicEndpointGetUrl = (
  endpoint: string
) => {
  return `/anthropic/${endpoint}`;
};

export const anthropicProxyRouteAnthropicEndpointGet = async (
  endpoint: string,
  options?: RequestInit
): Promise<anthropicProxyRouteAnthropicEndpointGetResponse> => {
  const res = await fetch(
    getAnthropicProxyRouteAnthropicEndpointGetUrl(endpoint),
    {
      ...options,
      method: 'PUT',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: anthropicProxyRouteAnthropicEndpointGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as anthropicProxyRouteAnthropicEndpointGetResponse;
};
