/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type {
  Invite,
  InviteDeleteResponse,
  InviteListResponse,
  InviteRequest,
  ListInvitesParams,
} from '.././schemas';

/**
 * @summary Returns a list of invites in the organization.
 */
export type listInvitesResponse200 = {
  data: InviteListResponse;
  status: 200;
};

export type listInvitesResponseComposite = listInvitesResponse200;

export type listInvitesResponse = listInvitesResponseComposite & {
  headers: Headers;
};

export const getListInvitesUrl = (params?: ListInvitesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/organization/invites?${stringifiedParams}`
    : `/organization/invites`;
};

export const listInvites = async (
  params?: ListInvitesParams,
  options?: RequestInit
): Promise<listInvitesResponse> => {
  const res = await fetch(getListInvitesUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listInvitesResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listInvitesResponse;
};

/**
 * @summary Create an invite for a user to the organization. The invite must be accepted by the user before they have access to the organization.
 */
export type inviteUserResponse200 = {
  data: Invite;
  status: 200;
};

export type inviteUserResponseComposite = inviteUserResponse200;

export type inviteUserResponse = inviteUserResponseComposite & {
  headers: Headers;
};

export const getInviteUserUrl = () => {
  return `/organization/invites`;
};

export const inviteUser = async (
  inviteRequest: InviteRequest,
  options?: RequestInit
): Promise<inviteUserResponse> => {
  const res = await fetch(getInviteUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(inviteRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: inviteUserResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as inviteUserResponse;
};

/**
 * @summary Retrieves an invite.
 */
export type retrieveInviteResponse200 = {
  data: Invite;
  status: 200;
};

export type retrieveInviteResponseComposite = retrieveInviteResponse200;

export type retrieveInviteResponse = retrieveInviteResponseComposite & {
  headers: Headers;
};

export const getRetrieveInviteUrl = (inviteId: string) => {
  return `/organization/invites/${inviteId}`;
};

export const retrieveInvite = async (
  inviteId: string,
  options?: RequestInit
): Promise<retrieveInviteResponse> => {
  const res = await fetch(getRetrieveInviteUrl(inviteId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: retrieveInviteResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as retrieveInviteResponse;
};

/**
 * @summary Delete an invite. If the invite has already been accepted, it cannot be deleted.
 */
export type deleteInviteResponse200 = {
  data: InviteDeleteResponse;
  status: 200;
};

export type deleteInviteResponseComposite = deleteInviteResponse200;

export type deleteInviteResponse = deleteInviteResponseComposite & {
  headers: Headers;
};

export const getDeleteInviteUrl = (inviteId: string) => {
  return `/organization/invites/${inviteId}`;
};

export const deleteInvite = async (
  inviteId: string,
  options?: RequestInit
): Promise<deleteInviteResponse> => {
  const res = await fetch(getDeleteInviteUrl(inviteId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteInviteResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteInviteResponse;
};
