/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type {
  HTTPValidationError,
  ListVectorStoresVectorStoreListGetParams,
  LiteLLMManagedVectorStore,
  LiteLLMManagedVectorStoreListResponse,
  VectorStoreDeleteRequest,
  VectorStoreInfoRequest,
  VectorStoreUpdateRequest,
} from '.././schemas';

/**
 * Create a new vector store.

Parameters:
- vector_store_id: str - Unique identifier for the vector store
- custom_llm_provider: str - Provider of the vector store
- vector_store_name: Optional[str] - Name of the vector store
- vector_store_description: Optional[str] - Description of the vector store
- vector_store_metadata: Optional[Dict] - Additional metadata for the vector store
 * @summary New Vector Store
 */
export type newVectorStoreVectorStoreNewPostResponse200 = {
  data: unknown;
  status: 200;
};

export type newVectorStoreVectorStoreNewPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type newVectorStoreVectorStoreNewPostResponseComposite =
  | newVectorStoreVectorStoreNewPostResponse200
  | newVectorStoreVectorStoreNewPostResponse422;

export type newVectorStoreVectorStoreNewPostResponse =
  newVectorStoreVectorStoreNewPostResponseComposite & {
    headers: Headers;
  };

export const getNewVectorStoreVectorStoreNewPostUrl = () => {
  return `/vector_store/new`;
};

export const newVectorStoreVectorStoreNewPost = async (
  liteLLMManagedVectorStore: LiteLLMManagedVectorStore,
  options?: RequestInit
): Promise<newVectorStoreVectorStoreNewPostResponse> => {
  const res = await fetch(getNewVectorStoreVectorStoreNewPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(liteLLMManagedVectorStore),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: newVectorStoreVectorStoreNewPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as newVectorStoreVectorStoreNewPostResponse;
};

/**
 * List all available vector stores with optional filtering and pagination.
Combines both in-memory vector stores and those stored in the database.

Parameters:
- page: int - Page number for pagination (default: 1)
- page_size: int - Number of items per page (default: 100)
 * @summary List Vector Stores
 */
export type listVectorStoresVectorStoreListGetResponse200 = {
  data: LiteLLMManagedVectorStoreListResponse;
  status: 200;
};

export type listVectorStoresVectorStoreListGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listVectorStoresVectorStoreListGetResponseComposite =
  | listVectorStoresVectorStoreListGetResponse200
  | listVectorStoresVectorStoreListGetResponse422;

export type listVectorStoresVectorStoreListGetResponse =
  listVectorStoresVectorStoreListGetResponseComposite & {
    headers: Headers;
  };

export const getListVectorStoresVectorStoreListGetUrl = (
  params?: ListVectorStoresVectorStoreListGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/vector_store/list?${stringifiedParams}`
    : `/vector_store/list`;
};

export const listVectorStoresVectorStoreListGet = async (
  params?: ListVectorStoresVectorStoreListGetParams,
  options?: RequestInit
): Promise<listVectorStoresVectorStoreListGetResponse> => {
  const res = await fetch(getListVectorStoresVectorStoreListGetUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listVectorStoresVectorStoreListGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listVectorStoresVectorStoreListGetResponse;
};

/**
 * Delete a vector store.

Parameters:
- vector_store_id: str - ID of the vector store to delete
 * @summary Delete Vector Store
 */
export type deleteVectorStoreVectorStoreDeletePostResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteVectorStoreVectorStoreDeletePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteVectorStoreVectorStoreDeletePostResponseComposite =
  | deleteVectorStoreVectorStoreDeletePostResponse200
  | deleteVectorStoreVectorStoreDeletePostResponse422;

export type deleteVectorStoreVectorStoreDeletePostResponse =
  deleteVectorStoreVectorStoreDeletePostResponseComposite & {
    headers: Headers;
  };

export const getDeleteVectorStoreVectorStoreDeletePostUrl = () => {
  return `/vector_store/delete`;
};

export const deleteVectorStoreVectorStoreDeletePost = async (
  vectorStoreDeleteRequest: VectorStoreDeleteRequest,
  options?: RequestInit
): Promise<deleteVectorStoreVectorStoreDeletePostResponse> => {
  const res = await fetch(getDeleteVectorStoreVectorStoreDeletePostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(vectorStoreDeleteRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteVectorStoreVectorStoreDeletePostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteVectorStoreVectorStoreDeletePostResponse;
};

/**
 * Return a single vector store's details
 * @summary Get Vector Store Info
 */
export type getVectorStoreInfoVectorStoreInfoPostResponse200 = {
  data: unknown;
  status: 200;
};

export type getVectorStoreInfoVectorStoreInfoPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getVectorStoreInfoVectorStoreInfoPostResponseComposite =
  | getVectorStoreInfoVectorStoreInfoPostResponse200
  | getVectorStoreInfoVectorStoreInfoPostResponse422;

export type getVectorStoreInfoVectorStoreInfoPostResponse =
  getVectorStoreInfoVectorStoreInfoPostResponseComposite & {
    headers: Headers;
  };

export const getGetVectorStoreInfoVectorStoreInfoPostUrl = () => {
  return `/vector_store/info`;
};

export const getVectorStoreInfoVectorStoreInfoPost = async (
  vectorStoreInfoRequest: VectorStoreInfoRequest,
  options?: RequestInit
): Promise<getVectorStoreInfoVectorStoreInfoPostResponse> => {
  const res = await fetch(getGetVectorStoreInfoVectorStoreInfoPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(vectorStoreInfoRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getVectorStoreInfoVectorStoreInfoPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getVectorStoreInfoVectorStoreInfoPostResponse;
};

/**
 * Update vector store details
 * @summary Update Vector Store
 */
export type updateVectorStoreVectorStoreUpdatePostResponse200 = {
  data: unknown;
  status: 200;
};

export type updateVectorStoreVectorStoreUpdatePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateVectorStoreVectorStoreUpdatePostResponseComposite =
  | updateVectorStoreVectorStoreUpdatePostResponse200
  | updateVectorStoreVectorStoreUpdatePostResponse422;

export type updateVectorStoreVectorStoreUpdatePostResponse =
  updateVectorStoreVectorStoreUpdatePostResponseComposite & {
    headers: Headers;
  };

export const getUpdateVectorStoreVectorStoreUpdatePostUrl = () => {
  return `/vector_store/update`;
};

export const updateVectorStoreVectorStoreUpdatePost = async (
  vectorStoreUpdateRequest: VectorStoreUpdateRequest,
  options?: RequestInit
): Promise<updateVectorStoreVectorStoreUpdatePostResponse> => {
  const res = await fetch(getUpdateVectorStoreVectorStoreUpdatePostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(vectorStoreUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: updateVectorStoreVectorStoreUpdatePostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateVectorStoreVectorStoreUpdatePostResponse;
};
