/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type {
  GetGroupsScimV2GroupsGetParams,
  GetUsersScimV2UsersGetParams,
  HTTPValidationError,
  SCIMGroup,
  SCIMListResponse,
  SCIMPatchOp,
  SCIMServiceProviderConfig,
  SCIMUser,
} from '.././schemas';

/**
 * Return SCIM Service Provider Configuration.
 * @summary Get Service Provider Config
 */
export type getServiceProviderConfigScimV2ServiceProviderConfigGetResponse200 =
  {
    data: SCIMServiceProviderConfig;
    status: 200;
  };

export type getServiceProviderConfigScimV2ServiceProviderConfigGetResponseComposite =
  getServiceProviderConfigScimV2ServiceProviderConfigGetResponse200;

export type getServiceProviderConfigScimV2ServiceProviderConfigGetResponse =
  getServiceProviderConfigScimV2ServiceProviderConfigGetResponseComposite & {
    headers: Headers;
  };

export const getGetServiceProviderConfigScimV2ServiceProviderConfigGetUrl =
  () => {
    return `/scim/v2/ServiceProviderConfig`;
  };

export const getServiceProviderConfigScimV2ServiceProviderConfigGet = async (
  options?: RequestInit
): Promise<getServiceProviderConfigScimV2ServiceProviderConfigGetResponse> => {
  const res = await fetch(
    getGetServiceProviderConfigScimV2ServiceProviderConfigGetUrl(),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getServiceProviderConfigScimV2ServiceProviderConfigGetResponse['data'] =
    body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getServiceProviderConfigScimV2ServiceProviderConfigGetResponse;
};

/**
 * Get a list of users according to SCIM v2 protocol
 * @summary Get Users
 */
export type getUsersScimV2UsersGetResponse200 = {
  data: SCIMListResponse;
  status: 200;
};

export type getUsersScimV2UsersGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getUsersScimV2UsersGetResponseComposite =
  | getUsersScimV2UsersGetResponse200
  | getUsersScimV2UsersGetResponse422;

export type getUsersScimV2UsersGetResponse =
  getUsersScimV2UsersGetResponseComposite & {
    headers: Headers;
  };

export const getGetUsersScimV2UsersGetUrl = (
  params?: GetUsersScimV2UsersGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/scim/v2/Users?${stringifiedParams}`
    : `/scim/v2/Users`;
};

export const getUsersScimV2UsersGet = async (
  params?: GetUsersScimV2UsersGetParams,
  options?: RequestInit
): Promise<getUsersScimV2UsersGetResponse> => {
  const res = await fetch(getGetUsersScimV2UsersGetUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getUsersScimV2UsersGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUsersScimV2UsersGetResponse;
};

/**
 * Create a user according to SCIM v2 protocol
 * @summary Create User
 */
export type createUserScimV2UsersPostResponse201 = {
  data: SCIMUser;
  status: 201;
};

export type createUserScimV2UsersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createUserScimV2UsersPostResponseComposite =
  | createUserScimV2UsersPostResponse201
  | createUserScimV2UsersPostResponse422;

export type createUserScimV2UsersPostResponse =
  createUserScimV2UsersPostResponseComposite & {
    headers: Headers;
  };

export const getCreateUserScimV2UsersPostUrl = () => {
  return `/scim/v2/Users`;
};

export const createUserScimV2UsersPost = async (
  sCIMUser: SCIMUser,
  options?: RequestInit
): Promise<createUserScimV2UsersPostResponse> => {
  const res = await fetch(getCreateUserScimV2UsersPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sCIMUser),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createUserScimV2UsersPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createUserScimV2UsersPostResponse;
};

/**
 * Get a single user by ID according to SCIM v2 protocol
 * @summary Get User
 */
export type getUserScimV2UsersUserIdGetResponse200 = {
  data: SCIMUser;
  status: 200;
};

export type getUserScimV2UsersUserIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getUserScimV2UsersUserIdGetResponseComposite =
  | getUserScimV2UsersUserIdGetResponse200
  | getUserScimV2UsersUserIdGetResponse422;

export type getUserScimV2UsersUserIdGetResponse =
  getUserScimV2UsersUserIdGetResponseComposite & {
    headers: Headers;
  };

export const getGetUserScimV2UsersUserIdGetUrl = (userId: string) => {
  return `/scim/v2/Users/${userId}`;
};

export const getUserScimV2UsersUserIdGet = async (
  userId: string,
  options?: RequestInit
): Promise<getUserScimV2UsersUserIdGetResponse> => {
  const res = await fetch(getGetUserScimV2UsersUserIdGetUrl(userId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getUserScimV2UsersUserIdGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserScimV2UsersUserIdGetResponse;
};

/**
 * Update a user according to SCIM v2 protocol (full replacement)
 * @summary Update User
 */
export type updateUserScimV2UsersUserIdPutResponse200 = {
  data: SCIMUser;
  status: 200;
};

export type updateUserScimV2UsersUserIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateUserScimV2UsersUserIdPutResponseComposite =
  | updateUserScimV2UsersUserIdPutResponse200
  | updateUserScimV2UsersUserIdPutResponse422;

export type updateUserScimV2UsersUserIdPutResponse =
  updateUserScimV2UsersUserIdPutResponseComposite & {
    headers: Headers;
  };

export const getUpdateUserScimV2UsersUserIdPutUrl = (userId: string) => {
  return `/scim/v2/Users/${userId}`;
};

export const updateUserScimV2UsersUserIdPut = async (
  userId: string,
  sCIMUser: SCIMUser,
  options?: RequestInit
): Promise<updateUserScimV2UsersUserIdPutResponse> => {
  const res = await fetch(getUpdateUserScimV2UsersUserIdPutUrl(userId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sCIMUser),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: updateUserScimV2UsersUserIdPutResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateUserScimV2UsersUserIdPutResponse;
};

/**
 * Delete a user according to SCIM v2 protocol
 * @summary Delete User
 */
export type deleteUserScimV2UsersUserIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteUserScimV2UsersUserIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteUserScimV2UsersUserIdDeleteResponseComposite =
  | deleteUserScimV2UsersUserIdDeleteResponse204
  | deleteUserScimV2UsersUserIdDeleteResponse422;

export type deleteUserScimV2UsersUserIdDeleteResponse =
  deleteUserScimV2UsersUserIdDeleteResponseComposite & {
    headers: Headers;
  };

export const getDeleteUserScimV2UsersUserIdDeleteUrl = (userId: string) => {
  return `/scim/v2/Users/${userId}`;
};

export const deleteUserScimV2UsersUserIdDelete = async (
  userId: string,
  options?: RequestInit
): Promise<deleteUserScimV2UsersUserIdDeleteResponse> => {
  const res = await fetch(getDeleteUserScimV2UsersUserIdDeleteUrl(userId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteUserScimV2UsersUserIdDeleteResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteUserScimV2UsersUserIdDeleteResponse;
};

/**
 * Patch a user according to SCIM v2 protocol
 * @summary Patch User
 */
export type patchUserScimV2UsersUserIdPatchResponse200 = {
  data: SCIMUser;
  status: 200;
};

export type patchUserScimV2UsersUserIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type patchUserScimV2UsersUserIdPatchResponseComposite =
  | patchUserScimV2UsersUserIdPatchResponse200
  | patchUserScimV2UsersUserIdPatchResponse422;

export type patchUserScimV2UsersUserIdPatchResponse =
  patchUserScimV2UsersUserIdPatchResponseComposite & {
    headers: Headers;
  };

export const getPatchUserScimV2UsersUserIdPatchUrl = (userId: string) => {
  return `/scim/v2/Users/${userId}`;
};

export const patchUserScimV2UsersUserIdPatch = async (
  userId: string,
  sCIMPatchOp: SCIMPatchOp,
  options?: RequestInit
): Promise<patchUserScimV2UsersUserIdPatchResponse> => {
  const res = await fetch(getPatchUserScimV2UsersUserIdPatchUrl(userId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sCIMPatchOp),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: patchUserScimV2UsersUserIdPatchResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchUserScimV2UsersUserIdPatchResponse;
};

/**
 * Get a list of groups according to SCIM v2 protocol
 * @summary Get Groups
 */
export type getGroupsScimV2GroupsGetResponse200 = {
  data: SCIMListResponse;
  status: 200;
};

export type getGroupsScimV2GroupsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getGroupsScimV2GroupsGetResponseComposite =
  | getGroupsScimV2GroupsGetResponse200
  | getGroupsScimV2GroupsGetResponse422;

export type getGroupsScimV2GroupsGetResponse =
  getGroupsScimV2GroupsGetResponseComposite & {
    headers: Headers;
  };

export const getGetGroupsScimV2GroupsGetUrl = (
  params?: GetGroupsScimV2GroupsGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/scim/v2/Groups?${stringifiedParams}`
    : `/scim/v2/Groups`;
};

export const getGroupsScimV2GroupsGet = async (
  params?: GetGroupsScimV2GroupsGetParams,
  options?: RequestInit
): Promise<getGroupsScimV2GroupsGetResponse> => {
  const res = await fetch(getGetGroupsScimV2GroupsGetUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getGroupsScimV2GroupsGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getGroupsScimV2GroupsGetResponse;
};

/**
 * Create a group according to SCIM v2 protocol
 * @summary Create Group
 */
export type createGroupScimV2GroupsPostResponse201 = {
  data: SCIMGroup;
  status: 201;
};

export type createGroupScimV2GroupsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createGroupScimV2GroupsPostResponseComposite =
  | createGroupScimV2GroupsPostResponse201
  | createGroupScimV2GroupsPostResponse422;

export type createGroupScimV2GroupsPostResponse =
  createGroupScimV2GroupsPostResponseComposite & {
    headers: Headers;
  };

export const getCreateGroupScimV2GroupsPostUrl = () => {
  return `/scim/v2/Groups`;
};

export const createGroupScimV2GroupsPost = async (
  sCIMGroup: SCIMGroup,
  options?: RequestInit
): Promise<createGroupScimV2GroupsPostResponse> => {
  const res = await fetch(getCreateGroupScimV2GroupsPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sCIMGroup),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createGroupScimV2GroupsPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createGroupScimV2GroupsPostResponse;
};

/**
 * Get a single group by ID according to SCIM v2 protocol
 * @summary Get Group
 */
export type getGroupScimV2GroupsGroupIdGetResponse200 = {
  data: SCIMGroup;
  status: 200;
};

export type getGroupScimV2GroupsGroupIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getGroupScimV2GroupsGroupIdGetResponseComposite =
  | getGroupScimV2GroupsGroupIdGetResponse200
  | getGroupScimV2GroupsGroupIdGetResponse422;

export type getGroupScimV2GroupsGroupIdGetResponse =
  getGroupScimV2GroupsGroupIdGetResponseComposite & {
    headers: Headers;
  };

export const getGetGroupScimV2GroupsGroupIdGetUrl = (groupId: string) => {
  return `/scim/v2/Groups/${groupId}`;
};

export const getGroupScimV2GroupsGroupIdGet = async (
  groupId: string,
  options?: RequestInit
): Promise<getGroupScimV2GroupsGroupIdGetResponse> => {
  const res = await fetch(getGetGroupScimV2GroupsGroupIdGetUrl(groupId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getGroupScimV2GroupsGroupIdGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getGroupScimV2GroupsGroupIdGetResponse;
};

/**
 * Update a group according to SCIM v2 protocol
 * @summary Update Group
 */
export type updateGroupScimV2GroupsGroupIdPutResponse200 = {
  data: SCIMGroup;
  status: 200;
};

export type updateGroupScimV2GroupsGroupIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateGroupScimV2GroupsGroupIdPutResponseComposite =
  | updateGroupScimV2GroupsGroupIdPutResponse200
  | updateGroupScimV2GroupsGroupIdPutResponse422;

export type updateGroupScimV2GroupsGroupIdPutResponse =
  updateGroupScimV2GroupsGroupIdPutResponseComposite & {
    headers: Headers;
  };

export const getUpdateGroupScimV2GroupsGroupIdPutUrl = (groupId: string) => {
  return `/scim/v2/Groups/${groupId}`;
};

export const updateGroupScimV2GroupsGroupIdPut = async (
  groupId: string,
  sCIMGroup: SCIMGroup,
  options?: RequestInit
): Promise<updateGroupScimV2GroupsGroupIdPutResponse> => {
  const res = await fetch(getUpdateGroupScimV2GroupsGroupIdPutUrl(groupId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sCIMGroup),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: updateGroupScimV2GroupsGroupIdPutResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateGroupScimV2GroupsGroupIdPutResponse;
};

/**
 * Delete a group according to SCIM v2 protocol
 * @summary Delete Group
 */
export type deleteGroupScimV2GroupsGroupIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteGroupScimV2GroupsGroupIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteGroupScimV2GroupsGroupIdDeleteResponseComposite =
  | deleteGroupScimV2GroupsGroupIdDeleteResponse204
  | deleteGroupScimV2GroupsGroupIdDeleteResponse422;

export type deleteGroupScimV2GroupsGroupIdDeleteResponse =
  deleteGroupScimV2GroupsGroupIdDeleteResponseComposite & {
    headers: Headers;
  };

export const getDeleteGroupScimV2GroupsGroupIdDeleteUrl = (groupId: string) => {
  return `/scim/v2/Groups/${groupId}`;
};

export const deleteGroupScimV2GroupsGroupIdDelete = async (
  groupId: string,
  options?: RequestInit
): Promise<deleteGroupScimV2GroupsGroupIdDeleteResponse> => {
  const res = await fetch(getDeleteGroupScimV2GroupsGroupIdDeleteUrl(groupId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteGroupScimV2GroupsGroupIdDeleteResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteGroupScimV2GroupsGroupIdDeleteResponse;
};

/**
 * Patch a group according to SCIM v2 protocol
 * @summary Patch Group
 */
export type patchGroupScimV2GroupsGroupIdPatchResponse200 = {
  data: SCIMGroup;
  status: 200;
};

export type patchGroupScimV2GroupsGroupIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type patchGroupScimV2GroupsGroupIdPatchResponseComposite =
  | patchGroupScimV2GroupsGroupIdPatchResponse200
  | patchGroupScimV2GroupsGroupIdPatchResponse422;

export type patchGroupScimV2GroupsGroupIdPatchResponse =
  patchGroupScimV2GroupsGroupIdPatchResponseComposite & {
    headers: Headers;
  };

export const getPatchGroupScimV2GroupsGroupIdPatchUrl = (groupId: string) => {
  return `/scim/v2/Groups/${groupId}`;
};

export const patchGroupScimV2GroupsGroupIdPatch = async (
  groupId: string,
  sCIMPatchOp: SCIMPatchOp,
  options?: RequestInit
): Promise<patchGroupScimV2GroupsGroupIdPatchResponse> => {
  const res = await fetch(getPatchGroupScimV2GroupsGroupIdPatchUrl(groupId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sCIMPatchOp),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: patchGroupScimV2GroupsGroupIdPatchResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchGroupScimV2GroupsGroupIdPatchResponse;
};
