/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type {
  AssistantObject,
  CreateAssistantRequest,
  CreateMessageRequest,
  CreateRunParams,
  CreateRunRequest,
  CreateThreadAndRunRequest,
  CreateThreadRequest,
  DeleteAssistantResponse,
  DeleteMessageResponse,
  DeleteThreadResponse,
  GetRunStepParams,
  ListAssistantsParams,
  ListAssistantsResponse,
  ListMessagesParams,
  ListMessagesResponse,
  ListRunStepsParams,
  ListRunStepsResponse,
  ListRunsParams,
  ListRunsResponse,
  MessageObject,
  ModifyAssistantRequest,
  ModifyMessageRequest,
  ModifyRunRequest,
  ModifyThreadRequest,
  RunObject,
  RunStepObject,
  SubmitToolOutputsRunRequest,
  ThreadObject,
} from '.././schemas';

/**
 * @summary Returns a list of assistants.
 */
export type listAssistantsResponse200 = {
  data: ListAssistantsResponse;
  status: 200;
};

export type listAssistantsResponseComposite = listAssistantsResponse200;

export type listAssistantsResponse = listAssistantsResponseComposite & {
  headers: Headers;
};

export const getListAssistantsUrl = (params?: ListAssistantsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/assistants?${stringifiedParams}`
    : `/assistants`;
};

export const listAssistants = async (
  params?: ListAssistantsParams,
  options?: RequestInit
): Promise<listAssistantsResponse> => {
  const res = await fetch(getListAssistantsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listAssistantsResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listAssistantsResponse;
};

/**
 * @summary Create an assistant with a model and instructions.
 */
export type createAssistantResponse200 = {
  data: AssistantObject;
  status: 200;
};

export type createAssistantResponseComposite = createAssistantResponse200;

export type createAssistantResponse = createAssistantResponseComposite & {
  headers: Headers;
};

export const getCreateAssistantUrl = () => {
  return `/assistants`;
};

export const createAssistant = async (
  createAssistantRequest: CreateAssistantRequest,
  options?: RequestInit
): Promise<createAssistantResponse> => {
  const res = await fetch(getCreateAssistantUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAssistantRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createAssistantResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createAssistantResponse;
};

/**
 * @summary Retrieves an assistant.
 */
export type getAssistantResponse200 = {
  data: AssistantObject;
  status: 200;
};

export type getAssistantResponseComposite = getAssistantResponse200;

export type getAssistantResponse = getAssistantResponseComposite & {
  headers: Headers;
};

export const getGetAssistantUrl = (assistantId: string) => {
  return `/assistants/${assistantId}`;
};

export const getAssistant = async (
  assistantId: string,
  options?: RequestInit
): Promise<getAssistantResponse> => {
  const res = await fetch(getGetAssistantUrl(assistantId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getAssistantResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAssistantResponse;
};

/**
 * @summary Modifies an assistant.
 */
export type modifyAssistantResponse200 = {
  data: AssistantObject;
  status: 200;
};

export type modifyAssistantResponseComposite = modifyAssistantResponse200;

export type modifyAssistantResponse = modifyAssistantResponseComposite & {
  headers: Headers;
};

export const getModifyAssistantUrl = (assistantId: string) => {
  return `/assistants/${assistantId}`;
};

export const modifyAssistant = async (
  assistantId: string,
  modifyAssistantRequest: ModifyAssistantRequest,
  options?: RequestInit
): Promise<modifyAssistantResponse> => {
  const res = await fetch(getModifyAssistantUrl(assistantId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(modifyAssistantRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: modifyAssistantResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as modifyAssistantResponse;
};

/**
 * @summary Delete an assistant.
 */
export type deleteAssistantResponse200 = {
  data: DeleteAssistantResponse;
  status: 200;
};

export type deleteAssistantResponseComposite = deleteAssistantResponse200;

export type deleteAssistantResponse = deleteAssistantResponseComposite & {
  headers: Headers;
};

export const getDeleteAssistantUrl = (assistantId: string) => {
  return `/assistants/${assistantId}`;
};

export const deleteAssistant = async (
  assistantId: string,
  options?: RequestInit
): Promise<deleteAssistantResponse> => {
  const res = await fetch(getDeleteAssistantUrl(assistantId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteAssistantResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteAssistantResponse;
};

/**
 * @summary Create a thread.
 */
export type createThreadResponse200 = {
  data: ThreadObject;
  status: 200;
};

export type createThreadResponseComposite = createThreadResponse200;

export type createThreadResponse = createThreadResponseComposite & {
  headers: Headers;
};

export const getCreateThreadUrl = () => {
  return `/threads`;
};

export const createThread = async (
  createThreadRequest: CreateThreadRequest,
  options?: RequestInit
): Promise<createThreadResponse> => {
  const res = await fetch(getCreateThreadUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createThreadRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createThreadResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createThreadResponse;
};

/**
 * @summary Create a thread and run it in one request.
 */
export type createThreadAndRunResponse200 = {
  data: RunObject;
  status: 200;
};

export type createThreadAndRunResponseComposite = createThreadAndRunResponse200;

export type createThreadAndRunResponse = createThreadAndRunResponseComposite & {
  headers: Headers;
};

export const getCreateThreadAndRunUrl = () => {
  return `/threads/runs`;
};

export const createThreadAndRun = async (
  createThreadAndRunRequest: CreateThreadAndRunRequest,
  options?: RequestInit
): Promise<createThreadAndRunResponse> => {
  const res = await fetch(getCreateThreadAndRunUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createThreadAndRunRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createThreadAndRunResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createThreadAndRunResponse;
};

/**
 * @summary Retrieves a thread.
 */
export type getThreadResponse200 = {
  data: ThreadObject;
  status: 200;
};

export type getThreadResponseComposite = getThreadResponse200;

export type getThreadResponse = getThreadResponseComposite & {
  headers: Headers;
};

export const getGetThreadUrl = (threadId: string) => {
  return `/threads/${threadId}`;
};

export const getThread = async (
  threadId: string,
  options?: RequestInit
): Promise<getThreadResponse> => {
  const res = await fetch(getGetThreadUrl(threadId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getThreadResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getThreadResponse;
};

/**
 * @summary Modifies a thread.
 */
export type modifyThreadResponse200 = {
  data: ThreadObject;
  status: 200;
};

export type modifyThreadResponseComposite = modifyThreadResponse200;

export type modifyThreadResponse = modifyThreadResponseComposite & {
  headers: Headers;
};

export const getModifyThreadUrl = (threadId: string) => {
  return `/threads/${threadId}`;
};

export const modifyThread = async (
  threadId: string,
  modifyThreadRequest: ModifyThreadRequest,
  options?: RequestInit
): Promise<modifyThreadResponse> => {
  const res = await fetch(getModifyThreadUrl(threadId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(modifyThreadRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: modifyThreadResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as modifyThreadResponse;
};

/**
 * @summary Delete a thread.
 */
export type deleteThreadResponse200 = {
  data: DeleteThreadResponse;
  status: 200;
};

export type deleteThreadResponseComposite = deleteThreadResponse200;

export type deleteThreadResponse = deleteThreadResponseComposite & {
  headers: Headers;
};

export const getDeleteThreadUrl = (threadId: string) => {
  return `/threads/${threadId}`;
};

export const deleteThread = async (
  threadId: string,
  options?: RequestInit
): Promise<deleteThreadResponse> => {
  const res = await fetch(getDeleteThreadUrl(threadId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteThreadResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteThreadResponse;
};

/**
 * @summary Returns a list of messages for a given thread.
 */
export type listMessagesResponse200 = {
  data: ListMessagesResponse;
  status: 200;
};

export type listMessagesResponseComposite = listMessagesResponse200;

export type listMessagesResponse = listMessagesResponseComposite & {
  headers: Headers;
};

export const getListMessagesUrl = (
  threadId: string,
  params?: ListMessagesParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/threads/${threadId}/messages?${stringifiedParams}`
    : `/threads/${threadId}/messages`;
};

export const listMessages = async (
  threadId: string,
  params?: ListMessagesParams,
  options?: RequestInit
): Promise<listMessagesResponse> => {
  const res = await fetch(getListMessagesUrl(threadId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listMessagesResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listMessagesResponse;
};

/**
 * @summary Create a message.
 */
export type createMessageResponse200 = {
  data: MessageObject;
  status: 200;
};

export type createMessageResponseComposite = createMessageResponse200;

export type createMessageResponse = createMessageResponseComposite & {
  headers: Headers;
};

export const getCreateMessageUrl = (threadId: string) => {
  return `/threads/${threadId}/messages`;
};

export const createMessage = async (
  threadId: string,
  createMessageRequest: CreateMessageRequest,
  options?: RequestInit
): Promise<createMessageResponse> => {
  const res = await fetch(getCreateMessageUrl(threadId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createMessageRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createMessageResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createMessageResponse;
};

/**
 * @summary Retrieve a message.
 */
export type getMessageResponse200 = {
  data: MessageObject;
  status: 200;
};

export type getMessageResponseComposite = getMessageResponse200;

export type getMessageResponse = getMessageResponseComposite & {
  headers: Headers;
};

export const getGetMessageUrl = (threadId: string, messageId: string) => {
  return `/threads/${threadId}/messages/${messageId}`;
};

export const getMessage = async (
  threadId: string,
  messageId: string,
  options?: RequestInit
): Promise<getMessageResponse> => {
  const res = await fetch(getGetMessageUrl(threadId, messageId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getMessageResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMessageResponse;
};

/**
 * @summary Modifies a message.
 */
export type modifyMessageResponse200 = {
  data: MessageObject;
  status: 200;
};

export type modifyMessageResponseComposite = modifyMessageResponse200;

export type modifyMessageResponse = modifyMessageResponseComposite & {
  headers: Headers;
};

export const getModifyMessageUrl = (threadId: string, messageId: string) => {
  return `/threads/${threadId}/messages/${messageId}`;
};

export const modifyMessage = async (
  threadId: string,
  messageId: string,
  modifyMessageRequest: ModifyMessageRequest,
  options?: RequestInit
): Promise<modifyMessageResponse> => {
  const res = await fetch(getModifyMessageUrl(threadId, messageId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(modifyMessageRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: modifyMessageResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as modifyMessageResponse;
};

/**
 * @summary Deletes a message.
 */
export type deleteMessageResponse200 = {
  data: DeleteMessageResponse;
  status: 200;
};

export type deleteMessageResponseComposite = deleteMessageResponse200;

export type deleteMessageResponse = deleteMessageResponseComposite & {
  headers: Headers;
};

export const getDeleteMessageUrl = (threadId: string, messageId: string) => {
  return `/threads/${threadId}/messages/${messageId}`;
};

export const deleteMessage = async (
  threadId: string,
  messageId: string,
  options?: RequestInit
): Promise<deleteMessageResponse> => {
  const res = await fetch(getDeleteMessageUrl(threadId, messageId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteMessageResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteMessageResponse;
};

/**
 * @summary Returns a list of runs belonging to a thread.
 */
export type listRunsResponse200 = {
  data: ListRunsResponse;
  status: 200;
};

export type listRunsResponseComposite = listRunsResponse200;

export type listRunsResponse = listRunsResponseComposite & {
  headers: Headers;
};

export const getListRunsUrl = (threadId: string, params?: ListRunsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/threads/${threadId}/runs?${stringifiedParams}`
    : `/threads/${threadId}/runs`;
};

export const listRuns = async (
  threadId: string,
  params?: ListRunsParams,
  options?: RequestInit
): Promise<listRunsResponse> => {
  const res = await fetch(getListRunsUrl(threadId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listRunsResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as listRunsResponse;
};

/**
 * @summary Create a run.
 */
export type createRunResponse200 = {
  data: RunObject;
  status: 200;
};

export type createRunResponseComposite = createRunResponse200;

export type createRunResponse = createRunResponseComposite & {
  headers: Headers;
};

export const getCreateRunUrl = (threadId: string, params?: CreateRunParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/threads/${threadId}/runs?${stringifiedParams}`
    : `/threads/${threadId}/runs`;
};

export const createRun = async (
  threadId: string,
  createRunRequest: CreateRunRequest,
  params?: CreateRunParams,
  options?: RequestInit
): Promise<createRunResponse> => {
  const res = await fetch(getCreateRunUrl(threadId, params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRunRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createRunResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createRunResponse;
};

/**
 * @summary Retrieves a run.
 */
export type getRunResponse200 = {
  data: RunObject;
  status: 200;
};

export type getRunResponseComposite = getRunResponse200;

export type getRunResponse = getRunResponseComposite & {
  headers: Headers;
};

export const getGetRunUrl = (threadId: string, runId: string) => {
  return `/threads/${threadId}/runs/${runId}`;
};

export const getRun = async (
  threadId: string,
  runId: string,
  options?: RequestInit
): Promise<getRunResponse> => {
  const res = await fetch(getGetRunUrl(threadId, runId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getRunResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as getRunResponse;
};

/**
 * @summary Modifies a run.
 */
export type modifyRunResponse200 = {
  data: RunObject;
  status: 200;
};

export type modifyRunResponseComposite = modifyRunResponse200;

export type modifyRunResponse = modifyRunResponseComposite & {
  headers: Headers;
};

export const getModifyRunUrl = (threadId: string, runId: string) => {
  return `/threads/${threadId}/runs/${runId}`;
};

export const modifyRun = async (
  threadId: string,
  runId: string,
  modifyRunRequest: ModifyRunRequest,
  options?: RequestInit
): Promise<modifyRunResponse> => {
  const res = await fetch(getModifyRunUrl(threadId, runId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(modifyRunRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: modifyRunResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as modifyRunResponse;
};

/**
 * @summary Cancels a run that is `in_progress`.
 */
export type cancelRunResponse200 = {
  data: RunObject;
  status: 200;
};

export type cancelRunResponseComposite = cancelRunResponse200;

export type cancelRunResponse = cancelRunResponseComposite & {
  headers: Headers;
};

export const getCancelRunUrl = (threadId: string, runId: string) => {
  return `/threads/${threadId}/runs/${runId}/cancel`;
};

export const cancelRun = async (
  threadId: string,
  runId: string,
  options?: RequestInit
): Promise<cancelRunResponse> => {
  const res = await fetch(getCancelRunUrl(threadId, runId), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: cancelRunResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as cancelRunResponse;
};

/**
 * @summary Returns a list of run steps belonging to a run.
 */
export type listRunStepsResponse200 = {
  data: ListRunStepsResponse;
  status: 200;
};

export type listRunStepsResponseComposite = listRunStepsResponse200;

export type listRunStepsResponse = listRunStepsResponseComposite & {
  headers: Headers;
};

export const getListRunStepsUrl = (
  threadId: string,
  runId: string,
  params?: ListRunStepsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/threads/${threadId}/runs/${runId}/steps?${stringifiedParams}`
    : `/threads/${threadId}/runs/${runId}/steps`;
};

export const listRunSteps = async (
  threadId: string,
  runId: string,
  params?: ListRunStepsParams,
  options?: RequestInit
): Promise<listRunStepsResponse> => {
  const res = await fetch(getListRunStepsUrl(threadId, runId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: listRunStepsResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listRunStepsResponse;
};

/**
 * @summary Retrieves a run step.
 */
export type getRunStepResponse200 = {
  data: RunStepObject;
  status: 200;
};

export type getRunStepResponseComposite = getRunStepResponse200;

export type getRunStepResponse = getRunStepResponseComposite & {
  headers: Headers;
};

export const getGetRunStepUrl = (
  threadId: string,
  runId: string,
  stepId: string,
  params?: GetRunStepParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/threads/${threadId}/runs/${runId}/steps/${stepId}?${stringifiedParams}`
    : `/threads/${threadId}/runs/${runId}/steps/${stepId}`;
};

export const getRunStep = async (
  threadId: string,
  runId: string,
  stepId: string,
  params?: GetRunStepParams,
  options?: RequestInit
): Promise<getRunStepResponse> => {
  const res = await fetch(getGetRunStepUrl(threadId, runId, stepId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getRunStepResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getRunStepResponse;
};

/**
 * @summary When a run has the `status: "requires_action"` and `required_action.type` is `submit_tool_outputs`, this endpoint can be used to submit the outputs from the tool calls once they're all completed. All outputs must be submitted in a single request.

 */
export type submitToolOuputsToRunResponse200 = {
  data: RunObject;
  status: 200;
};

export type submitToolOuputsToRunResponseComposite =
  submitToolOuputsToRunResponse200;

export type submitToolOuputsToRunResponse =
  submitToolOuputsToRunResponseComposite & {
    headers: Headers;
  };

export const getSubmitToolOuputsToRunUrl = (
  threadId: string,
  runId: string
) => {
  return `/threads/${threadId}/runs/${runId}/submit_tool_outputs`;
};

export const submitToolOuputsToRun = async (
  threadId: string,
  runId: string,
  submitToolOutputsRunRequest: SubmitToolOutputsRunRequest,
  options?: RequestInit
): Promise<submitToolOuputsToRunResponse> => {
  const res = await fetch(getSubmitToolOuputsToRunUrl(threadId, runId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitToolOutputsRunRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: submitToolOuputsToRunResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as submitToolOuputsToRunResponse;
};
