/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { CachePingResponsePingResponse } from './cachePingResponsePingResponse';
import type { CachePingResponseSetCacheResponse } from './cachePingResponseSetCacheResponse';
import type { CachePingResponseLitellmCacheParams } from './cachePingResponseLitellmCacheParams';
import type { CachePingResponseHealthCheckCacheParams } from './cachePingResponseHealthCheckCacheParams';

export interface CachePingResponse {
  status: string;
  cache_type: string;
  ping_response?: CachePingResponsePingResponse;
  set_cache_response?: CachePingResponseSetCacheResponse;
  litellm_cache_params?: CachePingResponseLitellmCacheParams;
  health_check_cache_params?: CachePingResponseHealthCheckCacheParams;
}
