/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { DefaultTeamSSOParamsMaxBudget } from './defaultTeamSSOParamsMaxBudget';
import type { DefaultTeamSSOParamsBudgetDuration } from './defaultTeamSSOParamsBudgetDuration';
import type { DefaultTeamSSOParamsTpmLimit } from './defaultTeamSSOParamsTpmLimit';
import type { DefaultTeamSSOParamsRpmLimit } from './defaultTeamSSOParamsRpmLimit';

/**
 * Default parameters to apply when a new team is automatically created by LiteLLM via SSO Groups
 */
export interface DefaultTeamSSOParams {
  /** Default list of models that new automatically created teams can access */
  models?: string[];
  /** Default maximum budget (in USD) for new automatically created teams */
  max_budget?: DefaultTeamSSOParamsMaxBudget;
  /** Default budget duration for new automatically created teams (e.g. 'daily', 'weekly', 'monthly') */
  budget_duration?: DefaultTeamSSOParamsBudgetDuration;
  /** Default tpm limit for new automatically created teams */
  tpm_limit?: DefaultTeamSSOParamsTpmLimit;
  /** Default rpm limit for new automatically created teams */
  rpm_limit?: DefaultTeamSSOParamsRpmLimit;
}
