/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { LiteLLMOrganizationMembershipTableUserRole } from './liteLLMOrganizationMembershipTableUserRole';
import type { LiteLLMOrganizationMembershipTableBudgetId } from './liteLLMOrganizationMembershipTableBudgetId';
import type { LiteLLMOrganizationMembershipTableUser } from './liteLLMOrganizationMembershipTableUser';
import type { LiteLLMOrganizationMembershipTableLitellmBudgetTable } from './liteLLMOrganizationMembershipTableLitellmBudgetTable';

/**
 * This is the table that track what organizations a user belongs to and users spend within the organization
 */
export interface LiteLLMOrganizationMembershipTable {
  user_id: string;
  organization_id: string;
  user_role?: LiteLLMOrganizationMembershipTableUserRole;
  spend?: number;
  budget_id?: LiteLLMOrganizationMembershipTableBudgetId;
  created_at: string;
  updated_at: string;
  user?: LiteLLMOrganizationMembershipTableUser;
  litellm_budget_table?: LiteLLMOrganizationMembershipTableLitellmBudgetTable;
}
