/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { ModelInfoId } from './modelInfoId';
import type { ModelInfoUpdatedAt } from './modelInfoUpdatedAt';
import type { ModelInfoUpdatedBy } from './modelInfoUpdatedBy';
import type { ModelInfoCreatedAt } from './modelInfoCreatedAt';
import type { ModelInfoCreatedBy } from './modelInfoCreatedBy';
import type { ModelInfoBaseModel } from './modelInfoBaseModel';
import type { ModelInfoTier } from './modelInfoTier';
import type { ModelInfoTeamId } from './modelInfoTeamId';
import type { ModelInfoTeamPublicModelName } from './modelInfoTeamPublicModelName';

export interface ModelInfo {
  id: ModelInfoId;
  db_model?: boolean;
  updated_at?: ModelInfoUpdatedAt;
  updated_by?: ModelInfoUpdatedBy;
  created_at?: ModelInfoCreatedAt;
  created_by?: ModelInfoCreatedBy;
  base_model?: ModelInfoBaseModel;
  tier?: ModelInfoTier;
  team_id?: ModelInfoTeamId;
  team_public_model_name?: ModelInfoTeamPublicModelName;
  [key: string]: unknown;
}
