/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { NewUserRequestKeyAlias } from './newUserRequestKeyAlias';
import type { NewUserRequestDuration } from './newUserRequestDuration';
import type { NewUserRequestModels } from './newUserRequestModels';
import type { NewUserRequestSpend } from './newUserRequestSpend';
import type { NewUserRequestMaxBudget } from './newUserRequestMaxBudget';
import type { NewUserRequestUserId } from './newUserRequestUserId';
import type { NewUserRequestTeamId } from './newUserRequestTeamId';
import type { NewUserRequestMaxParallelRequests } from './newUserRequestMaxParallelRequests';
import type { NewUserRequestMetadata } from './newUserRequestMetadata';
import type { NewUserRequestTpmLimit } from './newUserRequestTpmLimit';
import type { NewUserRequestRpmLimit } from './newUserRequestRpmLimit';
import type { NewUserRequestBudgetDuration } from './newUserRequestBudgetDuration';
import type { NewUserRequestAllowedCacheControls } from './newUserRequestAllowedCacheControls';
import type { NewUserRequestConfig } from './newUserRequestConfig';
import type { NewUserRequestPermissions } from './newUserRequestPermissions';
import type { NewUserRequestModelMaxBudget } from './newUserRequestModelMaxBudget';
import type { NewUserRequestModelRpmLimit } from './newUserRequestModelRpmLimit';
import type { NewUserRequestModelTpmLimit } from './newUserRequestModelTpmLimit';
import type { NewUserRequestGuardrails } from './newUserRequestGuardrails';
import type { NewUserRequestBlocked } from './newUserRequestBlocked';
import type { NewUserRequestAliases } from './newUserRequestAliases';
import type { NewUserRequestObjectPermission } from './newUserRequestObjectPermission';
import type { NewUserRequestUserEmail } from './newUserRequestUserEmail';
import type { NewUserRequestUserAlias } from './newUserRequestUserAlias';
import type { NewUserRequestUserRole } from './newUserRequestUserRole';
import type { NewUserRequestTeams } from './newUserRequestTeams';
import type { NewUserRequestSendInviteEmail } from './newUserRequestSendInviteEmail';
import type { NewUserRequestSsoUserId } from './newUserRequestSsoUserId';
import type { NewUserRequestOrganizations } from './newUserRequestOrganizations';

export interface NewUserRequest {
  key_alias?: NewUserRequestKeyAlias;
  duration?: NewUserRequestDuration;
  models?: NewUserRequestModels;
  spend?: NewUserRequestSpend;
  max_budget?: NewUserRequestMaxBudget;
  user_id?: NewUserRequestUserId;
  team_id?: NewUserRequestTeamId;
  max_parallel_requests?: NewUserRequestMaxParallelRequests;
  metadata?: NewUserRequestMetadata;
  tpm_limit?: NewUserRequestTpmLimit;
  rpm_limit?: NewUserRequestRpmLimit;
  budget_duration?: NewUserRequestBudgetDuration;
  allowed_cache_controls?: NewUserRequestAllowedCacheControls;
  config?: NewUserRequestConfig;
  permissions?: NewUserRequestPermissions;
  model_max_budget?: NewUserRequestModelMaxBudget;
  model_rpm_limit?: NewUserRequestModelRpmLimit;
  model_tpm_limit?: NewUserRequestModelTpmLimit;
  guardrails?: NewUserRequestGuardrails;
  blocked?: NewUserRequestBlocked;
  aliases?: NewUserRequestAliases;
  object_permission?: NewUserRequestObjectPermission;
  user_email?: NewUserRequestUserEmail;
  user_alias?: NewUserRequestUserAlias;
  user_role?: NewUserRequestUserRole;
  teams?: NewUserRequestTeams;
  auto_create_key?: boolean;
  send_invite_email?: NewUserRequestSendInviteEmail;
  sso_user_id?: NewUserRequestSsoUserId;
  organizations?: NewUserRequestOrganizations;
}
