/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type { RegenerateKeyRequestKeyAlias } from './regenerateKeyRequestKeyAlias';
import type { RegenerateKeyRequestDuration } from './regenerateKeyRequestDuration';
import type { RegenerateKeyRequestModels } from './regenerateKeyRequestModels';
import type { RegenerateKeyRequestSpend } from './regenerateKeyRequestSpend';
import type { RegenerateKeyRequestMaxBudget } from './regenerateKeyRequestMaxBudget';
import type { RegenerateKeyRequestUserId } from './regenerateKeyRequestUserId';
import type { RegenerateKeyRequestTeamId } from './regenerateKeyRequestTeamId';
import type { RegenerateKeyRequestMaxParallelRequests } from './regenerateKeyRequestMaxParallelRequests';
import type { RegenerateKeyRequestMetadata } from './regenerateKeyRequestMetadata';
import type { RegenerateKeyRequestTpmLimit } from './regenerateKeyRequestTpmLimit';
import type { RegenerateKeyRequestRpmLimit } from './regenerateKeyRequestRpmLimit';
import type { RegenerateKeyRequestBudgetDuration } from './regenerateKeyRequestBudgetDuration';
import type { RegenerateKeyRequestAllowedCacheControls } from './regenerateKeyRequestAllowedCacheControls';
import type { RegenerateKeyRequestConfig } from './regenerateKeyRequestConfig';
import type { RegenerateKeyRequestPermissions } from './regenerateKeyRequestPermissions';
import type { RegenerateKeyRequestModelMaxBudget } from './regenerateKeyRequestModelMaxBudget';
import type { RegenerateKeyRequestModelRpmLimit } from './regenerateKeyRequestModelRpmLimit';
import type { RegenerateKeyRequestModelTpmLimit } from './regenerateKeyRequestModelTpmLimit';
import type { RegenerateKeyRequestGuardrails } from './regenerateKeyRequestGuardrails';
import type { RegenerateKeyRequestBlocked } from './regenerateKeyRequestBlocked';
import type { RegenerateKeyRequestAliases } from './regenerateKeyRequestAliases';
import type { RegenerateKeyRequestObjectPermission } from './regenerateKeyRequestObjectPermission';
import type { RegenerateKeyRequestKey } from './regenerateKeyRequestKey';
import type { RegenerateKeyRequestBudgetId } from './regenerateKeyRequestBudgetId';
import type { RegenerateKeyRequestTags } from './regenerateKeyRequestTags';
import type { RegenerateKeyRequestEnforcedParams } from './regenerateKeyRequestEnforcedParams';
import type { RegenerateKeyRequestAllowedRoutes } from './regenerateKeyRequestAllowedRoutes';
import type { RegenerateKeyRequestSoftBudget } from './regenerateKeyRequestSoftBudget';
import type { RegenerateKeyRequestSendInviteEmail } from './regenerateKeyRequestSendInviteEmail';
import type { RegenerateKeyRequestKeyType } from './regenerateKeyRequestKeyType';
import type { RegenerateKeyRequestNewKey } from './regenerateKeyRequestNewKey';
import type { RegenerateKeyRequestNewMasterKey } from './regenerateKeyRequestNewMasterKey';

export interface RegenerateKeyRequest {
  key_alias?: RegenerateKeyRequestKeyAlias;
  duration?: RegenerateKeyRequestDuration;
  models?: RegenerateKeyRequestModels;
  spend?: RegenerateKeyRequestSpend;
  max_budget?: RegenerateKeyRequestMaxBudget;
  user_id?: RegenerateKeyRequestUserId;
  team_id?: RegenerateKeyRequestTeamId;
  max_parallel_requests?: RegenerateKeyRequestMaxParallelRequests;
  metadata?: RegenerateKeyRequestMetadata;
  tpm_limit?: RegenerateKeyRequestTpmLimit;
  rpm_limit?: RegenerateKeyRequestRpmLimit;
  budget_duration?: RegenerateKeyRequestBudgetDuration;
  allowed_cache_controls?: RegenerateKeyRequestAllowedCacheControls;
  config?: RegenerateKeyRequestConfig;
  permissions?: RegenerateKeyRequestPermissions;
  model_max_budget?: RegenerateKeyRequestModelMaxBudget;
  model_rpm_limit?: RegenerateKeyRequestModelRpmLimit;
  model_tpm_limit?: RegenerateKeyRequestModelTpmLimit;
  guardrails?: RegenerateKeyRequestGuardrails;
  blocked?: RegenerateKeyRequestBlocked;
  aliases?: RegenerateKeyRequestAliases;
  object_permission?: RegenerateKeyRequestObjectPermission;
  key?: RegenerateKeyRequestKey;
  budget_id?: RegenerateKeyRequestBudgetId;
  tags?: RegenerateKeyRequestTags;
  enforced_params?: RegenerateKeyRequestEnforcedParams;
  allowed_routes?: RegenerateKeyRequestAllowedRoutes;
  soft_budget?: RegenerateKeyRequestSoftBudget;
  send_invite_email?: RegenerateKeyRequestSendInviteEmail;
  /** Type of key that determines default allowed routes. */
  key_type?: RegenerateKeyRequestKeyType;
  new_key?: RegenerateKeyRequestNewKey;
  new_master_key?: RegenerateKeyRequestNewMasterKey;
}
