/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * LiteLLM API
 * Proxy Server to call 100+ LLMs in the OpenAI format. [**Customize Swagger Docs**](https://docs.litellm.ai/docs/proxy/enterprise#swagger-docs---custom-routes--branding)

👉 [```LiteLLM Admin Panel on /ui```](/ui/). Create, Edit Keys with SSO

💸 [```LiteLLM Model Cost Map```](https://models.litellm.ai/).

🔎 [```LiteLLM Model Hub```](/ui/model_hub_table). See available models on the proxy. [**Docs**](https://docs.litellm.ai/docs/proxy/model_hub)
 * OpenAPI spec version: 1.74.11
 */
import type {
  BodyTestModelConnectionHealthTestConnectionPost,
  HTTPValidationError,
  HealthCheckHistoryEndpointHealthHistoryGetParams,
  HealthEndpointHealthGetParams,
  HealthServicesEndpointHealthServicesGetParams,
} from '.././models';

/**
 * [DEPRECATED] use `/health/liveliness` instead.

A test endpoint that pings the proxy server to check if it's healthy.

Parameters:
    request (Request): The incoming request.

Returns:
    dict: A dictionary containing the route of the request URL.
 * @summary Test Endpoint
 */
export type testEndpointTestGetResponse200 = {
  data: unknown;
  status: 200;
};

export type testEndpointTestGetResponseComposite =
  testEndpointTestGetResponse200;

export type testEndpointTestGetResponse =
  testEndpointTestGetResponseComposite & {
    headers: Headers;
  };

export const getTestEndpointTestGetUrl = () => {
  return `/test`;
};

export const testEndpointTestGet = async (
  options?: RequestInit
): Promise<testEndpointTestGetResponse> => {
  const res = await fetch(getTestEndpointTestGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: testEndpointTestGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as testEndpointTestGetResponse;
};

/**
 * Use this admin-only endpoint to check if the service is healthy.

Example:
```
curl -L -X GET 'http://0.0.0.0:4000/health/services?service=datadog'     -H 'Authorization: Bearer sk-1234'
```
 * @summary Health Services Endpoint
 */
export type healthServicesEndpointHealthServicesGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthServicesEndpointHealthServicesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type healthServicesEndpointHealthServicesGetResponseComposite =
  | healthServicesEndpointHealthServicesGetResponse200
  | healthServicesEndpointHealthServicesGetResponse422;

export type healthServicesEndpointHealthServicesGetResponse =
  healthServicesEndpointHealthServicesGetResponseComposite & {
    headers: Headers;
  };

export const getHealthServicesEndpointHealthServicesGetUrl = (
  params: HealthServicesEndpointHealthServicesGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/health/services?${stringifiedParams}`
    : `/health/services`;
};

export const healthServicesEndpointHealthServicesGet = async (
  params: HealthServicesEndpointHealthServicesGetParams,
  options?: RequestInit
): Promise<healthServicesEndpointHealthServicesGetResponse> => {
  const res = await fetch(
    getHealthServicesEndpointHealthServicesGetUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: healthServicesEndpointHealthServicesGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthServicesEndpointHealthServicesGetResponse;
};

/**
 * 🚨 USE `/health/liveliness` to health check the proxy 🚨

See more 👉 https://docs.litellm.ai/docs/proxy/health


Check the health of all the endpoints in config.yaml

To run health checks in the background, add this to config.yaml:
```
general_settings:
    # ... other settings
    background_health_checks: True
```
else, the health checks will be run on models when /health is called.
 * @summary Health Endpoint
 */
export type healthEndpointHealthGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthEndpointHealthGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type healthEndpointHealthGetResponseComposite =
  | healthEndpointHealthGetResponse200
  | healthEndpointHealthGetResponse422;

export type healthEndpointHealthGetResponse =
  healthEndpointHealthGetResponseComposite & {
    headers: Headers;
  };

export const getHealthEndpointHealthGetUrl = (
  params?: HealthEndpointHealthGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/health?${stringifiedParams}`
    : `/health`;
};

export const healthEndpointHealthGet = async (
  params?: HealthEndpointHealthGetParams,
  options?: RequestInit
): Promise<healthEndpointHealthGetResponse> => {
  const res = await fetch(getHealthEndpointHealthGetUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: healthEndpointHealthGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthEndpointHealthGetResponse;
};

/**
 * Get health check history for models

Returns historical health check data with optional filtering.
 * @summary Health Check History Endpoint
 */
export type healthCheckHistoryEndpointHealthHistoryGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthCheckHistoryEndpointHealthHistoryGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type healthCheckHistoryEndpointHealthHistoryGetResponseComposite =
  | healthCheckHistoryEndpointHealthHistoryGetResponse200
  | healthCheckHistoryEndpointHealthHistoryGetResponse422;

export type healthCheckHistoryEndpointHealthHistoryGetResponse =
  healthCheckHistoryEndpointHealthHistoryGetResponseComposite & {
    headers: Headers;
  };

export const getHealthCheckHistoryEndpointHealthHistoryGetUrl = (
  params?: HealthCheckHistoryEndpointHealthHistoryGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/health/history?${stringifiedParams}`
    : `/health/history`;
};

export const healthCheckHistoryEndpointHealthHistoryGet = async (
  params?: HealthCheckHistoryEndpointHealthHistoryGetParams,
  options?: RequestInit
): Promise<healthCheckHistoryEndpointHealthHistoryGetResponse> => {
  const res = await fetch(
    getHealthCheckHistoryEndpointHealthHistoryGetUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: healthCheckHistoryEndpointHealthHistoryGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthCheckHistoryEndpointHealthHistoryGetResponse;
};

/**
 * Get the latest health check status for all models

Returns the most recent health check result for each model.
 * @summary Latest Health Checks Endpoint
 */
export type latestHealthChecksEndpointHealthLatestGetResponse200 = {
  data: unknown;
  status: 200;
};

export type latestHealthChecksEndpointHealthLatestGetResponseComposite =
  latestHealthChecksEndpointHealthLatestGetResponse200;

export type latestHealthChecksEndpointHealthLatestGetResponse =
  latestHealthChecksEndpointHealthLatestGetResponseComposite & {
    headers: Headers;
  };

export const getLatestHealthChecksEndpointHealthLatestGetUrl = () => {
  return `/health/latest`;
};

export const latestHealthChecksEndpointHealthLatestGet = async (
  options?: RequestInit
): Promise<latestHealthChecksEndpointHealthLatestGetResponse> => {
  const res = await fetch(getLatestHealthChecksEndpointHealthLatestGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: latestHealthChecksEndpointHealthLatestGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as latestHealthChecksEndpointHealthLatestGetResponse;
};

/**
 * Returns a list of litellm level settings

This is useful for debugging and ensuring the proxy server is configured correctly.

Response schema:
```
{
    "alerting": _alerting,
    "litellm.callbacks": litellm_callbacks,
    "litellm.input_callback": litellm_input_callbacks,
    "litellm.failure_callback": litellm_failure_callbacks,
    "litellm.success_callback": litellm_success_callbacks,
    "litellm._async_success_callback": litellm_async_success_callbacks,
    "litellm._async_failure_callback": litellm_async_failure_callbacks,
    "litellm._async_input_callback": litellm_async_input_callbacks,
    "all_litellm_callbacks": all_litellm_callbacks,
    "num_callbacks": len(all_litellm_callbacks),
    "num_alerting": _num_alerting,
    "litellm.request_timeout": litellm.request_timeout,
}
```
 * @summary Active Callbacks
 */
export type activeCallbacksActiveCallbacksGetResponse200 = {
  data: unknown;
  status: 200;
};

export type activeCallbacksActiveCallbacksGetResponseComposite =
  activeCallbacksActiveCallbacksGetResponse200;

export type activeCallbacksActiveCallbacksGetResponse =
  activeCallbacksActiveCallbacksGetResponseComposite & {
    headers: Headers;
  };

export const getActiveCallbacksActiveCallbacksGetUrl = () => {
  return `/active/callbacks`;
};

export const activeCallbacksActiveCallbacksGet = async (
  options?: RequestInit
): Promise<activeCallbacksActiveCallbacksGetResponse> => {
  const res = await fetch(getActiveCallbacksActiveCallbacksGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: activeCallbacksActiveCallbacksGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as activeCallbacksActiveCallbacksGetResponse;
};

/**
 * Returns a list of litellm level settings

This is useful for debugging and ensuring the proxy server is configured correctly.

Response schema:
```
{
    "alerting": _alerting,
    "litellm.callbacks": litellm_callbacks,
    "litellm.input_callback": litellm_input_callbacks,
    "litellm.failure_callback": litellm_failure_callbacks,
    "litellm.success_callback": litellm_success_callbacks,
    "litellm._async_success_callback": litellm_async_success_callbacks,
    "litellm._async_failure_callback": litellm_async_failure_callbacks,
    "litellm._async_input_callback": litellm_async_input_callbacks,
    "all_litellm_callbacks": all_litellm_callbacks,
    "num_callbacks": len(all_litellm_callbacks),
    "num_alerting": _num_alerting,
    "litellm.request_timeout": litellm.request_timeout,
}
```
 * @summary Active Callbacks
 */
export type activeCallbacksSettingsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type activeCallbacksSettingsGetResponseComposite =
  activeCallbacksSettingsGetResponse200;

export type activeCallbacksSettingsGetResponse =
  activeCallbacksSettingsGetResponseComposite & {
    headers: Headers;
  };

export const getActiveCallbacksSettingsGetUrl = () => {
  return `/settings`;
};

export const activeCallbacksSettingsGet = async (
  options?: RequestInit
): Promise<activeCallbacksSettingsGetResponse> => {
  const res = await fetch(getActiveCallbacksSettingsGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: activeCallbacksSettingsGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as activeCallbacksSettingsGetResponse;
};

/**
 * Unprotected endpoint for checking if worker can receive requests
 * @summary Health Readiness
 */
export type healthReadinessHealthReadinessGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthReadinessHealthReadinessGetResponseComposite =
  healthReadinessHealthReadinessGetResponse200;

export type healthReadinessHealthReadinessGetResponse =
  healthReadinessHealthReadinessGetResponseComposite & {
    headers: Headers;
  };

export const getHealthReadinessHealthReadinessGetUrl = () => {
  return `/health/readiness`;
};

export const healthReadinessHealthReadinessGet = async (
  options?: RequestInit
): Promise<healthReadinessHealthReadinessGetResponse> => {
  const res = await fetch(getHealthReadinessHealthReadinessGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: healthReadinessHealthReadinessGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthReadinessHealthReadinessGetResponse;
};

/**
 * Unprotected endpoint for checking if worker is alive
 * @summary Health Liveliness
 */
export type healthLivelinessHealthLivenessGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthLivelinessHealthLivenessGetResponseComposite =
  healthLivelinessHealthLivenessGetResponse200;

export type healthLivelinessHealthLivenessGetResponse =
  healthLivelinessHealthLivenessGetResponseComposite & {
    headers: Headers;
  };

export const getHealthLivelinessHealthLivenessGetUrl = () => {
  return `/health/liveness`;
};

export const healthLivelinessHealthLivenessGet = async (
  options?: RequestInit
): Promise<healthLivelinessHealthLivenessGetResponse> => {
  const res = await fetch(getHealthLivelinessHealthLivenessGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: healthLivelinessHealthLivenessGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthLivelinessHealthLivenessGetResponse;
};

/**
 * Unprotected endpoint for checking if worker is alive
 * @summary Health Liveliness
 */
export type healthLivelinessHealthLivelinessGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthLivelinessHealthLivelinessGetResponseComposite =
  healthLivelinessHealthLivelinessGetResponse200;

export type healthLivelinessHealthLivelinessGetResponse =
  healthLivelinessHealthLivelinessGetResponseComposite & {
    headers: Headers;
  };

export const getHealthLivelinessHealthLivelinessGetUrl = () => {
  return `/health/liveliness`;
};

export const healthLivelinessHealthLivelinessGet = async (
  options?: RequestInit
): Promise<healthLivelinessHealthLivelinessGetResponse> => {
  const res = await fetch(getHealthLivelinessHealthLivelinessGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: healthLivelinessHealthLivelinessGetResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthLivelinessHealthLivelinessGetResponse;
};

/**
 * Test a direct connection to a specific model.

This endpoint allows you to verify if your proxy can successfully connect to a specific model.
It's useful for troubleshooting model connectivity issues without going through the full proxy routing.

Example:
```bash
curl -X POST 'http://localhost:4000/health/test_connection' \
  -H 'Authorization: Bearer sk-1234' \
  -H 'Content-Type: application/json' \
  -d '{
    "litellm_params": {
        "model": "gpt-4",
        "custom_llm_provider": "azure_ai",
        "litellm_credential_name": null,
        "api_key": "6xxxxxxx",
        "api_base": "https://litellm8397336933.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21",
    },
    "mode": "chat"
  }'
```

Returns:
    dict: A dictionary containing the health check result with either success information or error details.
 * @summary Test Model Connection
 */
export type testModelConnectionHealthTestConnectionPostResponse200 = {
  data: unknown;
  status: 200;
};

export type testModelConnectionHealthTestConnectionPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type testModelConnectionHealthTestConnectionPostResponseComposite =
  | testModelConnectionHealthTestConnectionPostResponse200
  | testModelConnectionHealthTestConnectionPostResponse422;

export type testModelConnectionHealthTestConnectionPostResponse =
  testModelConnectionHealthTestConnectionPostResponseComposite & {
    headers: Headers;
  };

export const getTestModelConnectionHealthTestConnectionPostUrl = () => {
  return `/health/test_connection`;
};

export const testModelConnectionHealthTestConnectionPost = async (
  bodyTestModelConnectionHealthTestConnectionPost: BodyTestModelConnectionHealthTestConnectionPost,
  options?: RequestInit
): Promise<testModelConnectionHealthTestConnectionPostResponse> => {
  const res = await fetch(getTestModelConnectionHealthTestConnectionPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(bodyTestModelConnectionHealthTestConnectionPost),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: testModelConnectionHealthTestConnectionPostResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as testModelConnectionHealthTestConnectionPostResponse;
};
